project:
  type: website
  render:
    - "*.qmd"
    - "!*.md"
    - "!**/ENVX2001_*.qmd"

execute:
  freeze: auto

profile:
  default: exercise
  group:
    - [exercise, solution] # `--profile solution` activates BOTH; pairs with _quarto-solution.yml

website:
  page-navigation: true
  page-footer:
    right: The University of Sydney
  navbar:
    title: ENVX2001 Resources

format:
  html:
    theme: cosmo
    fontsize: 12pt
    code-copy: true
    code-overflow: wrap
    toc: false
