---
title: ENVX2001 Resources
author:
  - Januar Harianto
  - Si Yang Han
  - Liana Pozza
anchor-sections: false
section-divs: false
---

This site hosts lectures, tutorials, and labs for ENVX2001. Some content is still being developed and may be incomplete. Students can find all course material on [Canvas](https://canvas.sydney.edu.au/).

### Module 1: Designed studies

::: {tbl-colwidths="[10,45,25,20]"}
| Week | Lecture | Tutorial | Lab |
|------|---------|----------|-----|
| 1 | [Introduction][L01] | [Tutorial 01][T01] [{{< fa file-pdf >}}][T01pdf] | [Lab 01][Lab01] [{{< fa file-pdf >}}][Lab01pdf] |
| 2 | [Sampling designs][L02] | [Tutorial 02][T02] [{{< fa file-pdf >}}][T02pdf] | [Lab 02][Lab02] [{{< fa file-pdf >}}][Lab02pdf] |
| 3 | [1-way ANOVA][L03] | [Tutorial 03][T03] [{{< fa file-pdf >}}][T03pdf] | [Lab 03][Lab03] [{{< fa file-pdf >}}][Lab03pdf] |
| 4 | [Residual diagnostics & post hoc tests][L04] | [Tutorial 04][T04] [{{< fa file-pdf >}}][T04pdf] | [Lab 04][Lab04] [{{< fa file-pdf >}}][Lab04pdf] |
| 5 | [Experimental design][L05] | [Tutorial 05][T05] [{{< fa file-pdf >}}][T05pdf] | [Lab 05][Lab05] [{{< fa file-pdf >}}][Lab05pdf] |
| 6 | [ANOVA with blocking][L06] | [Tutorial 06][T06] [{{< fa file-pdf >}}][T06pdf] | [Lab 06][Lab06] [{{< fa file-pdf >}}][Lab06pdf] |
:::

### Module 2: Finding patterns in data

::: {tbl-colwidths="[10,45,25,20]"}
| Week | Lecture | Tutorial | Lab |
|------|---------|----------|-----|
| 7  | [Regression modelling][L07] | [Tutorial 07][T07] [{{< fa file-pdf >}}][T07pdf] | [Lab 07][Lab07] [{{< fa file-pdf >}}][Lab07pdf] |
| 8  | [Regression model development][L08] | [Tutorial 08][T08] [{{< fa file-pdf >}}][T08pdf] | [Lab 08][Lab08] [{{< fa file-pdf >}}][Lab08pdf] |
| 9  | [Regression model assessment][L09] | -- | [Lab 09][Lab09] [{{< fa file-pdf >}}][Lab09pdf] |
| 10 | Principle component analysis | [Tutorial 10][T10] [{{< fa file-pdf >}}][T10pdf] | [Lab 10][Lab10] [{{< fa file-pdf >}}][Lab10pdf] |
| 11 | Clustering | [Tutorial 11][T11] [{{< fa file-pdf >}}][T11pdf] | [Lab 11][Lab11] [{{< fa file-pdf >}}][Lab11pdf] |
| 12 | Multidimensional scaling | [Tutorial 12][T12] [{{< fa file-pdf >}}][T12pdf] | [Lab 12][Lab12] [{{< fa file-pdf >}}][Lab12pdf] |
:::

<!-- Links -->
[L01]: lectures/L01/index.qmd
[L02]: lectures/L02/index.qmd
[L03]: lectures/L03/index.qmd
[L04]: lectures/L04/index.qmd
[L05]: lectures/L05/index.qmd
[L06]: lectures/L06/index.qmd
[L07]: lectures/L07/index.qmd
[L08]: lectures/L08/index.qmd
[L09]: lectures/L09/index.qmd
[T01]: tutorials/tutorial01.qmd
[T02]: tutorials/tutorial02.qmd
[T03]: tutorials/tutorial03.qmd
[T04]: tutorials/tutorial04.qmd
[T05]: tutorials/tutorial05.qmd
[T06]: tutorials/tutorial06.qmd
[T07]: tutorials/tutorial07.qmd
[T08]: tutorials/tutorial08.qmd
[T10]: tutorials/tutorial10.qmd
[T11]: tutorials/tutorial11.qmd
[T12]: tutorials/tutorial12.qmd
[T01pdf]: tutorials/tutorial01.pdf
[T02pdf]: tutorials/tutorial02.pdf
[T03pdf]: tutorials/tutorial03.pdf
[T04pdf]: tutorials/tutorial04.pdf
[T05pdf]: tutorials/tutorial05.pdf
[T06pdf]: tutorials/tutorial06.pdf
[T07pdf]: tutorials/tutorial07.pdf
[T08pdf]: tutorials/tutorial08.pdf
[T10pdf]: tutorials/tutorial10.pdf
[T11pdf]: tutorials/tutorial11.pdf
[T12pdf]: tutorials/tutorial12.pdf
[Lab01]: labs/Lab01/Lab01-introduction.qmd
[Lab02]: labs/Lab02/Lab02-sampling-designs.qmd
[Lab03]: labs/Lab03/Lab03-oneway-anova.qmd
[Lab04]: labs/Lab04/Lab04-residuals-posthoc.qmd
[Lab05]: labs/Lab05/Lab05-exp-designs.qmd
[Lab06]: labs/Lab06/Lab06-factorial-anova.qmd
[Lab07]: labs/Lab07/Lab07-regression-modelling.qmd
[Lab08]: labs/Lab08/Lab08-model-selection.qmd
[Lab09]: labs/Lab09/Lab09-regression-assessment.qmd
[Lab10]: labs/Lab10/Lab10-pca.qmd
[Lab11]: labs/Lab11/Lab11-clustering.qmd
[Lab12]: labs/Lab12/Lab12-nmds.qmd
[Lab01pdf]: labs/Lab01/Lab01-introduction.pdf
[Lab02pdf]: labs/Lab02/Lab02-sample-designs.pdf
[Lab03pdf]: labs/Lab03/Lab03-oneway-anova.pdf
[Lab04pdf]: labs/Lab04/Lab04-residuals-posthoc.pdf
[Lab05pdf]: labs/Lab05/Lab05-exp-designs.pdf
[Lab06pdf]: labs/Lab06/Lab06-factorial-anova.pdf
[Lab07pdf]: labs/Lab07/Lab07-regression-modelling.pdf
[Lab08pdf]: labs/Lab08/Lab08-model-selection.pdf
[Lab09pdf]: labs/Lab09/Lab09-regression-assessment.pdf
[Lab10pdf]: labs/Lab10/Lab10-pca.pdf
[Lab11pdf]: labs/Lab11/Lab11-clustering.pdf
[Lab12pdf]: labs/Lab12/Lab12-nmds.pdf
