{
  "hash": "29898f4ae8f1ff461b46bfd67294f5f4",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Tutorial 03\"\n# reviewed-by:\nformat:\n  sandstone-html:\n    code-tools: true\n---\n\n## Welcome {.unnumbered}\n\nIn this tutorial we will learn the diagnostic tools for checking assumptions behind *t*-tests and ANOVA, then take apart an ANOVA table to understand what every number means.\n\nYou will learn how to:\n\n1. Identify the three assumptions of *t*-tests and ANOVA.\n2. Use R to produce diagnostic plots and numerical checks.\n3. Read diagnostics and decide whether assumptions are met.\n4. Read an ANOVA table and interpret the F ratio and degrees of freedom.\n\n\n\n\n# Checking assumptions\n\nWhat assumptions do *t*-tests and ANOVA make? There are three:\n\n1. **Normality**: the residuals follow a normal distribution.\n2. **Equal variance**: the spread of observations is roughly the same across groups.\n3. **Independence**: the observations do not influence each other.\n\nWe can check the first two from the data. Independence comes from the study design (random assignment, no repeated measures on the same subject), so we cannot diagnose it from a plot.\n\n\n## Exercise 1: Checking assumptions in R {.unnumbered}\n\nThe diagnostics are the same whether we fit a *t*-test or an ANOVA. Run each block and the tutor will walk through the output.\n\n::: {.column-margin}\nThe `sleep` dataset records the change in hours of sleep for 10 patients under two drug treatments (20 observations total). It is built into R, so no file download is needed.\n:::\n\n::: {.panel-tabset}\n\n### t-test\n\nThe `t.test()` object does not store residuals, so we check normality on the raw data in each group. This is equivalent to checking the residuals, since within each group the residuals are just the values minus the group mean (same shape, shifted to zero). With only two groups this is straightforward:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(sleep)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Subset the data into two groups\ngroup1 <- subset(sleep, group == \"1\")\ngroup2 <- subset(sleep, group == \"2\")\n\n# QQ plot for Group 1\nqqnorm(group1$extra, main = \"Group 1\")\nqqline(group1$extra, col = \"red\")\n\n# QQ plot for Group 2\nqqnorm(group2$extra, main = \"Group 2\")\nqqline(group2$extra, col = \"red\")\n\n# Shapiro-Wilk test for normality in Group 1\nshapiro.test(group1$extra)\n\n# Shapiro-Wilk test for normality in Group 2\nshapiro.test(group2$extra)\n```\n:::\n\n\n### ANOVA\n\nANOVA and the *t*-test are mathematically equivalent when there are only two groups, so we can fit an ANOVA to the same data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- aov(extra ~ group, data = sleep)\n```\n:::\n\n\nWith `aov()`, residuals are built in:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqqnorm(residuals(model), main = \"\")\nqqline(residuals(model), col = \"red\")\nshapiro.test(residuals(model))\n```\n:::\n\n\n:::\n\n**Equal variance** (this check is the same whether you used the *t*-test or ANOVA approach above):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboxplot(extra ~ group, data = sleep)\n\n# Using group1 and group2 from the t-test tab (or re-create them here)\ngroup1 <- subset(sleep, group == \"1\")\ngroup2 <- subset(sleep, group == \"2\")\nmax(sd(group1$extra), sd(group2$extra)) /\n  min(sd(group1$extra), sd(group2$extra))\n```\n:::\n\n\n::: {.column-margin}\nThe SD ratio rule of thumb: below 2 is generally acceptable.\n:::\n\n**Independence** cannot be checked from data. It comes from the study design: random assignment, no repeated measures on the same subject.\n\nR can also produce four diagnostic plots at once with `plot(aov(...))`, including the QQ plot and two others we have not covered yet. We will explore these in the lab next week.\n\n### Reading diagnostics {.unnumbered}\n\nNow that we know the code, can we read the output? The widget below generates random data with 2 to 4 groups, shows one diagnostic, and asks whether the assumption holds.\n\n```{ojs}\n//| echo: false\nimport { assumptionCheckerWidget } from \"../assets/js/assumption-checker.js\"\nassumptionCheckerWidget()\n```\n\n::: {.callout-note}\n## Checkpoint\nWe should be able to run the diagnostic checks in R, read the output, and decide whether the assumption is met.\n:::\n\n\n# The ANOVA table\n\nWhen we run `summary(aov(...))` in R, we get an ANOVA table. Most people skip straight to the p-value, but every number in the table tells us something about the data and the experiment. The two most important things to understand are the **F ratio** (is there a real effect, or just noise?) and the **degrees of freedom** (how big was the experiment?).\n\n::: {.column-margin}\nANOVA table interpretation and basic calculations (the F ratio and degrees of freedom) are examinable.\n:::\n\n\n## Exercise 2: The F ratio and degrees of freedom {.unnumbered}\n\nA researcher tested three planting densities of a maize fodder crop (low, medium, and high) across 15 plots, with 5 plots per density. The sample means and standard deviations (kg of dry matter per plot) are:\n\n\n::: {#tbl-maize-summary .cell tbl-cap='Sample means and standard deviations of dry matter yield (kg per plot) for three planting densities of maize.'}\n::: {.cell-output-display}\n\n\n|Density |  Mean| Std.Dev|\n|:-------|-----:|-------:|\n|Low     | 17.58|    2.70|\n|Medium  | 27.18|    1.89|\n|High    | 27.14|    2.02|\n\n\n:::\n:::\n\n\nThe low-density group produced noticeably less dry matter than the other two. But is that difference real, or could it be noise? Here is the ANOVA table R produces:\n\n\n::: {#tbl-anova-maize .cell tbl-cap='One-way ANOVA for the effect of planting density on dry matter yield of maize.'}\n::: {.cell-output-display}\n\n\n|Source    | Df| Sum Sq| Mean Sq|F value |Pr(>F)  |\n|:---------|--:|------:|-------:|:-------|:-------|\n|Treatment |  2| 305.92|  152.96|30.77   |< 0.001 |\n|Residual  | 12|  59.65|    4.97|        |        |\n\n\n:::\n:::\n\n\nA second researcher tested three fertiliser blends on wheat yield using the same design (3 treatments, 5 plots each). Their table:\n\n\n::: {#tbl-anova-wheat .cell tbl-cap='One-way ANOVA for the effect of fertiliser blend on wheat yield.'}\n::: {.cell-output-display}\n\n\n|Source    | Df| Sum Sq| Mean Sq|F value |Pr(>F) |\n|:---------|--:|------:|-------:|:-------|:------|\n|Treatment |  2|   11.4|     5.7|1.14    |0.35   |\n|Residual  | 12|   60.0|     5.0|        |       |\n\n\n:::\n:::\n\n\n### The F ratio {.unnumbered}\n\nThe F value is a signal-to-noise ratio:\n\n$$F = \\frac{MS_{trt}}{MS_{res}}$$\n\n$MS_{trt}$ (treatment mean square) measures how much the group means differ from the overall mean. $MS_{res}$ (residual mean square) measures the scatter within each group. When F is close to 1, the groups look no more different than random noise would produce. When F is large, the data suggest a real effect.\n\nIn the maize table, $F = 152.96 \\div 4.97 = 30.77$. The between-group signal is about 30 times larger than the within-group noise, and the p-value is tiny. Planting density clearly affects dry matter yield.\n\nIn the wheat table, $F = 5.70 \\div 5.00 = 1.14$. The treatment variation is about the same size as the residual noise. The fertiliser blends made no detectable difference.\n\n::: {.column-margin}\nThe sum of squares (Sum Sq) in the treatment and residual rows add up to the total variation in the data. The ANOVA table partitions all variation into two sources: differences between groups and scatter within groups.\n:::\n\n### Degrees of freedom {.unnumbered}\n\nThe degrees of freedom tell us about the size and shape of the experiment:\n\n- **Treatment df** $= t - 1$, where $t$ is the number of groups. Both tables show df = 2, so both experiments compared 3 groups.\n- **Residual df** $= N - t$, where $N$ is the total number of observations. Both tables show df = 12, so $N = 12 + 3 = 15$ observations in each experiment.\n- Each group therefore had $15 \\div 3 = 5$ replicates.\n\n### Try it yourself {.unnumbered}\n\nA colleague compared 4 watering regimes on tomato plants, with 6 plants per regime. Their ANOVA table shows $MS_{trt} = 45.2$ and $MS_{res} = 8.1$, but they forgot to include the F value and degrees of freedom.\n\n1. What are the treatment and residual degrees of freedom?\n2. Calculate the F ratio.\n3. The critical value at $\\alpha = 0.05$ for these degrees of freedom is 3.10. Is the result significant?\n\n::: {.column-margin}\nIf the observed F exceeds the critical value, we reject the null hypothesis at that significance level. You can find critical values in R with `qf(0.05, df1, df2, lower.tail = FALSE)`.\n:::\n\n::: {.callout-note}\n## Checkpoint\nWe should be able to read an ANOVA table, explain what F measures (between-group variation divided by within-group variation), compute F from the mean squares, and work out the number of groups and observations from the degrees of freedom.\n:::\n\n\n## Wrap-up {.unnumbered}\n\nWe covered the diagnostic tools for checking assumptions and learned to read an ANOVA table. In the lab, we will fit ANOVA models in R and use post-hoc tests to identify which groups differ.\n",
    "supporting": [
      "tutorial03_files/figure-typst"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}