{
  "hash": "7ac0679bceee5dad9971c21cd33d2316",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Lab 06\n# revised-by:\nsubtitle: ENVX2001 Applied Statistical Methods\ndescription: The University of Sydney\ntoc: true\ntoc-depth: 3\nresources:\n  - data/tasmanian_devil_aggression.csv\n---\n\n# Welcome!\n\nThis week we will analyse a factorial experiment using ANOVA: first as a completely randomised design (CRD), then as a randomised complete block design (RCBD). The experiment investigates aggressive interactions in Tasmanian devils.\n\nYou will come across **Exercises** in this lab. Solutions will be posted on Friday evening.\n\n## Learning outcomes\n\nAt the end of this practical students should be able to:\n\n* use R to analyse experiments with a factorial treatment structure where the experimental design is a CRD or RCBD;\n\n## Specific goals\n\nBy the end of this lab, you should be able to:\n\n- [ ] Fit and interpret a factorial ANOVA for a CRD\n- [ ] Check ANOVA assumptions and apply transformations when needed\n- [ ] Fit a factorial ANOVA with a blocking term for an RCBD\n- [ ] Perform post-hoc tests using `emmeans`\n- [ ] Calculate the percentage of variation explained by blocking\n\n## Preparation\n\nThis lab uses `emmeans`. Install it if you are missing it by running the following **in the console**:\n\n```r\ninstall.packages(\"emmeans\")\n```\n\n### Downloads\n\n| File | Used in | Download |\n|---|---|---|\n| `tasmanian_devil_aggression.csv` | Sections 1 and 2 | [Download](data/tasmanian_devil_aggression.csv) |\n\n\n# 1. Factorial ANOVA as CRD (~30 min)\n\nYou are interested in investigating if aggressive interactions between Tasmanian devil individuals are influenced by eating in a group or alone, and if they are male or female. You conduct an experiment where you observe the number of aggressive interactions between individuals in a 10 minute trial.  You have 12 nights to conduct the experiment and each night you observe one trial for each of the 4 treatment combinations.\n\nAnalyse the data using a factorial ANOVA as if it was collected by a CRD.\n\nThe data is in the **tasmanian_devil_aggression.csv** file.\n\nFactors:\n\n- feeding_context: Alone vs Group\n- sex: Female vs Male\n\nResponse variables:\n\n- aggression_count (integer count per trial)\n- log_aggression = log(aggression_count + 1)\n\n\nBlocking factor (we will ignore this for the CRD analysis but it will be used in the RCBD analysis):\n\n- block: Night_01 … Night_12 (each night includes all 4 treatment combinations)\n- Total N: 12 blocks × 2 sexes × 2 contexts = 48 trials (1 obs per cell per block)\n\n\n![Tasmanian devil (*Sarcophilus harrisii*) is the largest carnivorous marsupial in the world. Image credit: Wayne McLean.](images/devil_Wayne_McLean.png)\n\n## Analysis\n\n::: {.question}\n### Exercise 1\n\n*(i)* Write out the statistical model for the factorial ANOVA for this experiment.  Define all the terms in the model. You can write out in words or in mathematical notation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Answer here\n```\n:::\n\n\n\n*(ii)* Test the assumptions of the factorial ANOVA and transform the data (if needed). Hint first run the model using the `aov()` function and then use the `plot()` function to check the assumptions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#\n```\n:::\n\n\n*(iii)* Use an ANOVA to analyse the CRD and report on the results.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#\n```\n:::\n\n\n*(iv)* Explore any significant results using post-hoc tests from `emmeans` package and its `emmeans()` function. Include any plots that you think are useful to visualise the results.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#\n```\n:::\n\n:::\n\n::: {.content-visible when-profile=\"solution\"}\n::: {.ans}\n#### Solution\n\n##### *(i)* The statistical model for the factorial ANOVA is:\n$$\nY_{ijk} = \\mu + \\alpha_i + \\beta_j + (\\alpha\\beta)_{ij} + \\epsilon_{ijk}\n$$\n\nWhere:\n\n- $Y_{ijk}$ is the response variable (aggression count) for the $k$th observation in the $i$th level of feeding context and $j$th level of sex\n- $\\mu$ is the overall mean aggression count\n- $\\alpha_i$ is the effect of the $i$th level of feeding context (Alone vs Group)\n- $\\beta_j$ is the effect of the $j$th level of sex (Female vs Male)\n\n- $(\\alpha\\beta)_{ij}$ is the interaction effect between feeding context and sex\n- $\\epsilon_{ijk}$ is the random error term for the $k$th observation in the $i$th level of feeding context and $j$th level of sex and is assumed to be normally distributed with mean 0 and constant variance $\\sigma^2$.\n\nOR:\n\n$$Aggression\\ count = overall\\ mean +  feeding\\ context +  sex + feeding\\ context\\times sex + random\\ error$$\n\n\n##### *(ii)* Test the assumptions of the factorial ANOVA and transform the data (if needed).\n\nRead in the data and convert to `factor` if required.\n\n::: {.cell}\n\n```{.r .cell-code}\ndevil <- read.csv(\"data/tasmanian_devil_aggression.csv\")\nstr(devil)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t48 obs. of  6 variables:\n $ id              : int  1 2 3 4 5 6 7 8 9 10 ...\n $ block           : chr  \"Night_01\" \"Night_01\" \"Night_01\" \"Night_01\" ...\n $ sex             : chr  \"Female\" \"Female\" \"Male\" \"Male\" ...\n $ feeding_context : chr  \"Alone\" \"Group\" \"Alone\" \"Group\" ...\n $ aggression_count: int  3 5 5 8 1 4 3 3 5 3 ...\n $ log_aggression  : num  1.386 1.792 1.792 2.197 0.693 ...\n```\n\n\n:::\n\n```{.r .cell-code}\ndevil$feeding_context <- as.factor(devil$feeding_context)\ndevil$sex <- as.factor(devil$sex)\nstr(devil)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t48 obs. of  6 variables:\n $ id              : int  1 2 3 4 5 6 7 8 9 10 ...\n $ block           : chr  \"Night_01\" \"Night_01\" \"Night_01\" \"Night_01\" ...\n $ sex             : Factor w/ 2 levels \"Female\",\"Male\": 1 1 2 2 1 1 2 2 1 1 ...\n $ feeding_context : Factor w/ 2 levels \"Alone\",\"Group\": 1 2 1 2 1 2 1 2 1 2 ...\n $ aggression_count: int  3 5 5 8 1 4 3 3 5 3 ...\n $ log_aggression  : num  1.386 1.792 1.792 2.197 0.693 ...\n```\n\n\n:::\n:::\n\n\nRun the model and check the assumptions with the `plot()` function.\n\n::: {.cell}\n\n```{.r .cell-code}\ndevil.aov <- aov(aggression_count ~ feeding_context*sex, data=devil)\n\npar(mfrow=c(1,2))\nplot(devil.aov, which=1)\nplot(devil.aov, which=2)\n```\n\n::: {.cell-output-display}\n![](Lab06-factorial-anova_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n\n```{.r .cell-code}\npar(mfrow=c(1,1))\n```\n:::\n\nThe residual diagnostics show that the data is not normally distributed, has unequal variance (fanning).  A log transformation is applied to the response variable to try and meet the assumptions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndevil.log.aov <- aov(log(aggression_count+1) ~ feeding_context*sex, data=devil)\n\npar(mfrow=c(1,2))\nplot(devil.log.aov, which=1)\nplot(devil.log.aov, which=2)\n```\n\n::: {.cell-output-display}\n![](Lab06-factorial-anova_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n\n```{.r .cell-code}\npar(mfrow=c(1,1))\n```\n:::\n\n\nThe residual diagnostics show that the data is not normally distributed, but now has equal variance.  Given ANOVA is robust against non-normality, we will proceed with the analysis using the log transformed response variable.\n\n##### *(iii)* Use an ANOVA to analyse the CRD and report on the results.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(devil.log.aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                    Df Sum Sq Mean Sq F value   Pr(>F)    \nfeeding_context      1  4.937   4.937  16.637 0.000187 ***\nsex                  1  2.752   2.752   9.274 0.003917 ** \nfeeding_context:sex  1  0.082   0.082   0.276 0.601716    \nResiduals           44 13.058   0.297                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\nThe ANOVA table shows that there is not a significant interaction between `feeding_context` and `sex` with a P-value of 0.60.  This means we can now move to the main effects and see that both `feeding_context` and `sex` have a significant influence on `log_aggression`.\n\n##### *(iv)* Explore any significant results using post-hoc tests from `emmeans` package and its `emmeans()` function. Include any plots that you think are useful to visualise the results.\n\nMain effect of `feeding_context` is significant so we can use `emmeans()` to conduct post-hoc tests to determine which pairs are significantly different.  The results show that the `log_aggression` is significantly higher when feeding in a group compared to alone.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(emmeans)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWelcome to emmeans.\nCaution: You lose important information if you filter this package's results.\nSee '? untidy'\n```\n\n\n:::\n\n```{.r .cell-code}\nemmeans(devil.log.aov, pairwise ~ feeding_context)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNOTE: Results may be misleading due to involvement in interactions\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$emmeans\n feeding_context emmean    SE df lower.CL upper.CL\n Alone             1.12 0.111 44    0.894     1.34\n Group             1.76 0.111 44    1.535     1.98\n\nResults are averaged over the levels of: sex \nResults are given on the log(mu + 1) (not the response) scale. \nConfidence level used: 0.95 \n\n$contrasts\n contrast      estimate    SE df t.ratio p.value\n Alone - Group   -0.641 0.157 44  -4.079  0.0002\n\nResults are averaged over the levels of: sex \nNote: contrasts are still on the log(mu + 1) scale. Consider using\n      regrid() if you want contrasts of back-transformed estimates. \n```\n\n\n:::\n:::\n\n\n\nPlotting the marginal means for `feeding_context` shows that the `log_aggression` is higher when feeding in a group compared to alone.\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(emmeans(devil.log.aov, pairwise ~ feeding_context), comparisons = TRUE)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNOTE: Results may be misleading due to involvement in interactions\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Lab06-factorial-anova_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nThe main effect of `sex` is significant so we can use `emmeans()` to conduct post-hoc tests to determine which pairs are significantly different.  The results show that the `log_aggression` is significantly\n\n\n::: {.cell}\n\n```{.r .cell-code}\nemmeans(devil.log.aov, pairwise ~ sex)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNOTE: Results may be misleading due to involvement in interactions\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$emmeans\n sex    emmean    SE df lower.CL upper.CL\n Female   1.20 0.111 44    0.975     1.42\n Male     1.68 0.111 44    1.454     1.90\n\nResults are averaged over the levels of: feeding_context \nResults are given on the log(mu + 1) (not the response) scale. \nConfidence level used: 0.95 \n\n$contrasts\n contrast      estimate    SE df t.ratio p.value\n Female - Male   -0.479 0.157 44  -3.045  0.0039\n\nResults are averaged over the levels of: feeding_context \nNote: contrasts are still on the log(mu + 1) scale. Consider using\n      regrid() if you want contrasts of back-transformed estimates. \n```\n\n\n:::\n:::\n\nMales have a significantly higher `log_aggression` compared to females.\n\nPlotting:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(emmeans(devil.log.aov, pairwise ~ sex), comparisons = TRUE)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNOTE: Results may be misleading due to involvement in interactions\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Lab06-factorial-anova_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n:::\n:::\n\n\nBefore we move on, now is a good time to take a 5-minute break.\n\n\n# 2. Factorial ANOVA with blocking (~30 min)\n\nNow we will analyse the same experiment as above but this time we will include the blocking factor of `block` (night) in the analysis.  This means we will be analysing the data as if it was collected by a RCBD.\n\n## Analysis\n\n::: {.question}\n### Exercise 2\n\n*(i)* Write out the statistical model for the factorial ANOVA with blocking for this experiment.  Define all the terms in the model. You can write out in words or in mathematical notation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Answer here\n```\n:::\n\n\n\n*(ii)* Test the assumptions of the ANOVA model and transform the data (if needed). Hint first run the model using the `aov()` function and then use the `plot()` function to check the assumptions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#\n```\n:::\n\n\n*(iii)* Use an ANOVA to analyse the RCBD and report on the results.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#\n```\n:::\n\n\n*(iv)* Calculate how much variation the blocking term captured.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#\n```\n:::\n\n:::\n\n::: {.content-visible when-profile=\"solution\"}\n::: {.ans}\n#### Solution\n\n##### *(i)* The statistical model for the factorial ANOVA with blocking is:\n$$\nY_{ijkl} = \\mu + \\alpha_i + \\beta_j + (\\alpha\\beta)_{ij} + \\gamma_k + \\epsilon_{ijkl}\n$$\nWhere:\n\n- $Y_{ijkl}$ is the response variable (aggression count) for the $l $th observation in the $i$th level of feeding context, $j $th level of sex and $k$th block (night)\n- $\\mu$ is the overall mean aggression count\n- $\\alpha_i$ is the effect of the $i$th level of feeding context (Alone vs Group)\n- $\\beta_j$ is the effect of the $j $th level of sex (Male vs Female)\n- $(\\alpha\\beta)_{ij}$ is the interaction effect between feeding context and sex\n- $\\gamma_k$ is the effect of the $k$th block (night)\n- $\\epsilon_{ijkl}$ is the random error term for the $l$th observation in the $i$th level of feeding context, $j $th level of sex and $k$th block (night) and is assumed to be normally distributed with mean 0 and constant variance $\\sigma^2$.\n\nOR:\n\n$$Aggression\\ count = overall\\ mean + block + feeding\\ context + sex + feeding\\ context \\times sex + random\\ error$$\n\n##### *(ii)* Test the assumptions of the ANOVA model and transform the data (if needed).\nRun the model and check the assumptions with the `plot()` function.\n\n::: {.cell}\n\n```{.r .cell-code}\ndevil.block.aov <- aov(aggression_count ~ block + feeding_context * sex, data=devil)\npar(mfrow=c(1,2))\nplot(devil.block.aov, which=1)\nplot(devil.block.aov, which=2)\n```\n\n::: {.cell-output-display}\n![](Lab06-factorial-anova_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n\n```{.r .cell-code}\npar(mfrow=c(1,1))\n```\n:::\n\nThe residual diagnostics show that the data is not normally distributed, but has equal variance.  A log transformation is applied to the response variable to try and meet the assumption of normality.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndevil.block.log.aov <- aov(log(aggression_count+1) ~ block + feeding_context * sex, data=devil)\npar(mfrow=c(1,2))\nplot(devil.block.log.aov, which=1)\nplot(devil.block.log.aov, which=2)\n```\n\n::: {.cell-output-display}\n![](Lab06-factorial-anova_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n\n```{.r .cell-code}\npar(mfrow=c(1,1))\n```\n:::\n\nThe residual diagnostics show that the data is close to being normally distributed.  Given ANOVA is robust against non-normality, we will proceed with the analysis using the log transformed response variable.\n\n##### *(iii)* Use an ANOVA to analyse the RCBD and report on the results.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(devil.block.log.aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                    Df Sum Sq Mean Sq F value   Pr(>F)    \nblock               11  4.115   0.374   1.380 0.227950    \nfeeding_context      1  4.937   4.937  18.219 0.000156 ***\nsex                  1  2.752   2.752  10.156 0.003140 ** \nfeeding_context:sex  1  0.082   0.082   0.303 0.585914    \nResiduals           33  8.943   0.271                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\nThe ANOVA table shows that there is not a significant interaction between `feeding_context` and `sex` with a P-value of 0.59.  However, both main effects are significant.\n\n\n\n##### *(iv)* Calculate how much variation the blocking term captured.\n\nThe sum of squares for the block term is 4.115\nTotal sum of squares is:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTotal.SS <- 4.115+4.937+2.752+0.082+8.943\n\nTotal.SS\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 20.829\n```\n\n\n:::\n:::\n\nThe percentage of variation captured by the block term is:\n\n::: {.cell}\n\n```{.r .cell-code}\n(4.115/Total.SS)*100\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 19.75611\n```\n\n\n:::\n:::\n\nThe block term captured 19.76% of the variation in the data, so it was useful using a RCBD for this experiment.\n:::\n:::\n\n\n# Conclusion\n\n## Closing thoughts\n\nWe analysed a factorial experiment this week using Tasmanian devil aggression data: first as a CRD to test for main effects and interactions, then as an RCBD to account for night-to-night variation. These factorial designs and analysis techniques extend the one-way ANOVA methods from previous weeks.\n\n### Attribution\n\nThis lab was developed using resources that are available under a\n[Creative Commons Attribution 4.0 International license], made available\non the [SOLES Open Educational Resources repository].\n\n  [Creative Commons Attribution 4.0 International license]: http://creativecommons.org/licenses/by/4.0/\n  [SOLES Open Educational Resources repository]: https://github.com/usyd-soles-edu/\n",
    "supporting": [
      "Lab06-factorial-anova_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}