{
  "hash": "d3fb7f69faab71322b6be10f8c7fa3fa",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Lab 03\n# revised-by:\nsubtitle: ENVX2001 Applied Statistical Methods\ndescription: The University of Sydney\ntoc: true\ntoc-depth: 3\nresources:\n  - data/diatoms.xlsx\n  - data/chick_marigold.xlsx\n  - data/lambs.csv\n---\n\n# Welcome!\n\nThis week we will analyse diatom diversity in streams, compare comb weights in chicks, and test immunoglobulin levels across lamb breeds using one-way ANOVA.\n\nYou will come across two types of tasks in this lab. **Worked Examples** have solutions you can expand and check straight away. **Exercises** do not --- solutions for these will be posted on Friday evening.\n\nAs always, don't forget to take regular breaks in between sections. A good rule of thumb is to work for 20-25 minutes, then take a 5-minute break. This will help you stay focused and avoid burnout.\n\n## Learning outcomes\n\nIn this lab, we will learn how to:\n\n1. Explore grouped data using summary statistics and graphical summaries.\n2. Fit a one-way ANOVA using `aov()` and interpret the ANOVA table.\n3. Perform post-hoc comparisons using `emmeans`.\n4. Explain when a two-sample *t*-test gives the same results as a one-way ANOVA.\n\n## Specific goals\n\nBy the end of this lab, you should be able to:\n\n- [ ] Convert character variables to factors using `as.factor()`\n- [ ] Calculate group means and standard deviations\n- [ ] Produce boxplots for grouped data\n- [ ] Fit a one-way ANOVA and read the output table\n- [ ] Use `emmeans` for post-hoc testing\n- [ ] Compare *t*-test and ANOVA results for a two-group design\n\n## Preparation\n\nThis lab uses `tidyverse`, `readxl`, and `emmeans`. Install any you are missing by running the following **in the console**:\n\n```r\ninstall.packages(c(\"tidyverse\", \"readxl\", \"emmeans\"))\n```\n\n### Downloads\n\n| File | Used in | Download |\n|---|---|---|\n| `diatoms.xlsx` | Sections 1--2 | [Download](data/diatoms.xlsx) |\n| `chick_marigold.xlsx` | Section 3 | [Download](data/chick_marigold.xlsx) |\n| `lambs.csv` | Section 4 | [Download](data/lambs.csv) |\n\nSave all files into a folder called `data` inside your project folder.\n\n\n# 1. Exploring diatom diversity (~15 min)\n\nCoal miners once carried canaries underground as indicators of air toxicity. Diatoms are the freshwater equivalent, acting as bioindicators whose diversity changes with water quality. Medley and Clements (1998) surveyed 34 streams in the Rocky Mountains of Colorado, where decades of mining had left zinc leaching into the water, and counted diatom species at each site. Does zinc contamination reduce diatom diversity?\n\n## Getting started\n\nLet us warm up. This section is a quick refresher on data import, summary statistics, and plotting and should be straightforward if you have been following the labs in the past couple of weeks. If you have any questions, ask your tutor or post on Ed Discussion.\n\n::: {.question}\n### Worked Example 1\n\nImport the `Diatoms` worksheet from `diatoms.xlsx`, check the data structure with `str()`, and convert the character variables `Zinc` and `Stream` to factors. Use the code chunk below as a template for your own report.\n\n::: {.column-margin}\nIf you have difficulty importing, see the [data import guide](../tutorials/data-import.html).\n:::\n\n```r\nlibrary(tidyverse)\nlibrary(readxl)\n\n# Look at the Excel file to work out the worksheet name and range:\ndiatoms <- read_excel(\n    path = \"data/diatoms.xlsx\",\n    sheet = ...,\n    range = ...\n)\n\nstr(diatoms)\n\n# Convert character variables to factors:\ndiatoms <- diatoms |>\n    mutate(\n        Zinc = as.factor(Zinc),\n        Stream = as.factor(Stream)\n    )\n```\n\n:::\n\n::: {.callout-tip collapse=\"true\"}\n### Solution\n\n```r\nlibrary(tidyverse)\nlibrary(readxl)\n\ndiatoms <- read_excel(\n    path = \"data/diatoms.xlsx\",\n    sheet = \"Diatoms\",\n    range = \"A1:D35\"\n)\n\nstr(diatoms)\n\ndiatoms <- diatoms |>\n    mutate(\n        Zinc = as.factor(Zinc),\n        Stream = as.factor(Stream)\n    )\n```\n:::\n\n\n\n\n## Exploring the data\n\nBefore running any formal test, it helps to look at summary statistics and plots to see what patterns emerge.\n\n::: {.question}\n### Exercise 1\n\nCalculate the mean and standard deviation of `Diversity` for each level of `Zinc`. What do the values suggest about differences between groups?\n:::\n\n\n:::: {.content-visible when-profile=\"solution\"}\n::: {.ans}\n#### Solution\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiatoms |>\n    group_by(Zinc) |>\n    summarise(\n        mean = mean(Diversity),\n        sd = sd(Diversity)\n    )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n  Zinc   mean    sd\n  <fct> <dbl> <dbl>\n1 BACK   1.80 0.485\n2 HIGH   1.28 0.427\n3 LOW    2.03 0.445\n4 MED    1.72 0.503\n```\n\n\n:::\n:::\n\n\nThe mean diversity for the `HIGH` zinc level is noticeably lower than the other groups, suggesting that high zinc concentrations may reduce diatom diversity. The standard deviations are fairly uniform (ratio of largest to smallest is less than 2), so the assumption of constant variance appears reasonable.\n:::\n::::\n\nEven before doing any formal statistics, summary statistics are useful decision tools. If the means are very different and the standard deviations are small, we might already have a good idea that there are differences between groups, and knowing the distribution of the data can help us decide which test to use and how to check assumptions.\n\nHowever, numbers alone can be hard to interpret. This is where plotting comes in to present the data in a more intuitive way. A boxplot is a good choice for grouped data, as it shows the median, interquartile range, and potential outliers.\n\n##\n::: {.question}\n### Exercise 2\n\nProduce a boxplot of `Diversity` grouped by `Zinc`. Add appropriate axis labels. What does the plot tell you about differences between groups?\n:::\n\n::: {.column-margin}\nWith fewer than 10 observations per group, boxplots are often more informative than histograms.\n:::\n\n:::: {.content-visible when-profile=\"solution\"}\n::: {.ans}\n#### Solution\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(diatoms, aes(x = Zinc, y = Diversity)) +\n    geom_boxplot() +\n    labs(x = \"Zinc concentration\", y = \"Diversity\")\n```\n\n::: {.cell-output-display}\n![Boxplot of diatom diversity by zinc concentration.](Lab03-oneway-anova_files/figure-html/fig-diatom-boxplot-1.png){#fig-diatom-boxplot width=672}\n:::\n:::\n\n\n- The median diversity for the `HIGH` zinc group is noticeably lower than the other groups.\n- The boxes (Q1 to Q3) for the `HIGH` group do not overlap with those of the other groups, but the remaining groups overlap with each other. This is initial evidence that high zinc concentration is associated with lower diatom diversity.\n:::\n::::\n\n\nTake this opportunity to explore the data further if you like. You could make a histogram of the `Diversity` values within each `Zinc` group, or calculate other summary statistics such as the range or interquartile range. The more you understand the data before fitting a model, the better you will be able to interpret the results and check assumptions.\n\nOnce you are done, take a quick break. It is important to step away from the screen regularly.\n\n# 2. Testing for differences (~25 min)\n\nWe noticed (hopefully) in Section 1 that the `HIGH` zinc group has lower diatom diversity than the others. But is that difference real, or could it be random variation? A one-way ANOVA will test this formally.\n\n## The ANOVA model\n\nA one-way ANOVA tests whether the means of several groups are all equal. The model is:\n\n$$y_{i,j} = \\mu_i + \\varepsilon_{i,j}$$\n\nwhere $y_{i,j}$ is the diversity for observation $j$ in zinc group $i$, $\\mu_i$ is the mean of group $i$, and $\\varepsilon_{i,j}$ is the residual.\n\nThe hypotheses are:\n\n$$H_0: \\mu_1 = \\mu_2 = \\ldots = \\mu_t$$\n$$H_1: \\text{not all } \\mu_i \\text{ are equal}$$\n\n::: {.column-margin}\nWe will cover model assumptions formally next week when we look at residual diagnostics.\n:::\n\n## Fitting the model\n\nIn general, we \"fit a model\" when we test hypotheses, because models explain the relationships between data in a manner that is more flexible than fitting mathematical equations.\n\n::: {.question}\n### Worked Example 2\n\nFit a one-way ANOVA to test whether diatom diversity differs across zinc levels. Use `aov()` to fit the model and `summary()` to view the ANOVA table. Try to interpret the ANOVA table before looking at the solution below.\n\n::: {.column-margin}\nThe general formula is `aov(response ~ group, data = ...)`.\n:::\n\n:::\n\n::: {.callout-tip collapse=\"true\"}\n### Solution\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova.diatoms <- aov(Diversity ~ Zinc, data = diatoms)\nsummary(anova.diatoms)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value Pr(>F)  \nZinc         3  2.567  0.8555   3.939 0.0176 *\nResiduals   30  6.516  0.2172                 \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe ANOVA table shows:\n\n- **Df**: degrees of freedom. Treatment df = number of groups minus 1 (4 − 1 = 3). Residual df = total observations minus number of groups (34 − 4 = 30).\n- **Sum Sq**: how much variation is explained by the grouping (Zinc) versus left unexplained (Residuals).\n- **Mean Sq**: Sum Sq divided by Df. This gives the average variation per degree of freedom.\n- **F value**: the ratio of treatment Mean Sq to residual Mean Sq. A large F suggests that group differences are bigger than random noise.\n- **Pr(>F)**: the P-value. If this is below 0.05, we reject $H_0$.\n:::\n\n## Interpreting the results\n\nThe assumptions of the ANOVA (normality, equal variances, independence) appear reasonable based on our exploration in Section 1. The standard deviations were similar across groups, and nothing in the boxplot suggested serious departures from normality.\n\n**However**, we should always formally check the assumptions by looking at model residuals. We will cover this in more detail next week, but here is a quick look at normality and equal variance using the approach from Tutorial 3.\n\n::: {.panel-tabset}\n\n### QQ plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqqnorm(residuals(anova.diatoms), main = \"\")\nqqline(residuals(anova.diatoms), col = \"red\")\n```\n\n::: {.cell-output-display}\n![Normal QQ plot of residuals from the diatom ANOVA model.](Lab03-oneway-anova_files/figure-html/fig-diatom-qq-1.png){#fig-diatom-qq width=672}\n:::\n:::\n\n\n### Shapiro-Wilk test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshapiro.test(residuals(anova.diatoms))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  residuals(anova.diatoms)\nW = 0.96883, p-value = 0.43\n```\n\n\n:::\n:::\n\n\n:::\n\nThe QQ plot shows points falling roughly along the line, and the Shapiro-Wilk test is not significant (*P* > 0.05), so normality is reasonable. We already checked the SD ratio in Section 1 and found it was below 2, supporting equal variances.\n\n::: {.question}\n### Exercise 3\n\nBased on the ANOVA output from Worked Example 2, is there a significant difference in diatom diversity across zinc levels? Write a one-sentence reporting statement that includes the F statistic, degrees of freedom, and P-value.\n:::\n\n::: {.column-margin}\nA reporting statement typically follows this pattern: \"There was a significant difference in [response] across [groups] (*F* = ..., *df* = ..., *P* = ...).\"\n:::\n\n:::: {.content-visible when-profile=\"solution\"}\n::: {.ans}\n#### Solution\n\nThere are significant differences between the levels of zinc concentration in terms of diatom diversity (*F* = 3.9, *df* = 3, 30, *P* = 0.02).\n:::\n::::\n\n## Post-hoc comparisons\n\nThe ANOVA tells us that at least one group mean differs from the others, but not which ones. We use post-hoc testing to find out.\n\n::: {.question}\n### Worked Example 3\n\nUse the `emmeans` package to compute estimated marginal means and their confidence intervals for each zinc level. Then visualise the results with `plot()`.\n\n::: {.column-margin}\n`emmeans(model, \"factor_name\")` takes a fitted model and the name of the grouping variable.\n:::\n\n:::\n\n::: {.callout-tip collapse=\"true\"}\n### Solution\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(emmeans)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWelcome to emmeans.\nCaution: You lose important information if you filter this package's results.\nSee '? untidy'\n```\n\n\n:::\n\n```{.r .cell-code}\nposthoc <- emmeans(anova.diatoms, \"Zinc\")\nposthoc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Zinc emmean    SE df lower.CL upper.CL\n BACK   1.80 0.165 30    1.461     2.13\n HIGH   1.28 0.155 30    0.961     1.60\n LOW    2.03 0.165 30    1.696     2.37\n MED    1.72 0.155 30    1.401     2.04\n\nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\n\nThe output shows the estimated mean diversity for each zinc level, along with the standard error and 95% confidence interval. Groups whose confidence intervals do not overlap are likely to be significantly different.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(posthoc)\n```\n\n::: {.cell-output-display}\n![](Lab03-oneway-anova_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n:::\n\n##\n::: {.question}\n### Exercise 4\n\nBased on the `emmeans` output from Worked Example 3, which zinc levels differ from each other? How can you tell from the confidence intervals?\n:::\n\n:::: {.content-visible when-profile=\"solution\"}\n::: {.ans}\n#### Solution\n\nThe 95% confidence interval for the `HIGH` zinc level does not overlap with the confidence intervals of the other levels (BACK, LOW, MED). This indicates that the `HIGH` group has significantly lower diatom diversity. The confidence intervals for BACK, LOW, and MED overlap with each other, so we cannot conclude that they differ.\n:::\n::::\n\n\n**Now is a good time to take a 5-minute break.**\n\n\n# 3. Comparing *t*-tests and ANOVA (~20 min)\n\nSo far we have used ANOVA on data with four groups. But what happens when there are only two? In Lecture 03a we learned the two-sample *t*-test, and in Lecture 03b we learned ANOVA. This section shows they give the same answer when there are two groups.\n\nAn experiment compared 15-day mean comb weights (g) of male chicks receiving one of two hormones: A (testosterone) or C (dehydroandrosterone). With only two groups, we could use either a pooled two-sample *t*-test or a one-way ANOVA.\n\n## The data\n\nRead the *Comb* worksheet from `chick_marigold.xlsx` and convert `Hormone` to a factor:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncomb <- read_excel(\"data/chick_marigold.xlsx\", sheet = \"Comb\") |>\n    mutate(Hormone = as.factor(Hormone))\ncomb\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 22 × 2\n   CombWt Hormone\n    <dbl> <fct>  \n 1     57 A      \n 2    120 A      \n 3    101 A      \n 4    137 A      \n 5    119 A      \n 6    117 A      \n 7    104 A      \n 8     73 A      \n 9     53 A      \n10     68 A      \n# ℹ 12 more rows\n```\n\n\n:::\n:::\n\n\n##\n::: {.question}\n### Exercise 5\n\nBefore running any test, check whether the assumptions of normality and equal variance are reasonable. Produce a boxplot and calculate the standard deviations for each hormone group.\n:::\n\n:::: {.content-visible when-profile=\"solution\"}\n::: {.ans}\n#### Solution\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(comb, aes(x = Hormone, y = CombWt)) +\n    geom_boxplot() +\n    labs(x = \"Hormone\", y = \"Comb weight (g)\")\n```\n\n::: {.cell-output-display}\n![](Lab03-oneway-anova_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncomb |>\n    group_by(Hormone) |>\n    summarise(\n        mean = mean(CombWt),\n        sd = sd(CombWt)\n    )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  Hormone  mean    sd\n  <fct>   <dbl> <dbl>\n1 A          97  29.1\n2 C          56  27.8\n```\n\n\n:::\n:::\n\n\nThe distributions look roughly symmetrical with no outliers. The ratio of the larger SD to the smaller is less than 2, so the equal variance assumption is reasonable.\n:::\n::::\n\n##\n::: {.question}\n### Exercise 6\n\nRun a pooled two-sample *t*-test using `t.test(..., var.equal = TRUE)` and a one-way ANOVA using `aov()` on the same data. Compare:\n\ni. the degrees of freedom,\nii. the P-values, and\niii. the relationship between the *t* statistic and the *F* statistic.\n\nWhen there are two groups, $F = t^2$. Verify this for your results.\n:::\n\n::: {.column-margin}\nUse `var.equal = TRUE` in `t.test()` to get the pooled (Student's) *t*-test, which matches the ANOVA assumption of equal variances.\n:::\n\n:::: {.content-visible when-profile=\"solution\"}\n::: {.ans}\n#### Solution\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(CombWt ~ Hormone, var.equal = TRUE, data = comb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  CombWt by Hormone\nt = 3.3764, df = 20, p-value = 0.003\nalternative hypothesis: true difference in means between group A and group C is not equal to 0\n95 percent confidence interval:\n 15.66997 66.33003\nsample estimates:\nmean in group A mean in group C \n             97              56 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncomb.aov <- aov(CombWt ~ Hormone, data = comb)\nsummary(comb.aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value Pr(>F)   \nHormone      1   9245    9245    11.4  0.003 **\nResiduals   20  16220     811                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\ni. The *t*-test has *df* = 20. The ANOVA residual *df* is also 20. The treatment *df* is 1 (two groups minus one).\nii. Both P-values are 0.003.\niii. $F = t^2$: $(3.38)^2 = 11.4 = F_\\text{obs}$.\n\nWhen there are only two groups, the *t*-test and one-way ANOVA are mathematically equivalent. The ANOVA generalises the *t*-test to more than two groups.\n:::\n::::\n\n\nTake a break!\n\n# 4. Lambs (~25 min)\n\nThis final section is a capstone exercise. You will work through the entire ANOVA workflow on a new dataset with minimal guidance, bringing together everything from Sections 1 to 3.\n\nThe levels of immunoglobulin (Ig) in blood serum (g/100 ml) in three breeds of newborn lambs have been investigated. A total of 44 lambs were sampled, with approximately equal numbers per breed. Does immunoglobulin level differ between breeds?\n\n## The data\n\nHere is a preview of the dataset. You will import it yourself as part of the exercise.\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 44 × 2\n      Ig Breed\n   <dbl> <fct>\n 1   1.1 1    \n 2   2.2 1    \n 3   1.7 1    \n 4   1.4 1    \n 5   1.6 1    \n 6   2.3 1    \n 7   1.4 1    \n 8   1.9 1    \n 9   0.8 1    \n10   1.6 1    \n# ℹ 34 more rows\n```\n\n\n:::\n:::\n\n\n##\n::: {.question}\n### Exercise 7\n\nAnalyse the `lambs` dataset using the full ANOVA workflow. Test the hypothesis that:\n\n$$H_{0}: \\mu_1 = \\mu_2 = \\mu_3$$\n$$H_{1}: \\text{not all } \\mu_j \\text{ are equal}$$\n\nwhere $\\mu_j$ is the mean Ig level for breed $j$.\n\nWork through each step:\n\n- [ ] Read the data and convert `Breed` to a factor.\n- [ ] Produce a boxplot and calculate group means and standard deviations.\n- [ ] Check the equal variance assumption using the SD ratio.\n- [ ] Fit the model using `aov()` and report *F*, *df*, and *P*.\n- [ ] Run post-hoc comparisons using `emmeans()`.\n- [ ] Write a conclusion that addresses the null hypothesis and explains the results in a biological context.\n:::\n\n:::: {.content-visible when-profile=\"solution\"}\n::: {.ans}\n#### Solution\n\nRead the data and convert `Breed` to a factor:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlambs <- read_csv(\"data/lambs.csv\") |>\n    mutate(Breed = as.factor(Breed))\nstr(lambs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [44 × 2] (S3: tbl_df/tbl/data.frame)\n $ Ig   : num [1:44] 1.1 2.2 1.7 1.4 1.6 2.3 1.4 1.9 0.8 1.6 ...\n $ Breed: Factor w/ 3 levels \"1\",\"2\",\"3\": 1 1 1 1 1 1 1 1 1 1 ...\n```\n\n\n:::\n:::\n\n\nExploratory analysis:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlambs |>\n    group_by(Breed) |>\n    summarise(\n        n = n(),\n        mean = mean(Ig),\n        sd = sd(Ig)\n    )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n  Breed     n  mean    sd\n  <fct> <int> <dbl> <dbl>\n1 1        16  1.59 0.381\n2 2        13  2.23 0.352\n3 3        15  2.23 0.405\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(lambs, aes(x = Breed, y = Ig)) +\n    geom_boxplot() +\n    labs(x = \"Breed\", y = \"Ig level (g/100 ml)\")\n```\n\n::: {.cell-output-display}\n![](Lab03-oneway-anova_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\nThe distributions look roughly symmetrical. Check equal variance:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlamb_sds <- lambs |>\n    group_by(Breed) |>\n    summarise(sd = sd(Ig))\nmax(lamb_sds$sd) / min(lamb_sds$sd)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.149486\n```\n\n\n:::\n:::\n\n\nThe ratio of the largest to smallest SD is less than 2, so we can assume equal variances.\n\nFit the ANOVA:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlambs.aov <- aov(Ig ~ Breed, data = lambs)\nsummary(lambs.aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value   Pr(>F)    \nBreed        2  4.231  2.1156   14.56 1.67e-05 ***\nResiduals   41  5.959  0.1453                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe P-value is below 0.05, so we reject $H_0$. Post-hoc comparisons:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nposthoc_lambs <- emmeans(lambs.aov, \"Breed\")\nposthoc_lambs\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Breed emmean     SE df lower.CL upper.CL\n 1       1.59 0.0953 41     1.40     1.78\n 2       2.23 0.1060 41     2.02     2.44\n 3       2.23 0.0984 41     2.03     2.43\n\nConfidence level used: 0.95 \n```\n\n\n:::\n\n```{.r .cell-code}\nplot(posthoc_lambs)\n```\n\n::: {.cell-output-display}\n![](Lab03-oneway-anova_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n- There are significant differences in Ig levels across the three breeds (*F* = 14.6; *df* = 2, 41; *P* < 0.0001).\n- The 95% CI for Breed 1 does not overlap with the CIs for Breeds 2 and 3.\n- Breed 1 has substantially less immunoglobulin (1.59 ± 0.10 g/100 ml) than Breed 2 (2.23 ± 0.11 g/100 ml) and Breed 3 (2.23 ± 0.10 g/100 ml). This could have implications for disease susceptibility in newborn lambs of different breeds.\n:::\n::::\n\n\n# Conclusion\n\n## Closing thoughts\n\nIn this lab we worked through the full one-way ANOVA workflow: exploring grouped data, fitting a model with `aov()`, checking assumptions, running post-hoc comparisons with `emmeans`, and reporting results. We also saw that a two-sample *t*-test and a one-way ANOVA with two groups are mathematically equivalent ($F = t^2$, same P-value and residual degrees of freedom).\n\nNext week we will look at model residuals in more detail and learn formal diagnostic checks for the ANOVA assumptions.\n\n### Attribution\n\nThis lab was developed using resources that are available under a [Creative Commons Attribution 4.0 International license], made available on the [SOLES Open Educational Resources repository].\n\n  [Creative Commons Attribution 4.0 International license]: http://creativecommons.org/licenses/by/4.0/\n  [SOLES Open Educational Resources repository]: https://github.com/usyd-soles-edu/\n\n",
    "supporting": [
      "Lab03-oneway-anova_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}