{
  "hash": "bb17915db9eb862a0a272124bff3c35d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Lab 03\n# revised-by:\nresources:\n  - data/diatoms.xlsx\n---\n\nIn this week's lab we will work through the experimental design workflow for a one-way ANOVA.\n\n## Learning outcomes\nIn this lab, you will work towards achieving learning outcomes...\n\n### Lab objectives\nAt the end of the lab, students should be able to:\n\n- Understand the workflow involved in conducting a one-way Analysis of Variance (ANOVA), including data exploration, model fitting, and interpretation of results.\n- Analyse an experiment with a 1-way ANOVA and interpret the results.\n- Explain situations when a 2-sample t-test gives the same results as a 1-way ANOVA.\n\n## Prerequisites\n\nThe following packages are used for this lab: `readxl`, `ggplot2`, `dplyr` and `tidyr`. To install these packages, run the following code **in the console**.\n\n```r\ninstall.packages(c(\"readxl\", \"ggplot2\", \"dplyr\", \"tidyr\"))\n```\n\nYou will come across two types of tasks in this lab. **Worked Examples** have solutions you can expand and check straight away. **Exercises** do not --- solutions for these will be posted on Friday evening.\n\n## Exercise 1 -- diatoms\n\n\nMedley & Clements (1998) sampled 34 locations along streams for diversity of diatoms. Each site was classified according to the Zn concentration in the water. There were 4 classes; background, low, medium and high. Were there *differences* between each of the groupings in term of diatom diversity? Let's find out.\n\n\n::: {.question}\n\n### Worked Example 1 -- Data import\nImport the `Diatoms` worksheet from the `diatoms.xlsx` file into R. \n\nIf you have difficulty with this step, see the [data import guide](../tutorials/data-import.html).\n\n```r\nlibrary(readxl)\n\n# You will need to look at the Excel file and work out \n# the correct worksheet name and range:\ndiatoms <- read_excel(\n    path = \"diatoms.xlsx\",\n    sheet = ...,\n    range = ...\n)\n```\n\n\n:::\n\n\n\n\n\n### Workflow \nWe will briefly go through a typical analytical workflow which involves data exploration, model fitting, checking of model assumptions[^assump] and interpretation of the results.\n\n[^assump]: Assumptions will be covered formally next week when we look at model residuals.\n\n### Data exploration \n\n#### Data structure \nChecking the structure of the data is the first step in any data analysis. This is done using the `str()` function in R.\n\n```r\nstr(diatoms)\n```\n\nOf particular interest are the variables `Stream` and `Zinc`, which have been classified as characters (`chr`).\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [34 × 4] (S3: tbl_df/tbl/data.frame)\n $ Stream   : chr [1:34] \"Eagle\" \"Blue\" \"Blue\" \"Blue\" ...\n $ Zinc     : chr [1:34] \"BACK\" \"BACK\" \"BACK\" \"BACK\" ...\n $ Diversity: num [1:34] 2.27 1.7 2.05 1.98 2.2 1.53 0.76 1.89 1.4 2.18 ...\n $ Group    : num [1:34] 1 1 1 1 1 1 1 1 2 2 ...\n```\n\n\n:::\n:::\n\n\nThese variables are most likely factors and should be converted to such. This can be done using `as.factor()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiatoms$Zinc <- as.factor(diatoms$Zinc)\ndiatoms$Stream <- as.factor(diatoms$Stream)\n```\n:::\n\n\n\n\n::: callout-tip\n**The `tidyverse` approach** -- We can use the `mutate()` function to convert the `Zinc` and `Stream` variables to factors.\n\n```r\nlibrary(dplyr)\ndiatoms <- diatoms %>%\n    mutate(\n        Zinc = as.factor(Zinc),\n        Stream = as.factor(Stream)\n    )\n```\n\n\n:::\n\nWe can then check if the conversion was successful by using the `str()` function again.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(diatoms)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [34 × 4] (S3: tbl_df/tbl/data.frame)\n $ Stream   : Factor w/ 6 levels \"Arkan\",\"Blue\",..: 4 2 2 2 5 6 6 6 1 1 ...\n $ Zinc     : Factor w/ 4 levels \"BACK\",\"HIGH\",..: 1 1 1 1 1 1 1 1 3 3 ...\n $ Diversity: num [1:34] 2.27 1.7 2.05 1.98 2.2 1.53 0.76 1.89 1.4 2.18 ...\n $ Group    : num [1:34] 1 1 1 1 1 1 1 1 2 2 ...\n```\n\n\n:::\n:::\n\n\n\n#### Summary statistics\n\nUse `summary()` for a quick overview of common statistical measures for each variable in the data frame. However it is not informative when we are interested in differences between groups or factors as it only gives the summary statistics for the entire data set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(diatoms)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Stream    Zinc     Diversity         Group      \n Arkan:7   BACK:8   Min.   :0.630   Min.   :1.000  \n Blue :7   HIGH:9   1st Qu.:1.377   1st Qu.:2.000  \n Chalk:5   LOW :8   Median :1.855   Median :3.000  \n Eagle:4   MED :9   Mean   :1.694   Mean   :2.559  \n Snake:5            3rd Qu.:2.058   3rd Qu.:3.750  \n Splat:6            Max.   :2.830   Max.   :4.000  \n```\n\n\n:::\n:::\n\n\n\n\nIt is more useful to calculate summary statistics for each level of Zn contamination, as we are interested in differences between the mean of each group.\n\nWe can use the `tapply()` function to calculate the mean and standard deviation for each level of `Zinc`. This has to be done separately for each summary statistic (mean and standard deviation).\n\nThe general structure of the `tapply()` function is 3 arguments which are described below based on the code above:\n\n- the response variable on which we wish to apply the function, `diatoms$Diversity`;\n- the categorical variable which indicates the groups we wish to separately apply the function to, `diatoms$Zinc`;\n- the function we are using, `mean()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntapply(\n    X = diatoms$Diversity,\n    INDEX = diatoms$Zinc,\n    FUN = mean\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    BACK     HIGH      LOW      MED \n1.797500 1.277778 2.032500 1.717778 \n```\n\n\n:::\n\n```{.r .cell-code}\ntapply(\n    X = diatoms$Diversity,\n    INDEX = diatoms$Zinc,\n    FUN = sd\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     BACK      HIGH       LOW       MED \n0.4852613 0.4268717 0.4449960 0.5030104 \n```\n\n\n:::\n:::\n\n\n::: callout-tip\n**The `tidyverse` approach** -- Use the `group_by()` and `summarise()` functions to calculate the mean and standard deviation for each level of `Zinc`. The code is longer, but readable as you can see the sequence of operations.\n\n```r\ndiatoms %>%\n    group_by(Zinc) %>%\n    summarise(\n        mean = mean(Diversity),\n        sd = sd(Diversity)\n    )\n```\n:::\n\n\n#### Graphical summaries \n\nNumerical summaries are nice, but visual summaries are often more informative and are the **summary of choice** for publication. They can also help us to check the assumptions of the statistical test (although sometimes this is not possible until we have fitted the model). \n\nIn the case of ANOVA model we are interested in the distribution of the response variable for each level of the factor. The table below gives heuristic rules about which graphical summary to use based on the number of observations. \n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|observations |graphics      |command                           |\n|:------------|:-------------|:---------------------------------|\n|1-5          |plot raw data |`stripchart()` or `geom_jitter()` |\n|6-20         |boxplot       |`boxplot()` or `geom_boxplot()`   |\n|20 or more   |histogram     |`hist()` or `geom_histogram()`    |\n\n\n:::\n:::\n\n\nWe will show examples of both the histogram and boxplot for the diatom data. We recommend that you use `ggplot2` for your graphical summaries as it is more flexible and has a more consistent syntax than base R graphics. However, we will show both approaches here.\n\n##### Histogram As there are less than 10 observations per group the histogram may not be very informative. However, it may still be useful for checking the normality of the data. You may be able to see the limitations of the histogram for small sample sizes.\n\n::: callout-tip\n\nTo calculate the number of observations per group:\n\n```r\ntapply(\n    X = diatoms$Diversity,\n    INDEX = diatoms$Zinc,\n    FUN = length\n)\n```\n\n:::\n\n\n::: panel-tabset\n## ggplot2\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nggplot(diatoms, aes(x = Diversity)) +\n    geom_histogram(binwidth = .3) +\n    facet_wrap(~Zinc)\n```\n\n::: {.cell-output-display}\n![](Lab03-oneway-anova_files/figure-typst/unnamed-chunk-8-1.png)\n:::\n:::\n\n\n## base R (no loops)\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(2, 2))\nhist(\n    x = diatoms$Diversity[diatoms$Zinc == \"BACK\"],\n    main = \"Zinc: BACK\",\n    xlab = \"Diversity\"\n)\nhist(\n    x = diatoms$Diversity[diatoms$Zinc == \"HIGH\"],\n    main = \"Zinc: HIGH\",\n    xlab = \"Diversity\"\n)\nhist(\n    x = diatoms$Diversity[diatoms$Zinc == \"LOW\"],\n    main = \"Zinc: LOW\",\n    xlab = \"Diversity\"\n)\nhist(\n    x = diatoms$Diversity[diatoms$Zinc == \"MED\"],\n    main = \"Zinc: MED\",\n    xlab = \"Diversity\"\n)\n```\n\n::: {.cell-output-display}\n![](Lab03-oneway-anova_files/figure-typst/unnamed-chunk-9-1.png)\n:::\n:::\n\n\n## base R (loops)\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(2, 2))\nfor (i in levels(diatoms$Zinc)) {\n    hist(\n        x = diatoms$Diversity[diatoms$Zinc == i],\n        main = paste(\"Zinc:\", i),\n        xlab = \"Diversity\"\n    )\n}\n```\n\n::: {.cell-output-display}\n![](Lab03-oneway-anova_files/figure-typst/unnamed-chunk-10-1.png)\n:::\n:::\n\n\n:::\n\n\n##### Boxplot A more appropriate plot for this data is the boxplot. If we want to format the plot for publication we should make the plot clear by adding axis labels and a figure caption.\n\n::: panel-tabset\n## base R\n\n\n::: {.cell .caption-bottom}\n\n```{.r .cell-code}\nboxplot(\n    Diversity ~ Zinc,\n    data = diatoms,\n    ylab = \"Diversity\",\n    xlab = \"Zinc concentration\"\n)\n```\n\n::: {.cell-output-display}\n![Boxplot of diatom diversity by Zinc concentration.](Lab03-oneway-anova_files/figure-typst/fig-diatom1-1.png){#fig-diatom1}\n:::\n:::\n\n\n## ggplot2\n\n\n::: {.cell .caption-bottom}\n\n```{.r .cell-code}\nggplot(diatoms, aes(x = Zinc, y = Diversity)) +\n    geom_boxplot() +\n    ylab(\"Diversity\") +\n    theme_minimal(base_size = 12)\n```\n\n::: {.cell-output-display}\n![Boxplot of diatom diversity by Zinc concentration.](Lab03-oneway-anova_files/figure-typst/fig-diatom2-1.png){#fig-diatom2}\n:::\n:::\n\n\n:::\n\n::: {.question}\n### Exercise 1\n\nWhat can you say about the the different levels of Zinc from looking at the mean and standard deviation values when running the following?\n\n```r\ntapply(\n    X = diatoms$Diversity,\n    INDEX = diatoms$Zinc,\n    FUN = mean\n)\n\ntapply(\n    X = diatoms$Diversity,\n    INDEX = diatoms$Zinc,\n    FUN = sd\n)\n```\n:::\n\n::: {.content-visible when-profile=\"solution\"}\n::: {.ans}\n### Solution\n\nThe mean diatom diversity for the `HIGH` level of Zn concentration is much smaller than the other groupings indicating that there is something happening, more formal hypothesis testing is needed to determine whether this is significant.\n\nIn terms of the variance of each group these are quite uniform.\n\nNote: the assumption of constant variance (more on this next week) is likely to be met. For example, the ratio of the largest standard deviation to the smallest standard deviation (0.503/0.427) is less than 2.\n:::\n:::\n\n\n::: {.question}\n### Exercise 2\n\nCan you interpret and describe the boxplot above?\n:::\n\n::: {.content-visible when-profile=\"solution\"}\n::: {.ans}\n### Solution\n- Based on the median values the smallest diversity is associated with the `HIGH` level of Zn concentration.\n- The $Q_1$ and $Q_3$ (the \"box part\") for the `HIGH` level of Zn do not overlap with the others levels of Zn, but the boxes overlap with each other for the other levels. This is some initial evidence that it will be likely that all the different levels of Zn will have the same diversity with the exception of the `HIGH` level of Zn.\n:::\n:::\n\n\n### Model fitting \nA 1-way ANOVA involves one treatment (or grouping) factor.  The model we are fitting is:\n\n$$y_{i,j} =\\mu_i+\\epsilon_{i,j}$$\n\nwhere:\n\n1. $y_{i,j}$ is the response for observation *j* in treatment (or group) *i*,\n2. $\\mu_j$ is the mean of treatment (or group) *i*,\n3. $\\epsilon_{i,j}$ is the residual term which is an independent random variable that has a mean of 0, constant variance and is normally distributed.  This can be expressed shorthand as $\\sim N(0,\\sigma_2)$.  The residual MS estimates $\\sigma_2$.\n\nThe statistical hypotheses we are testing are:\n\n$$H_{0}: \\mu_1 = \\mu_2 = ... \\mu_t$$\n$$H_{1}: \\text{not all } \\mu_j \\text{ are equal}$$\n\nwhere $\\mu_j$ is the mean diatom diversity for each level of Zn concentration.\n\nThe code below fits the ANOVA model using the `aov()` function and saves the it to an object called `anova.diatoms`.  We can then extract the ANOVA table using the `summary` function.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova.diatoms <- aov(formula = Diversity ~ Zinc, data = diatoms)\nsummary(anova.diatoms)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value Pr(>F)  \nZinc         3  2.567  0.8555   3.939 0.0176 *\nResiduals   30  6.516  0.2172                 \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n### Assumptions and interpretation of results \nThe assumptions of the ANOVA model are:\n\n- The residuals are independent,\n- The residuals are normally distributed,\n- The residuals have constant variance.\n\nBased on the boxplots and histograms during data exploration, the assumptions of normality and equal variances are met. We will discuss assumptions again in greater detail next week when we start to look at residuals.\n\n**We can only interpret the results of the ANOVA model if the assumptions are met.** We can report the results the following way:\n\n> **Reporting**: The results indicate that there are significant differences between the levels of Zn concentration in terms of diatom diversity (*F* = 3.9, *df* = 3, 30, *P* = 0.02).\n\n### Post-hoc testing \nThe ANOVA test only tells us that there are differences between the groups, but it does not tell us which groups are different. We can use the `emmeans` package to perform post-hoc testing. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(emmeans)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWelcome to emmeans.\nCaution: You lose important information if you filter this package's results.\nSee '? untidy'\n```\n\n\n:::\n\n```{.r .cell-code}\nposthoc <- emmeans(anova.diatoms, \"Zinc\")\nposthoc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Zinc emmean    SE df lower.CL upper.CL\n BACK   1.80 0.165 30    1.461     2.13\n HIGH   1.28 0.155 30    0.961     1.60\n LOW    2.03 0.165 30    1.696     2.37\n MED    1.72 0.155 30    1.401     2.04\n\nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\n\nThe output of the `emmeans` function gives us the estimated marginal means for each level of `Zinc` and the 95% confidence intervals. The confidence intervals for the `HIGH` level of Zn concentration do not overlap with the other levels of Zn concentration, indicating that the `HIGH` level of Zn concentration is significantly different from the other levels.\n\n> **Reporting**: The post-hoc test indicates that the `HIGH` level of Zn concentration is significantly different from the other levels of Zn concentration. There are no other significant differences.\n\nWe can visualise the results of the post-hoc testing using the `plot` function, if you prefer a visual representation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(posthoc)\n```\n\n::: {.cell-output-display}\n![](Lab03-oneway-anova_files/figure-typst/unnamed-chunk-13-1.png)\n:::\n:::\n\n\n\n## Exercise 2 -- chicks\n\nAn experiment was designed to compare 15-day mean comb weights (g) of two lots of male chicks, one receiving sex hormone A (testosterone), the other C (dehydroandrosterone). While we usually analyse these data by using a (pooled) two-sample t-test, a single factor analysis of variance approach could be used (with two levels of the treatment factor). We will compare the results from both analyses.\n\nThe data is found in the *Comb* worksheet of the `chick_marigold.xlsx` file. Download it below:\n\n\nRead the data and save it as `comb`. It should look like below:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncomb\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 22 × 2\n   CombWt Hormone\n    <dbl> <chr>  \n 1     57 A      \n 2    120 A      \n 3    101 A      \n 4    137 A      \n 5    119 A      \n 6    117 A      \n 7    104 A      \n 8     73 A      \n 9     53 A      \n10     68 A      \n# ℹ 12 more rows\n```\n\n\n:::\n:::\n\n\n\n::: {.question}\n### Exercise 3\n\nPerform some checks to verify the two-sample t-test (or one-way ANOVA) is appropriate, i.e. investigate the shape of the distributions, and the standard deviations.\n:::\n\n\n::: {.content-visible when-profile=\"solution\"}\n::: {.ans}\n### Solution\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\ncombs <- read_excel(\"data/chick_marigold.xlsx\", sheet = \"Comb\")\nstr(combs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [22 × 2] (S3: tbl_df/tbl/data.frame)\n $ CombWt : num [1:22] 57 120 101 137 119 117 104 73 53 68 ...\n $ Hormone: chr [1:22] \"A\" \"A\" \"A\" \"A\" ...\n```\n\n\n:::\n\n```{.r .cell-code}\ncombs$Hormone <- as.factor(combs$Hormone)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\naggregate(CombWt ~ Hormone, summary, data = combs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Hormone CombWt.Min. CombWt.1st Qu. CombWt.Median CombWt.Mean CombWt.3rd Qu.\n1       A        53.0           70.5         104.0        97.0          118.5\n2       C        22.0           31.5          50.0        56.0           85.0\n  CombWt.Max.\n1       137.0\n2        96.0\n```\n\n\n:::\n\n```{.r .cell-code}\naggregate(CombWt ~ Hormone, sd, data = combs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Hormone   CombWt\n1       A 29.10670\n2       C 27.83523\n```\n\n\n:::\n\n```{.r .cell-code}\nboxplot(CombWt ~ Hormone, ylab = \"Comb weight (g)\", data = combs)\n```\n\n::: {.cell-output-display}\n![](Lab03-oneway-anova_files/figure-typst/unnamed-chunk-17-1.png)\n:::\n:::\n\n\nDescriptive statistics and boxplot would indicate that the two-sample t-test (or one-way ANOVA) would be appropriate as they appear to meet model assumptions of normality and equal variance.\n:::\n:::\n\n\n::: {.question}\n### Exercise 4\nIn R, perform a 2-sample t-test using the `t.test()` function, and use the `var.equal = TRUE` argument to ensure a standard 2-sample t-test is performed. Interpret the output.\n:::\n\n\n::: {.content-visible when-profile=\"solution\"}\n::: {.ans}\n### Solution\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(CombWt ~ Hormone, var.equal = TRUE, data = combs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  CombWt by Hormone\nt = 3.3764, df = 20, p-value = 0.003\nalternative hypothesis: true difference in means between group A and group C is not equal to 0\n95 percent confidence interval:\n 15.66997 66.33003\nsample estimates:\nmean in group A mean in group C \n             97              56 \n```\n\n\n:::\n:::\n\n\n- The t-test (*t* = 3.38, *df* = 20, *P* = 0.003) indicates that the means are significantly different, with the chicks given Hormone A (mean = 97 g) having a significantly higher weight than those given Hormone C (mean 56 g).\n- The estimated difference is 41 g, but the 95% CI for this estimate is between 15.7 and 66.3 g (A above C).\n- Since this 95% CI does not include zero, this also indicates the means differ significantly.\n:::\n:::\n\n\n::: {.question}\n### Exercise 5\n\nNext, perform a one-way ANOVA using the `aov` function, followed by `summary`, and interpret the results.\n:::\n\n::: {.content-visible when-profile=\"solution\"}\n::: {.ans}\n### Solution\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncombs.aov <- aov(CombWt ~ Hormone, data = combs)\nsummary(combs.aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value Pr(>F)   \nHormone      1   9245    9245    11.4  0.003 **\nResiduals   20  16220     811                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe results (*F* = 11.4, *df* = 1, 20, *P* = 0.003) indicates that the means are significantly different, with the chicks given Hormone A (mean = 97 g) having a significantly higher weight than those given Hormone C (mean 56 g).\n:::\n:::\n\n::: {.question}\n### Exercise 6\n\nCompare the t-test and ANOVA outputs. What do you notice about:\n\ni.\tthe degrees of freedom;\nii.\tthe P-value?\n:::\n\n\n\n::: {.content-visible when-profile=\"solution\"}\n::: {.ans}\n### Solution\n\ni. The *df* of *t* are 20, the denominator *df* for the ANOVA *F* statistic is also 20.\nii. They are the same (*P*-value = 0.03) for both tests.\n:::\n:::\n\n::: {.question}\n### Exercise 7\n\nWhen there are only two treatment groups, the observed *F* and *t* values are related by *F* = $t^2$. Demonstrate this for the observed values in this exercise.\n:::\n\n\n\n::: {.content-visible when-profile=\"solution\"}\n::: {.ans}\n### Solution\n\nWhen there are only two treatment groups, the observed *F*- and *t*-values are related by *F* = $t^2$.\n\nDemonstration: ($t_{obs}$)2 = $(3.38)^2$ = $F_{obs}$ of 11.4.\n:::\n:::\n\n## Exercise 3 -- lambs\n\n**Work on this exercise in your own time.**\n\nThe levels of immunoglobulin (Ig) in blood serum (g/100 ml) in 3 breeds of newborn lambs have been investigated. A total of 44 lambs were sampled, with approximately equal numbers per breed. The researcher wants to know whether or not there are significant differences in immunoglobulin levels between the breeds.\n\nThe data is found in `lambs.csv`. Download the data if you have not done so:\n\n\n**Read the data into R and save it as `lambs`.** Use the `read_csv()` function which should be available when you load the `tidyverse` package.\n\nIt should look like below:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlambs\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 44 × 2\n      Ig Breed\n   <dbl> <dbl>\n 1   1.1     1\n 2   2.2     1\n 3   1.7     1\n 4   1.4     1\n 5   1.6     1\n 6   2.3     1\n 7   1.4     1\n 8   1.9     1\n 9   0.8     1\n10   1.6     1\n# ℹ 34 more rows\n```\n\n\n:::\n:::\n\n\nBased on the demonstrator walkthrough, analyse the `lambs` dataset and test the hypothesis that:\n\n$$H_{0}: \\mu_1 = \\mu_2 = \\mu_3$$\n$$H_{1}: \\text{not all } \\mu_j \\text{ are equal}$$\n\nwhere $\\mu_j$ is the mean Ig level for breed $j$.\n\nRemember to:\n\n- [ ] State your null and alternate hypotheses.\n- [ ] Plot an appropriate summary graph for the data.\n- [ ] Demonstrate the model fit using the `aov()` function.\n- [ ] Test assumptions, by checking sd values, or by looking at your exploratory plots (checking residuals is not necessary at this point).\n- [ ] Report your test statistic, degrees of freedom and p-value.\n- [ ] Report the statistical conclusion by addressing the null hypothesis.\n- [ ] Explain the results within a biological context to the data.\n\n\n::: {.content-visible when-profile=\"solution\"}\n::: {.ans}\n### Answer\nFirst we read the data into R and the change the `Breed` variable to a `factor` after assesing the structure of the data.\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\nlambs <- readr::read_csv(\"data/lambs.csv\")\nstr(lambs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nspc_tbl_ [44 × 2] (S3: spec_tbl_df/tbl_df/tbl/data.frame)\n $ Ig   : num [1:44] 1.1 2.2 1.7 1.4 1.6 2.3 1.4 1.9 0.8 1.6 ...\n $ Breed: num [1:44] 1 1 1 1 1 1 1 1 1 1 ...\n - attr(*, \"spec\")=\n  .. cols(\n  ..   Ig = col_double(),\n  ..   Breed = col_double()\n  .. )\n - attr(*, \"problems\")=<externalptr> \n```\n\n\n:::\n\n```{.r .cell-code}\nlambs$Breed <- as.factor(lambs$Breed)\n```\n:::\n\n\nNow we do some exploratory data analysis. The main purpose here is to test the assumptions for performing the ANOVA. The `summary()` function selects the appropriate format to summarise for each variable in the data frame `lambs`: quartiles etc for `Ig`, a continuous variable, and a frequency distribution for levels of `Breed`, a factor. Note the unequal number of observations per breed.\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lambs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       Ig        Breed \n Min.   :0.800   1:16  \n 1st Qu.:1.600   2:13  \n Median :2.000   3:15  \n Mean   :1.998         \n 3rd Qu.:2.400         \n Max.   :3.000         \n```\n\n\n:::\n:::\n\n\nWe wish to see the summary statistics for each `Breed`.\n\n::: {.cell}\n\n```{.r .cell-code}\ntapply(\n    X = lambs$Ig,\n    INDEX = lambs$Breed,\n    FUN = mean\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       1        2        3 \n1.587500 2.230769 2.233333 \n```\n\n\n:::\n:::\n\n\nNote the median and mean for each `Breed` are similar which is an indicator of a symmetrical distribution. It is best to look at boxplots and below are these for each `Breed`. The equal length of the whiskers indicate that we can assume the data is normally distributed.\n\n::: {.cell}\n\n```{.r .cell-code}\nboxplot(Ig ~ Breed, ylab = \"Ig level (g/100 ml)\", data = lambs)\n```\n\n::: {.cell-output-display}\n![](Lab03-oneway-anova_files/figure-typst/unnamed-chunk-25-1.png)\n:::\n:::\n\n\nNow to assess whether the variances are equal.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvars <- tapply(\n    X = lambs$Ig,\n    INDEX = lambs$Breed,\n    FUN = sd\n)\nvars\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        1         2         3 \n0.3810074 0.3520999 0.4047339 \n```\n\n\n:::\n\n```{.r .cell-code}\n# ratio of largest to smallest\nmax(vars) / min(vars)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.149486\n```\n\n\n:::\n:::\n\n\n\nThe ratio of the largest (0.405) to smallest (0.352) is less than 2 so we can assume they are equal.\n\n\nNow we can perform the ANOVA. The statistical null and alternative hypotheses are:\n\n$$H_{0}: \\mu_1 = \\mu_2 = \\mu_3$$\n$$H_{1}: \\text{not all } \\mu_j \\text{ are equal}$$\n\nwhere $\\mu_j$ is the mean Ig level for breed $j$.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlambs.aov <- aov(Ig ~ Breed, data = lambs)\nsummary(lambs.aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value   Pr(>F)    \nBreed        2  4.231  2.1156   14.56 1.67e-05 ***\nResiduals   41  5.959  0.1453                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe *P*-value is below 0.05 so we reject the null hypothesis. Now explore which pair(s) of means are different.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(emmeans)\nemmeans(lambs.aov, \"Breed\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Breed emmean     SE df lower.CL upper.CL\n 1       1.59 0.0953 41     1.40     1.78\n 2       2.23 0.1060 41     2.02     2.44\n 3       2.23 0.0984 41     2.03     2.43\n\nConfidence level used: 0.95 \n```\n\n\n:::\n\n```{.r .cell-code}\nplot(emmeans(lambs.aov, \"Breed\"))\n```\n\n::: {.cell-output-display}\n![](Lab03-oneway-anova_files/figure-typst/unnamed-chunk-28-1.png)\n:::\n:::\n\n\n- Based on the the ANOVA table our conclusions are there are significant differences between the Ig means between the three breeds of lambs (*F* = 14.6; *df* = 2, 41; *P* < 0.0001).\n- The 95% CI of the the mean for Breed 1 does not overlap with the 95% CI of the other means.\n- Therefore, Breed 1 has substantially less immunoglobulin  (1.59 ± 0.10 g/100ml) than the other two: Breed 2: 2.23 ± 0.11 g/100ml, and Breed 3: 2.23 ± 0/.10 g/100ml (expressed as mean ± standard error).\n:::\n:::\n\n\n## Thanks!\n\nDid you know you can also knit to PDF? Check the documentation for [R Markdown](https://bookdown.org/yihui/rmarkdown/pdf-document.html) or [Quarto](https://quarto.org/docs/output-formats/pdf-basics.html) for more information.\n\n### Attribution\n\nThis lab was developed using resources that are available under a [Creative Commons Attribution 4.0 International license], made available on the [SOLES Open Educational Resources repository].\n\n  [Creative Commons Attribution 4.0 International license]: http://creativecommons.org/licenses/by/4.0/\n  [SOLES Open Educational Resources repository]: https://github.com/usyd-soles-edu/\n\n<button class=\"accordion-button\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapseOne\">\n**Click here for session information**\n</button><div id=\"collapseOne\" class=\"accordion-collapse collapse\"><div>\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.5.2 (2025-10-31)\nPlatform: aarch64-apple-darwin20\nRunning under: macOS Tahoe 26.3\n\nMatrix products: default\nBLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib \nLAPACK: /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1\n\nlocale:\n[1] en_AU.UTF-8/en_AU.UTF-8/en_AU.UTF-8/C/en_AU.UTF-8/en_AU.UTF-8\n\ntime zone: Australia/Sydney\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n[1] emmeans_2.0.0 ggplot2_4.0.2 readxl_1.4.5 \n\nloaded via a namespace (and not attached):\n [1] bit_4.6.0          rematch_2.0.0      gtable_0.3.6       jsonlite_2.0.0    \n [5] crayon_1.5.3       dplyr_1.2.0        compiler_4.5.2     tidyselect_1.2.1  \n [9] parallel_4.5.2     scales_1.4.0       yaml_2.3.12        fastmap_1.2.0     \n[13] lattice_0.22-7     coda_0.19-4.1      readr_2.2.0        R6_2.6.1          \n[17] labeling_0.4.3     generics_0.1.4     knitr_1.51         tibble_3.3.1      \n[21] tzdb_0.5.0         pillar_1.11.1      RColorBrewer_1.1-3 rlang_1.1.7       \n[25] utf8_1.2.6         xfun_0.56          S7_0.2.1           bit64_4.6.0-1     \n[29] otel_0.2.0         estimability_1.5.1 cli_3.6.5          withr_3.0.2       \n[33] magrittr_2.0.4     digest_0.6.39      grid_4.5.2         vroom_1.7.0       \n[37] xtable_1.8-4       mvtnorm_1.3-3      hms_1.1.4          lifecycle_1.0.5   \n[41] vctrs_0.7.1        evaluate_1.0.5     glue_1.8.0         farver_2.1.2      \n[45] cellranger_1.1.0   rmarkdown_2.30     tools_4.5.2        pkgconfig_2.0.3   \n[49] htmltools_0.5.9   \n```\n\n\n:::\n:::\n\n\n</div></div>",
    "supporting": [
      "Lab03-oneway-anova_files/figure-typst"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}