{
  "hash": "f5f40b6cb594d1596e6c987dd3e13b75",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Lab 08\n# revised-by: aca + Liana\nsubtitle: ENVX2001 Applied Statistical Methods\ndescription: The University of Sydney\ntoc: true\ntoc-depth: 3\nresources:\n  - data/Loyn_SLR.xlsx\n  - data/california_streamflow.xlsx\n---\n\n\n\n# Welcome to week 8!\n\nThis week's lab will give you some practice improving models by selecting the most useful predictors.  \n\nThis will prepare you for next week's content where we will use models for prediction. \n\n## Learning outcomes\n\nThis module links to the following unit learning outcomes: \n\n* LO3. demonstrate proficiency in the use or the statistical programming language R to apply an ANOVA and fit regression models to experimental data\n\n* LO5. interpret the output and understand conceptually how its derived of a regression, ANOVA and multivariate analysis that have been calculated by R\n\n* LO6. write statistical and modelling results as part of a scientific report\n\nIn this lab, we will learn how to:\n\n**1. Fit and interpret simple linear regression (SLR) models**\n**2. Fit and interpret multiple linear regression (MLR) models**\n**3. Assess model assumptions and apply transformations when needed**\n**4. Evaluate and compare model fit statistics**\n\n## Specific goals\n\n**By the end of this lab, you should be able to:**\n\n- [ ] Fit a simple linear regression model\n- [ ] Assess model assumptions and apply transformations when needed\n- [ ] Interpret model parameters and fit statistics\n- [ ] Fit a multiple linear regression model\n- [ ] Assess model assumptions, including collinearity between predictor variables\n- [ ] Determine the most suitable fit statistics for a multiple linear regression model\n- [ ] Write a conclusion on your findings\n\n**FIX EVERYTHING UP above**\n\n\n## Preparation\n\nPlease work on these exercises by creating your own Quarto file. You are welcome to write your responses up in the style of a report.\n\n### Packages\n\nThis lab uses `tidyverse`, `readxl`, `moments`, `psych`, and `performance`. Install any you are missing by running the following **in the console**:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(c(\"car\", \"tidyverse\", \"readxl\", \"moments\", \"psych\", \"performance\"))\n```\n:::\n\n\nIf a package is already installed, R will simply reinstall it — no harm done.\n\n\n# 1. Model quality - multiple vs adjusted *r*^2^ (10 mins)\n\nYou may have noticed how much we are focusing on the adjusted *r*^2^ value when interpreting our multiple linear regression models. This is because the multiple *r*^2^ value can be misleading when comparing models with different numbers of predictors.\n\nIn this exercise we will explore the difference between multiple *r*^2^ and adjusted *r*^2^ values and see how including a useless predictor can affect these values.\n\nFor this exercise we will use the same dataset as last week, which contains 43 years of annual precipitation measurements (in mm) taken at (originally) 6 sites in the Owens Valley in California. The response variable is the stream runoff volume measured at a site near Bishop, California (ML/year).\n\nData: *California_streamflow* spreadsheet\n\nImport the \"California_streamflow\" sheet into R.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load library if needed\nlibrary(readxl)\n# Load data\nstream_data <- read_xlsx(\"data/california_streamflow.xlsx\", \"streamflow\")\n```\n:::\n\n\nIn this exercise we will use the same data as last week. To jog your memory, the dataset contains 43 years of annual precipitation measurements (in mm) taken at (originally) 6 sites in the Owens Valley in California. Through model selection via partial F-test we have the final model as below:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit <- lm(runoff_volume ~ rock_creek + pine_creek, data = stream_data)\n```\n:::\n\n\nWe will now add a totally useless variable to the dataset. This variable is a random number generated from a normal distribution with mean 3 and standard deviation 2. We use the `set.seed()` function to make sure that everybody gets the same random values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(100) # to make sure everybody gets the same results\n\n# this generates the random number into the dataset\nstream_data$random_no <- rnorm(n = nrow(stream_data), mean = 3, sd = 2) \n```\n:::\n\n\nWe will see the impact of including a totally useless variable, such as this random variable, has on measures of model quality, *r*^2^ and adjusted *r*^2^ values.\n\n**Task: create two regression models:**\n\n1.  `runoff_volume ~ rock_creek + pine_creek`\n2.  `runoff_volume ~ rock_creek + pine_creek + random_no`\n\n::: question\n### Question 2\n\nCompare each in terms of their multiple *r*^2^ and adjusted *r*^2^ values. Which performance measure (multiple *r*^2^ or adj *r*^2^) would you use to identify which predictors to use in your model?\n:::\n\n:::: {.content-visible when-profile=\"solution\"}\n::: ans\n### Answer\n\nThere is only a small difference in the multiple *r*^2^ and adj *r*^2^ between the models, but one goes up and the other goes down. Since the random number is a totally useless value, this demonstrates that the adjusted *r*^2^ is the better performance measure to use.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_rand1 <- lm(runoff_volume ~ rock_creek + pine_creek,data = stream_data)\nsummary(mod_rand1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = runoff_volume ~ rock_creek + pine_creek, data = stream_data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.09832 -0.02350  0.01076  0.03291  0.08568 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  3.35762    0.10547  31.835  < 2e-16 ***\nrock_creek   0.44437    0.08925   4.979 1.26e-05 ***\npine_creek   0.21051    0.06861   3.068  0.00385 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.04937 on 40 degrees of freedom\nMultiple R-squared:  0.8749,\tAdjusted R-squared:  0.8686 \nF-statistic: 139.8 on 2 and 40 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nmod_rand2 <- lm(runoff_volume ~ rock_creek + pine_creek + random_no ,data = stream_data)\nsummary(mod_rand2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = runoff_volume ~ rock_creek + pine_creek + random_no, \n    data = stream_data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.10327 -0.02401  0.01220  0.03179  0.08056 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 3.359356   0.106303  31.602  < 2e-16 ***\nrock_creek  0.442795   0.089956   4.922  1.6e-05 ***\npine_creek  0.207234   0.069324   2.989  0.00482 ** \nrandom_no   0.003213   0.005077   0.633  0.53055    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.04974 on 39 degrees of freedom\nMultiple R-squared:  0.8761,\tAdjusted R-squared:  0.8666 \nF-statistic: 91.96 on 3 and 39 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n:::\n\n# 2. Variable selection for California_streamflow (~20 mins)\n\n#![Little Lakes Valley in the Eastern Sierra Nevada Mountains outside of Bishop, California. Source: Adobe Stock.](images/AdobeStock_668401555.jpeg)\n\n**You are a hydrologist tasked with analysing legacy data to investigate the relationship between precipitation at three sites (Lake Sabrina, Pine Creek, and Rock Creek) and stream runoff volume at a site near Bishop, California. The dataset contains 43 years of annual precipitation measurements (in mm) taken at (originally) 6 sites in the Owens Valley in California. You will focus on only 3 variables.**\n\n**focussing on the process rather than report writing, but can still write up conclusions as if it were for a report. **\n\nThe data is in the **california_streamflow.xlsx** file.\n\nVariables are as follows: \n\n* `lake_sabrina`: Precipitation recorded at Lake Sabrina (mm)\n* `pine_creek`: Precipitation recorded at Big Pine Creek (mm), \n* `rock_creek`: Precipitation recorded at Rock Creek (mm)\n* `runoff_volume`: Stream runoff volume measured at a site near Bishop, California (ML/year). This will be the response variable.\n\nNote the variables have already been log-transformed to increase normality of the residuals in the regressions.\n\nData source: \nHollett, K.J., Danskin, F.M., McCaffrey, W.F., and Walti, S.L., 1991. Geology and water resources of Owens Valley, California. U.S. Geological Survey Water-Supply Paper 2370-H.\n\n::: callout-tip\nLast week we concluded that Lake Sabrina is NOT a significant predictor of runoff volume at the site near Bishop, California. \n\nToday we will follow steps to see if we can produce a more parsimonious model.\n:::\n\n\n##\n::: {.question}\n### Exercise 1\n\n*(i)* Read in the data and investigate the relationship between each of your variables. Describe the relationships, supported by values (correlation coefficient) and plots.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\n\n# read in the data\nstream_data <- read_xlsx(\"data/california_streamflow.xlsx\", \"streamflow\")\n\nlibrary(tidyverse)\nglimpse(stream_data) # check the data\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 43\nColumns: 4\n$ lake_sabrina  <dbl> 1.958717, 2.087881, 1.981175, 2.054169, 2.102934, 2.1568…\n$ pine_creek    <dbl> 2.017618, 2.282781, 2.383471, 2.451719, 2.618086, 2.3532…\n$ rock_creek    <dbl> 2.275823, 2.450548, 2.491194, 2.585246, 2.706948, 2.3159…\n$ runoff_volume <dbl> 4.825412, 4.920867, 4.911735, 4.924242, 5.120841, 4.9210…\n```\n\n\n:::\n\n```{.r .cell-code}\n# Correlations and scatterplots all in one (+ histograms for each variable)\nlibrary(psych)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'psych'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:ggplot2':\n\n    %+%, alpha\n```\n\n\n:::\n\n```{.r .cell-code}\npairs.panels(stream_data)\n```\n\n::: {.cell-output-display}\n![](Lab08-model-selection_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# can also get the same results separately\ncor(stream_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              lake_sabrina pine_creek rock_creek runoff_volume\nlake_sabrina    1.00000000 0.07848517 0.09054996     0.1649284\npine_creek      0.07848517 1.00000000 0.88381452     0.8929251\nrock_creek      0.09054996 0.88381452 1.00000000     0.9194688\nrunoff_volume   0.16492838 0.89292511 0.91946880     1.0000000\n```\n\n\n:::\n\n```{.r .cell-code}\npairs(stream_data)\n```\n\n::: {.cell-output-display}\n![](Lab08-model-selection_files/figure-html/unnamed-chunk-5-2.png){width=672}\n:::\n:::\n\n\nWe see that runoff volume has a strong relationship with rock creek and pine creek, but not with lake sabrina. We also see that there is a strong relationship between rock creek and pine creek, which could be a sign of collinearity. We can confirm if this may be an issue with the model by observing the Variance inflation factor (VIF) later on when we check our model assumptions.\n\n*(ii)* Fit a multiple linear regression model to the data using all variables. Set  `runoff_volume` as the response variable and `lake_sabrina`, `pine_creek` and `rock_creek` as the predictor variables. This will be known as the 'full model'. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# fit the full model\n\nfull_model <- lm(runoff_volume ~ lake_sabrina + pine_creek + rock_creek, data = stream_data)\n```\n:::\n\n\n\n*(iii)* Check the assumptions of your model. Do you need to transform any variables? What does the Variance Inflation Factor (VIF) tell you about the collinearity between predictor variables?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(performance)\n\ncheck_model(full_model)\n```\n\n::: {.cell-output-display}\n![](Lab08-model-selection_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Lake Sabrina is doing something weird, so let's get VIF values too\n\ncar::vif(full_model) |> round(2) # numbers\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlake_sabrina   pine_creek   rock_creek \n        1.01         4.57         4.58 \n```\n\n\n:::\n:::\n\n\nLake Sabrina = 1.01\n\nPine_creek = 4.57\n\nRock_creek = 4.58 \n\nOur threshold is 5, so we are not too concerned about collinearity here, but it is something to keep in mind when interpreting the model parameters.\n\n*(iv)* Make a note of the model parameters and fit statistics for the full model. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(full_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = runoff_volume ~ lake_sabrina + pine_creek + rock_creek, \n    data = stream_data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.09885 -0.03331  0.01025  0.03359  0.09495 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   3.25716    0.12360  26.352  < 2e-16 ***\nlake_sabrina  0.05631    0.03756   1.499  0.14185    \npine_creek    0.21085    0.06756   3.121  0.00339 ** \nrock_creek    0.43838    0.08798   4.983 1.32e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.04861 on 39 degrees of freedom\nMultiple R-squared:  0.8817,\tAdjusted R-squared:  0.8726 \nF-statistic: 96.88 on 3 and 39 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nAs we saw last week, Lake Sabrina is not a significant predictor of runoff volume, but Pine Creek and Rock Creek are. The model has an adjusted R^2^ of 0.87, which means that 87% of the variation in runoff volume can be explained by the three predictor variables. \n\n*(v)* Remove `lake_sabrina` from the model and run the model again. This will be known as the 'reduced model'.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreduced_model <- lm(runoff_volume ~ pine_creek + rock_creek, data = stream_data)\n```\n:::\n\n\n\n*(vi)* Is the reduced model an improvement on the full model? How can you tell? What statistics would you look at to determine this?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(full_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = runoff_volume ~ lake_sabrina + pine_creek + rock_creek, \n    data = stream_data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.09885 -0.03331  0.01025  0.03359  0.09495 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   3.25716    0.12360  26.352  < 2e-16 ***\nlake_sabrina  0.05631    0.03756   1.499  0.14185    \npine_creek    0.21085    0.06756   3.121  0.00339 ** \nrock_creek    0.43838    0.08798   4.983 1.32e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.04861 on 39 degrees of freedom\nMultiple R-squared:  0.8817,\tAdjusted R-squared:  0.8726 \nF-statistic: 96.88 on 3 and 39 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(reduced_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = runoff_volume ~ pine_creek + rock_creek, data = stream_data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.09832 -0.02350  0.01076  0.03291  0.08568 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  3.35762    0.10547  31.835  < 2e-16 ***\npine_creek   0.21051    0.06861   3.068  0.00385 ** \nrock_creek   0.44437    0.08925   4.979 1.26e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.04937 on 40 degrees of freedom\nMultiple R-squared:  0.8749,\tAdjusted R-squared:  0.8686 \nF-statistic: 139.8 on 2 and 40 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nRemoving the `lake_sabrina` predictor from the model has slightly decreased the adjusted R^2^ value, but it has also removed a non-significant predictor from the model. This is an improvement in terms of parsimony, but we will need to use hypothesis testing to determine whether the reduced model is a *significant* improvement on the full model. We can do this using an F-test, which we will explore in the next exercise.\n\n:::\n\n\n##\n::: {.question}\n### Exercise 2 - model comparison\n\nWe can compare the models using the adjusted r^2^, but we will need to use hypothesis testing to decide whether the reduced model is a significant improvement or not. Let's explore this by using the F-test to compare the full and reduced models.\n\n*(i)* State the null and alternative hypotheses for the F-test between the full and reduced models.\n\nH0: No significant difference between full and reduced models\nH1: There is a significant difference between full and reduced models\n\n*(ii)* Perform the F-test using the `anova()` function to compare the full and reduced models. What is the p-value? Is the reduced model a significant improvement on the full model?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(full_model, reduced_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: runoff_volume ~ lake_sabrina + pine_creek + rock_creek\nModel 2: runoff_volume ~ pine_creek + rock_creek\n  Res.Df      RSS Df  Sum of Sq      F Pr(>F)\n1     39 0.092166                            \n2     40 0.097478 -1 -0.0053121 2.2478 0.1419\n```\n\n\n:::\n:::\n\n\nThe P-value is 0.1419, which is larger than 0.05, so we fail to reject the null hypothesis. This means that the reduced model is not a significant improvement on the full model, and we would opt for the reduced model as it is more parsimonious.\n\n:::\n\n\n\n##\n::: {.question}\n### Exercise 3 - stepwise regression\n\nInstead of removing one predictor at a time, there is a much quicker way involving the `step()` function in R. This function performs stepwise regression, which is an automated process of adding or removing predictors based on their significance in the model and the Akaike Information Criterion (AIC).\n\n*(i)* When using the AIC, how do we select the better model? \n\nSelect the model with the lowest AIC value. \n\nThe AIC is a measure of the relative quality of a statistical model for a given set of data. It takes into account the goodness of fit and the complexity of the model (number of predictors). A lower AIC value indicates a better model.\n\n*(ii)* Have a go at running the `step()` function on the full model. Which model does it select as the best model?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstep_model <- step(full_model, direction = \"backward\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStart:  AIC=-256.25\nrunoff_volume ~ lake_sabrina + pine_creek + rock_creek\n\n               Df Sum of Sq      RSS     AIC\n<none>                      0.092166 -256.25\n- lake_sabrina  1  0.005312 0.097478 -255.84\n- pine_creek    1  0.023015 0.115181 -248.66\n- rock_creek    1  0.058680 0.150845 -237.07\n```\n\n\n:::\n:::\n\n\nThe `step()` function selects the full model as the best model, which is inconsistent with our previous analysis using the F-test. \n\nThis is because the `step()` function uses the AIC to compare models, which is a different criterion than the F-test. The AIC takes into account both the goodness of fit and the complexity of the model, while the F-test only compares the goodness of fit between two models. \n\nIn this case, the AIC may be favoring the full model due to its better fit, even though it includes a non-significant predictor.\n\n*(iii)* One final check: what are the AIC values for the full and reduced models? Which model has the lowest AIC value?\n\nHINT: you can use the `AIC()` function to get the AIC values for each model. Insert the model name between the brackets. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nAIC(full_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -132.2222\n```\n\n\n:::\n\n```{.r .cell-code}\nAIC(reduced_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -131.8126\n```\n\n\n:::\n:::\n\n\n*(iv)* Based on our tests, which model do you think is the best model to use for predicting runoff volume at Bishop, California? Why have you chosen this model?\n\nThe reduced model is better. It is more parsimonious and does not include a non-significant predictor. \n\nThe F-test also indicates that the reduced model is not a significant improvement on the full model, so we would opt for the reduced model as it is simpler and just as good at explaining the variation in runoff volume.\n\nWe did see that the step function selected the full model as the best model based on AIC, but we would be cautious about this result given that it includes a non-significant predictor and the F-test did not support it as a significant improvement. \n\nIt was also helpful to calculate the AIC for our full and reduced models to confirm that the reduced model had a lower AIC value, which supports our choice of the reduced model.\n\nAutomated model selection methods are helpful when you have a large number of predictors, but our results demonstrate why we should not rely solely on these methods. We should also consider the significance of predictors and the overall fit of the model when making decisions about which model to use.\n\n:::\n\n\n\n\n\n\n::: callout-tip\nPlease work on this exercise by creating your own R Markdown file.\n:::\n\n\n::::\n\n## Exercise 2: Fish productivity.  '[DO FULL RUN OF MODEL PROCESS]\n\nFish communities were surveyed in lakes across a eutrophication gradient to investigate the relatioship between productivity and fish diversity.\n\nThe datasheet has thefollowing variables:\n\n-   `lake_id` Unique identifier for each lake\n-   `chla` Log-transformed Chlorophyll a\n-   `richness` Log-transformed species richness\n-   `evenness` Log-transformed Pielou’s evenness\\\n-   `abundance` Log-transformed abundance per unit effort (NPUE)\\\n-   `biomass` Log-transformed biomass per unit effort (BPUE)\n-   `productivity` Log-transformed productivity proxy\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Load library if necessary\nlibrary(tidyverse)\n\n#Read in data\nfish_data <- read_csv(\"data/fish_communities.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 39 Columns: 7\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (1): lake_id\ndbl (6): chla, richness, evenness, abundance, biomass, productivity\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\n#Have a look at the structure of the data\nstr(fish_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nspc_tbl_ [39 × 7] (S3: spec_tbl_df/tbl_df/tbl/data.frame)\n $ lake_id     : chr [1:39] \"FTH\" \"XLH\" \"HGH\" \"LH\" ...\n $ chla        : num [1:39] 4.61 4.53 3.84 3.71 2.43 ...\n $ richness    : num [1:39] 2.64 2.89 1.99 2.94 2.37 ...\n $ evenness    : num [1:39] -0.356 -0.67 -0.423 -0.405 -0.589 ...\n $ abundance   : num [1:39] 2.24 3.34 1.24 2.67 1.12 ...\n $ biomass     : num [1:39] 4.96 6.03 4.67 6.52 5.32 ...\n $ productivity: num [1:39] 3.47 4.47 2.71 4.47 3.24 ...\n - attr(*, \"spec\")=\n  .. cols(\n  ..   lake_id = col_character(),\n  ..   chla = col_double(),\n  ..   richness = col_double(),\n  ..   evenness = col_double(),\n  ..   abundance = col_double(),\n  ..   biomass = col_double(),\n  ..   productivity = col_double()\n  .. )\n - attr(*, \"problems\")=<externalptr> \n```\n\n\n:::\n:::\n\n\nExplore the data on your own before making any models. (*Hint:* remember that we are only interested in the numeric variables for our linear models)\n\n##\n::: {.question}\n### Exercise 2\n\n*(i)* Write out the statistical model for a multiple linear regression and define it in terms of the data (precipitation at each site vs runoff volume at Bishop). \n\nYou can write it out in words and/or in mathematical notation.\n\n*(ii)* State the hypotheses you will be testing for the relationship between each site and runoff volume.\n\n*(iii)* Read in the data and conduct some exploratory data analysis upon your variables. Describe the spread and central tendency of each, supported by values (summary statistics) and plots. \n\n*(iv)* Investigate the relationship between each of your variables. Describe the relationship, supported by values (correlation coefficient) and plots.\n\nHint: we are not only looking at relationship between response and predictors here, but also the relationships between predictor variables (signs of collinearity).\n\n*(v)* Fit a multiple linear regression model to the data, with `runoff_volume` as the response variable and `lake_sabrina`, `pine_creek` and `rock_creek` as the predictor variables.\n\n*(vi)* Check the assumptions of your model. Do you need to transform any variables?\n\nHint 1: you can use the the `check_model()` function from the `performance` package to check the assumptions of your model.\n\nHint 2: You may notice some collinearity occurring between predictors. This week you only need to acknowledge it and then you can move onto interpretation. Next week we will look at how to deal with collinearity in models.  \n\n*(vii)* Interpret the model parameters and fit statistics. Recall the key information we draw from the output; what do these statistics tell you about the relationship between precipitation at each site and runoff volume at Bishop, California?\n\n*(viii)* Write a concluding statement on your findings. \n\nHint: Consider the initial aim and hypothesis of the study and write it in a way that is easily understood by your client.\n\n:::\n\n\n\n\n::: question\n### Question 1\n\nAre there any obvious relationships between the response variable (productivity) and the other variables?\n:::\n\n:::: {.content-visible when-profile=\"solution\"}\n::: ans\n### Answer\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#correlation matrix\ncor(fish_data[,-1])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  chla   richness   evenness  abundance    biomass productivity\nchla         1.0000000  0.2388845  0.0872381  0.3449158  0.2809369    0.3406440\nrichness     0.2388845  1.0000000 -0.3295238  0.6585895  0.5704803    0.6611413\nevenness     0.0872381 -0.3295238  1.0000000 -0.5553243 -0.4396433   -0.5162017\nabundance    0.3449158  0.6585895 -0.5553243  1.0000000  0.8089680    0.9379798\nbiomass      0.2809369  0.5704803 -0.4396433  0.8089680  1.0000000    0.9571907\nproductivity 0.3406440  0.6611413 -0.5162017  0.9379798  0.9571907    1.0000000\n```\n\n\n:::\n\n```{.r .cell-code}\n#Plot the variables\n\npairs(fish_data[,-1])\n```\n\n::: {.cell-output-display}\n![](Lab08-model-selection_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\nProductivity has a strong relationship with biomass and abundance\n:::\n::::\n\n::: question\n### Question 2\n\nAre there any other patterns or potential issues you can see from the exploratory plots?\n:::\n\n:::: {.content-visible when-profile=\"solution\"}\n::: ans\n### Answer\n\nBiomass is also highly correlated with abundance, so collinearity might be an issue.\n:::\n::::\n\n## Take home exercise:\n\n## Review\n\n### Attribution\n",
    "supporting": [
      "Lab08-model-selection_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}