{
  "hash": "01e90625752004b7e16e0947c5ec4e7b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Lab 04\n# revised-by:\nsubtitle: ENVX2001 Applied Statistical Methods\ndescription: The University of Sydney\ntoc: true\ntoc-depth: 3\nresources:\n  - data/Data4.xlsx\n---\n\n# Welcome!\n\nThis week we will test ANOVA assumptions using residual diagnostics, perform post-hoc comparisons with Tukey's test, and practise back-transforming log-scale results using three datasets: diatoms, fish prolactin, and broiler chickens.\n\nYou will come across two types of tasks in this lab. **Worked Examples** have solutions you can expand and check straight away. **Exercises** do not --- solutions for these will be posted on Friday evening.\n\n## Learning outcomes\n\nIn this lab, we will learn how to:\n\n1. Test the assumptions of ANOVA using residual diagnostics.\n2. Use plotting and Tukey's tests to determine which pairs of groups are significantly different.\n3. Use R to perform the analyses.\n\n## Specific goals\n\nBy the end of this lab, you should be able to:\n\n- [ ] Fit a one-way ANOVA and extract standardised residuals\n- [ ] Assess normality using Q-Q plots, histograms, and the Shapiro-Wilk test\n- [ ] Assess equal variance using residual plots and Bartlett's test\n- [ ] Apply a log transformation when assumptions are violated\n- [ ] Perform post-hoc tests using `emmeans` and `TukeyHSD`\n- [ ] Back-transform log-scale estimates and interpret them as ratios\n\n## Preparation\n\nThis lab uses `readxl`, `emmeans`, and `performance`. Install any you are missing by running the following **in the console**:\n\n```r\ninstall.packages(c(\"readxl\", \"emmeans\", \"performance\"))\n```\n\n### Downloads\n\n| File | Used in | Download |\n|---|---|---|\n| `Data4.xlsx` | All sections | [Download](data/Data4.xlsx) |\n\nSave the file into a folder called `data` inside your project folder.\n\n\n# 1. Diatom diversity in streams (~20 min)\n\nHere we will test the assumptions using residual diagnostics and finding significant differences using plots and Tukey's test.  The data is found in the **Diatoms** worksheet.\n\n## Testing assumptions and finding differences\n\n##\n::: {.question}\n### Worked Example 1\n\nImport the Diatoms worksheet from `Data4.xlsx`, convert `Zinc` to a factor, and fit a one-way ANOVA model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# write your code here\n```\n:::\n\n:::\n\n::: {.callout-tip collapse=\"true\"}\n### Solution\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\ndiatoms<-read_excel(\"data/Data4.xlsx\",sheet=\"Diatoms\")\ndiatoms$Zinc<-as.factor(diatoms$Zinc)\nstr(diatoms)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [34 × 4] (S3: tbl_df/tbl/data.frame)\n $ Stream   : chr [1:34] \"Eagle\" \"Blue\" \"Blue\" \"Blue\" ...\n $ Zinc     : Factor w/ 4 levels \"BACK\",\"HIGH\",..: 1 1 1 1 1 1 1 1 3 3 ...\n $ Diversity: num [1:34] 2.27 1.7 2.05 1.98 2.2 1.53 0.76 1.89 1.4 2.18 ...\n $ Group    : num [1:34] 1 1 1 1 1 1 1 1 2 2 ...\n```\n\n\n:::\n\n```{.r .cell-code}\nanova.diatoms<-aov(Diversity~Zinc,data=diatoms)\nsummary(anova.diatoms)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value Pr(>F)  \nZinc         3  2.567  0.8555   3.939 0.0176 *\nResiduals   30  6.516  0.2172                 \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n:::\n\n##\n::: {.question}\n### Worked Example 2\n\nStatistical test of the assumption of constant variance.\n\nStatistics is made up of different tribes and some tribes use hypothesis testing to see if a dataset meets the assumptions of normality and constant variance.  One option is the Bartlett's test for constant variances.  The mechanics are not important but the function and syntax are shown below.  The hypotheses are:\n\n* $H_0:\\ \\sigma_{BACK}^2=\\sigma_{LOW}^2=\\sigma_{MED}^2=\\sigma_{HIGH}^2$\n\n* $H_1:\\ not\\ all\\ \\sigma_i^2\\ are\\ equal\\ \\left(i\\ =\\ BACK,\\ LOW,\\ MED,\\ HIGH\\right)$\n\nWe prefer to use numerical and graphical diagnostics, e.g. residuals plots, but this is more to show you other possibilities.  You can use this as a different line of evidence for testing assumptions if you wish.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#\n```\n:::\n\n:::\n\n::: {.column-margin}\nBartlett's test will not work if the data is non-normal and only use it if the data has one treatment factor with a completely randomised design.\n:::\n\n::: {.callout-tip collapse=\"true\"}\n### Solution\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbartlett.test(rstandard(anova.diatoms)~diatoms$Zinc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tBartlett test of homogeneity of variances\n\ndata:  rstandard(anova.diatoms) by diatoms$Zinc\nBartlett's K-squared = 0.25337, df = 3, p-value = 0.9685\n```\n\n\n:::\n:::\n\nBased on the P-value being > 0.05 we could state that we retain the null hypothesis and that the variances are equal.\n\n:::\n\n##\n::: {.question}\n### Worked Example 3\n\nIn Topic 3 we used the `emmeans` package to extract means for each group and their associated 95% CI.  The `emmeans` is useful to produce a plot showing the mean and 95% CI which is a nice way to present the results.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#\n```\n:::\n\n:::\n\n::: {.callout-tip collapse=\"true\"}\n### Solution\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(emmeans)\nemmeans(anova.diatoms, \"Zinc\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Zinc emmean    SE df lower.CL upper.CL\n BACK   1.80 0.165 30    1.461     2.13\n HIGH   1.28 0.155 30    0.961     1.60\n LOW    2.03 0.165 30    1.696     2.37\n MED    1.72 0.155 30    1.401     2.04\n\nConfidence level used: 0.95 \n```\n\n\n:::\n\n```{.r .cell-code}\nplot(emmeans(anova.diatoms, \"Zinc\"))\n```\n\n::: {.cell-output-display}\n![](Lab04-residuals-posthoc_files/figure-typst/unnamed-chunk-6-1.png)\n:::\n:::\n\n\nBased on the non-overlapping confidence intervals the only pairs of groups that are significantly different are `HIGH` and `LOW`.  However more correctly we are looking at whether the difference in means = 0 which is a slightly different question to seeing if the 95% CI around the mean overlaps.\n\n:::\n\n##\n::: {.question}\n### Worked Example 4\n\nAnother approach is to use a **Tukey's test** which we can extract using the `emmeans(model-goes-here, pairwise ~ your-treatment)` function from the `emmeans` package. Note there are many other post-hoc tests that have come and gone, but we will just focus on one of them.\n\nAnother way to present the results is to use the `plot()` function to show the confidence intervals and the comparisons among them.\n\n\n::: {.cell}\n\n:::\n\n:::\n\n::: {.callout-tip collapse=\"true\"}\n### Solution\n\n\n::: {.cell}\n\n```{.r .cell-code}\nemmeans(anova.diatoms,pairwise ~ Zinc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$emmeans\n Zinc emmean    SE df lower.CL upper.CL\n BACK   1.80 0.165 30    1.461     2.13\n HIGH   1.28 0.155 30    0.961     1.60\n LOW    2.03 0.165 30    1.696     2.37\n MED    1.72 0.155 30    1.401     2.04\n\nConfidence level used: 0.95 \n\n$contrasts\n contrast    estimate    SE df t.ratio p.value\n BACK - HIGH   0.5197 0.226 30   2.295  0.1219\n BACK - LOW   -0.2350 0.233 30  -1.008  0.7457\n BACK - MED    0.0797 0.226 30   0.352  0.9847\n HIGH - LOW   -0.7547 0.226 30  -3.333  0.0117\n HIGH - MED   -0.4400 0.220 30  -2.003  0.2096\n LOW - MED     0.3147 0.226 30   1.390  0.5153\n\nP value adjustment: tukey method for comparing a family of 4 estimates \n```\n\n\n:::\n:::\n\n\n You will note the following pairs are different:\n\n* 'LOW' and 'HIGH';\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(emmeans(anova.diatoms, \"Zinc\"), comparisons = TRUE)\n```\n\n::: {.cell-output-display}\n![](Lab04-residuals-posthoc_files/figure-typst/unnamed-chunk-9-1.png)\n:::\n:::\n\n\n\nIn the plot function above, we have specified `comparisons = TRUE`. The blue bars are confidence intervals for the EMMs, and the red arrows are for the comparisons among them. If an arrow from one mean overlaps an arrow from another group, the difference is not significant.\n:::\n\n##\n::: {.question}\n### Worked Example 5\n\nAn alternative base R function for Tukey tests is `TukeyHSD()`. It creates a set of confidence intervals on the differences between the means of the levels of a factor. Also plot the results from this function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#\n```\n:::\n\n:::\n\n::: {.column-margin}\nIf the confidence interval does not cross over 0, then that pair significantly differs from each other.\n:::\n\n::: {.callout-tip collapse=\"true\"}\n### Solution\n\n::: {.cell}\n\n```{.r .cell-code}\nTukeyHSD(anova.diatoms, conf.level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Tukey multiple comparisons of means\n    95% family-wise confidence level\n\nFit: aov(formula = Diversity ~ Zinc, data = diatoms)\n\n$Zinc\n                 diff        lwr        upr     p adj\nHIGH-BACK -0.51972222 -1.1355064 0.09606192 0.1218677\nLOW-BACK   0.23500000 -0.3986367 0.86863665 0.7457444\nMED-BACK  -0.07972222 -0.6955064 0.53606192 0.9847376\nLOW-HIGH   0.75472222  0.1389381 1.37050636 0.0116543\nMED-HIGH   0.44000000 -0.1573984 1.03739837 0.2095597\nMED-LOW   -0.31472222 -0.9305064 0.30106192 0.5153456\n```\n\n\n:::\n:::\n\n\nWe can also plot the results from `TukeyHSD()` to easily see where, if any, the differences are.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(TukeyHSD(anova.diatoms))\n```\n\n::: {.cell-output-display}\n![](Lab04-residuals-posthoc_files/figure-typst/unnamed-chunk-12-1.png)\n:::\n:::\n\n\n:::\n\n::: {.column-margin}\nNote a type I error rate is defined by your significance level (alpha). In other words, there is a chance that you will reject a null hypothesis that is actually true --- it is a false positive. When you perform only one test, the type I error rate equals your significance level, which is often 5%. However, as you conduct more and more tests, your chance of a false positive increases. If you perform enough tests, you are virtually guaranteed to get a false positive! The error rate for a family of tests is always higher than an individual test. Here in the `TukeyHSD` function you set the family-wise level of significance and the p-values for the individual tests are adjusted accordingly.\n:::\n\nBefore we move on, now is a good time to take a 5-minute break.\n\n\n# 2. Prolactin in stickleback fish (~30 min)\n\nIn this exercise will add a layer of complexity by considering a transformation.  If our data does not meet the assumptions we need to transform the data, possible transformations are the square root (weak) and log (high).  When we transform the data we need to be careful about how we interpret the results.\n\nConcentration of prolactin (units g/L) in the pituitary glands of nine-spined stickleback fish was assessed.  The fish were kept in either saltwater or freshwater prior to assay and were different batches were examined on three successive occasions.  Cysts tend to develop in fish when kept in saltwater and sometimes develop in freshwater populations.  The four different groups of fish were used in a preliminary experiment to examine the effects of cysts, whether induced by saltwater or normally present, on the prolactin production of the pituitary gland.\n\nThe four groups of fish were codes as follows, with 10 fish per group:\n\n* A = saltwater cysts, day 1;\n\n* B = freshwater, no cysts, day 2;\n\n* C = freshwater, no cysts, day 2;\n\n* D = freshwater, cysts, day 3.\n\nThe data is found in the **Prolactin** worksheet.\n\n## Exploratory analysis and assumptions\n\n##\n::: {.question}\n### Exercise 1\n\nImport the data into R, perform some exploratory data analysis to make **tentative** suggestions about differences between means and the likelihood of the data meeting the assumptions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#\n```\n:::\n\n:::\n\n::: {.content-visible when-profile=\"solution\"}\n::: {.ans}\n#### Solution\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\nfish<-read_excel(\"data/Data4.xlsx\",sheet=\"Prolactin\")\nfish$Treatment <- as.factor(fish$Treatment)\nstr(fish)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [40 × 2] (S3: tbl_df/tbl/data.frame)\n $ Treatment: Factor w/ 4 levels \"A\",\"B\",\"C\",\"D\": 1 1 1 1 1 1 1 1 1 1 ...\n $ Prolactin: num [1:40] 15.1 25.6 5.6 11.4 35.7 17.2 13.3 21.1 11.6 12.3 ...\n```\n\n\n:::\n:::\n\n\nFirst we create some boxplots for each group which show there are difference in median between each of the treatments.  There looks like some treatment effect.  In terms of the assumptions the spread of data in each treatment looks different based on the size of the boxes and length of the whiskers.  However for each group the upper and lower whisker lengths are similiar so the distribution is likely to be symmetrical (normal).\n\n::: {.cell}\n\n```{.r .cell-code}\nboxplot(Prolactin ~ Treatment, ylab = \"Prolactin concentration\", data = fish)\n```\n\n::: {.cell-output-display}\n![](Lab04-residuals-posthoc_files/figure-typst/unnamed-chunk-15-1.png)\n:::\n:::\n\n\nNext we generate summary statistics.  The variances are very different (ratio of largest: smallest > 4:1), therefore the assumption of constant variance is unlikley to be met.  The mean and median are similar for each treatment so the normality assumption could be met.\n\n::: {.cell}\n\n```{.r .cell-code}\naggregate(Prolactin ~ Treatment, mean, data = fish)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Treatment Prolactin\n1         A     16.89\n2         B     28.22\n3         C     52.27\n4         D     60.73\n```\n\n\n:::\n\n```{.r .cell-code}\naggregate(Prolactin ~ Treatment, median, data = fish)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Treatment Prolactin\n1         A     14.20\n2         B     27.35\n3         C     49.60\n4         D     56.20\n```\n\n\n:::\n\n```{.r .cell-code}\naggregate(Prolactin ~ Treatment, sd, data = fish)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Treatment Prolactin\n1         A  8.629723\n2         B 10.786700\n3         C 26.165628\n4         D 23.211302\n```\n\n\n:::\n:::\n\n\n:::\n:::\n\n##\n::: {.question}\n### Exercise 2\n\nFit an ANOVA model and test the assumption of normality using a QQ plot and a histogram - both based on standardised residuals.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#\n```\n:::\n\n:::\n\n::: {.content-visible when-profile=\"solution\"}\n::: {.ans}\n#### Solution\n\nThe QQ plot and the histogram indicate the data is normally distributed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npro.aov <- aov(Prolactin ~ Treatment, data = fish)\nqqnorm(rstandard(pro.aov))\nabline(0,1)\n```\n\n::: {.cell-output-display}\n![](Lab04-residuals-posthoc_files/figure-typst/unnamed-chunk-18-1.png)\n:::\n\n```{.r .cell-code}\nhist(rstandard(pro.aov))\n```\n\n::: {.cell-output-display}\n![](Lab04-residuals-posthoc_files/figure-typst/unnamed-chunk-18-2.png)\n:::\n:::\n\n\n:::\n:::\n\n##\n::: {.question}\n### Exercise 3\n\nAssess the assumption of constant variance by:\n\n* examine the plot of the standardised residuals against fitted values;\n\n::: {.cell}\n\n```{.r .cell-code}\n#\n```\n:::\n\n\n* From the performance package, use `check_model()` to assess the assumptions of the model.  This function will check the assumptions of normality and constant variance;\n\n::: {.cell}\n\n```{.r .cell-code}\n#\n```\n:::\n\n\n* using the Bartlett's test;\n\n::: {.cell}\n\n```{.r .cell-code}\n#\n```\n:::\n\n\n* using `check_homogeneity()` from the `performance` package;\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#\n```\n:::\n\n\n* calculating the ratio of the largest SD:smallest SD to see if it is below 2:1;\n\n::: {.cell}\n\n```{.r .cell-code}\n#\n```\n:::\n\n:::\n\n::: {.column-margin}\nNote there are many tests: `method = c(\"bartlett\", \"fligner\", \"levene\", \"auto\")`\n:::\n\n::: {.content-visible when-profile=\"solution\"}\n::: {.ans}\n#### Solution\n\nThis plots shows an increasing spread (fanning) of the residuals as the fitted values increase.  The assumption of constant variance is not tenable.\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(pro.aov, which = 1)\n```\n\n::: {.cell-output-display}\n![](Lab04-residuals-posthoc_files/figure-typst/unnamed-chunk-24-1.png)\n:::\n:::\n\n\n* From the performance package, use `check_model()` to assess the assumptions of the model.  This function will check the assumptions of normality and constant variance;\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(performance)\ncheck_model(pro.aov)\n```\n\n::: {.cell-output-display}\n![](Lab04-residuals-posthoc_files/figure-typst/unnamed-chunk-25-1.png)\n:::\n:::\n\n\n* using the Bartlett's test;\n\nThe P-value is less than 0.05 so we reject the null hypothesis.  The variances are not equal.\n\n::: {.cell}\n\n```{.r .cell-code}\nbartlett.test(rstandard(pro.aov) ~ fish$Treatment)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tBartlett test of homogeneity of variances\n\ndata:  rstandard(pro.aov) by fish$Treatment\nBartlett's K-squared = 13.651, df = 3, p-value = 0.003421\n```\n\n\n:::\n:::\n\n\n* using `check_homogeneity()` from the `performance` package;\nNote there are many tests: `method = c(\"bartlett\", \"fligner\", \"levene\", \"auto\")`\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_homogeneity(pro.aov, method = \"bartlett\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWarning: Variances differ between groups (Bartlett Test, p = 0.003).\n```\n\n\n:::\n:::\n\n\n\n* calculating the ratio of the largest SD:smallest SD to see if it is below 2:1;\n\nThe ratio is 3.03 so further evidence of the variances being unequal.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nout<-tapply(fish$Prolactin,fish$Treatment,sd)\nout\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        A         B         C         D \n 8.629723 10.786700 26.165628 23.211302 \n```\n\n\n:::\n\n```{.r .cell-code}\nout[3]/out[1]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       C \n3.032036 \n```\n\n\n:::\n:::\n\n\n:::\n:::\n\n##\n::: {.question}\n### Exercise 4\n\nThe data does not meet the assumptions so log transform (`log` function) the response and repeat the normality and constant variance checks to test the assumptions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#\n```\n:::\n\n:::\n\n::: {.column-margin}\nIn R you can transform data in the model formula or you could create a new column in your data frame, for example `fish$logProlactin <- log(fish$Prolactin)`.\n:::\n\n::: {.content-visible when-profile=\"solution\"}\n::: {.ans}\n#### Solution\nThe log transformation has not changed the distribution dramatically, it is still normally distributed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npro.aov <- aov(log(Prolactin) ~ Treatment, data = fish)\nqqnorm(rstandard(pro.aov))\nabline(0,1)\n```\n\n::: {.cell-output-display}\n![](Lab04-residuals-posthoc_files/figure-typst/unnamed-chunk-30-1.png)\n:::\n\n```{.r .cell-code}\nhist(rstandard(pro.aov))\n```\n\n::: {.cell-output-display}\n![](Lab04-residuals-posthoc_files/figure-typst/unnamed-chunk-30-2.png)\n:::\n:::\n\n\nAll of the ways to assess the constant variance assumption indicate the variances are equal after the log transformation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(pro.aov, which = 1)\n```\n\n::: {.cell-output-display}\n![](Lab04-residuals-posthoc_files/figure-typst/unnamed-chunk-31-1.png)\n:::\n\n```{.r .cell-code}\nbartlett.test(rstandard(pro.aov) ~ fish$Treatment)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tBartlett test of homogeneity of variances\n\ndata:  rstandard(pro.aov) by fish$Treatment\nBartlett's K-squared = 1.5541, df = 3, p-value = 0.6698\n```\n\n\n:::\n\n```{.r .cell-code}\nout<-tapply(log(fish$Prolactin),fish$Treatment,sd)\nout\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        A         B         C         D \n0.5097462 0.3994729 0.5382265 0.3785816 \n```\n\n\n:::\n\n```{.r .cell-code}\nout[3]/out[4]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       C \n1.421692 \n```\n\n\n:::\n:::\n\n\n:::\n:::\n\n## Post-hoc tests and back-transformation\n\n##\n::: {.question}\n### Exercise 5\n\nIf the assumptions are met and there is significant F-test perform Tukey tests and identify which pairs are significantly different.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#\n```\n:::\n\n:::\n\n::: {.content-visible when-profile=\"solution\"}\n::: {.ans}\n#### Solution\nThe ANOVA table indicates we reject the null hypothesis.\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(pro.aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value   Pr(>F)    \nTreatment    3 10.717   3.572   16.76 5.57e-07 ***\nResiduals   36  7.672   0.213                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe results of the Tukey test are show below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nemmeans(pro.aov,pairwise ~ Treatment)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$emmeans\n Treatment emmean    SE df lower.CL upper.CL\n A           2.71 0.146 36     2.42     3.01\n B           3.27 0.146 36     2.97     3.57\n C           3.83 0.146 36     3.54     4.13\n D           4.04 0.146 36     3.75     4.34\n\nResults are given on the log (not the response) scale. \nConfidence level used: 0.95 \n\n$contrasts\n contrast estimate    SE df t.ratio p.value\n A - B      -0.558 0.206 36  -2.701  0.0491\n A - C      -1.120 0.206 36  -5.425  <.0001\n A - D      -1.329 0.206 36  -6.438  <.0001\n B - C      -0.562 0.206 36  -2.724  0.0466\n B - D      -0.771 0.206 36  -3.737  0.0035\n C - D      -0.209 0.206 36  -1.013  0.7431\n\nResults are given on the log (not the response) scale. \nP value adjustment: tukey method for comparing a family of 4 estimates \n```\n\n\n:::\n:::\n\n\nor:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTukeyHSD(pro.aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Tukey multiple comparisons of means\n    95% family-wise confidence level\n\nFit: aov(formula = log(Prolactin) ~ Treatment, data = fish)\n\n$Treatment\n         diff          lwr       upr     p adj\nB-A 0.5576099  0.001593344 1.1136265 0.0491223\nC-A 1.1199871  0.563970549 1.6760037 0.0000235\nD-A 1.3290431  0.773026472 1.8850596 0.0000011\nC-B 0.5623772  0.006360617 1.1183938 0.0465770\nD-B 0.7714331  0.215416540 1.3274497 0.0034562\nD-C 0.2090559 -0.346960665 0.7650725 0.7431453\n```\n\n\n:::\n:::\n\n\n:::\n:::\n\n##\n::: {.question}\n### Exercise 6\n\nOne issue is that we have performed our hypothesis testing on the log scale.  This means there are some steps to be made if we wish to interpret the data on the original scale; e.g. provide a 95% CI on the original scale.  We will step through these.\n\nSuppose the biologist was primarily interested in comparing the prolactin concentrations for A (saltwater cysts, day 1) vs B (freshwater, no cysts, day 1).\n\n* Find the means and CI from the output of the `TukeyHSD()` or `emmeans()` function.\n* The CI and mean are on the log scale, so back-transform the difference in the means (`exp()` function), the lower and upper end-point 95% CI.  Note that the upper and lower tail are not of equal length on the original scale.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#\n```\n:::\n\n\nNow we have an estimate of the difference in the means on the original scale.  It actually corresponds to a ratio on the original scale.  The reason is based on log laws, we can write the difference between 2 logged numbers (A and B) as a log of their ratio (A/B);\n\n$\\log\\left(A\\right)-\\log\\left(B\\right)=\\log\\left(\\frac{A}{B}\\right)$.\n\nIf we back-transform the log of their ratio we get the ratio on the original scale;\n\n$e^{\\log\\left(\\frac{A}{B}\\right)}=\\frac{A}{B}$.\n\nSo the back-transformed difference between the pairs of the means is a ratio.\n\nNote: if we were to back-transform the group means on the log scale we would get the geometric mean on the original scale.\n\nProvide a biological interpretation for this estimate and confidence interval.  Use the CI to decided if there is a significant difference between Treatment A and Treatment B.\n:::\n\n::: {.content-visible when-profile=\"solution\"}\n::: {.ans}\n#### Solution\n\n::: {.cell}\n\n```{.r .cell-code}\ntukey.results <- TukeyHSD(pro.aov)\nB.A.diff <- tukey.results$Treatment[1,1]\nB.A.diff\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5576099\n```\n\n\n:::\n:::\n\n\n\nBack-transform the difference in the means and the lower and upper end-point 95% CI.\n\n::: {.cell}\n\n```{.r .cell-code}\nexp(B.A.diff) # difference between means\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.746493\n```\n\n\n:::\n\n```{.r .cell-code}\nexp(1.1136265) # upper CI\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.045382\n```\n\n\n:::\n\n```{.r .cell-code}\nexp(0.001593344) # lower CI\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.001595\n```\n\n\n:::\n:::\n\n\nSince we interpret the back-transformed difference as a ratio, we conclude that the mean prolactin concentration in Treatment B is estimated as 1.75 that in Treatment A.  However, the 95% CI for this ratio extends from 1.002 to 3.045.  Since the 95% CI for the ratio >1 (just), this also demonstrates the mean prolactin concentrations for Treatments A and B do differ significantly (P < 0.05).  Note if the ratio (on the original prolactin scale) is 1, then, this implies meanB / meanA = 1, i.e. $mean_{B} = mean_{A}$.\n\n:::\n:::\n\nBefore we move on, now is a good time to take a 5-minute break.\n\n\n# 3. Broiler chickens (~25 min)\n\nThis exercise is an analysis of a set of growth data. It is an open question for you to gain more practice.\n\nThe effect of weight gain in dressed broiler chickens was determined after five generations of selection. Group A was bred by using only the heaviest 10% in each generation; groups B and C were bred using respectively the heaviest 30% and 50%; group D was obtained by crossing groups A and C of the previous generation. The dressed weights (kg) of 25 birds from each group have been recorded.\n\nThe data is found in the **Broilers** worksheet.\n\n## Analysis\n\n##\n::: {.question}\n### Exercise 7\n\nWrite down the null and alternate hypothesis. What is the treatment factor, and how many levels does it have? What are the sample sizes for each group ($n_i$)?\n:::\n\n::: {.content-visible when-profile=\"solution\"}\n::: {.ans}\n#### Solution\n\n$$H_0:\\ \\mu_A=\\mu_B=\\mu_C=\\mu_D$$\n\n$$H_1:\\ not\\ all\\ \\mu_i\\ are\\ equal$$\n\nwhere i (i = A, B, C, D) is the population mean weight gain for broilers in selection group i.\nThe treatment factor is the selection group, with t = 4 levels in this factor.  There are r = 25 chicks in each selection group (equal replication).\n\n:::\n:::\n\n##\n::: {.question}\n### Exercise 8\n\nImport the data into R, and then obtain some numerical and graphical summaries of the data, by each group. How would you interpret these data? From these summaries, is the assumption of homogeneity of variances met?  What about normality?  Try a formal Bartlett's test using the `bartlett.test` or `check_homogeneity()` function. Use residual diagnostics to assess the assumptions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#\n```\n:::\n\n:::\n\n::: {.content-visible when-profile=\"solution\"}\n::: {.ans}\n#### Solution\nThe summary statistics by group indicate the data is likely to be normally distributed (mean ~ median) and the variances are equal.  This confirmed by boxplots for each group.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\nbroilers<-read_excel(\"data/Data4.xlsx\",sheet=\"Broilers\")\nstr(broilers)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [100 × 2] (S3: tbl_df/tbl/data.frame)\n $ WtGain: num [1:100] 1.67 1.64 1.6 1.66 1.4 1.48 1.7 1.5 1.67 1.52 ...\n $ Group : chr [1:100] \"A\" \"A\" \"A\" \"A\" ...\n```\n\n\n:::\n\n```{.r .cell-code}\nbroilers$Group<-as.factor(broilers$Group)\naggregate(WtGain ~ Group, summary, data = broilers)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Group WtGain.Min. WtGain.1st Qu. WtGain.Median WtGain.Mean WtGain.3rd Qu.\n1     A      1.4000         1.5000        1.5500      1.5644         1.6400\n2     B      1.3200         1.4500        1.4800      1.5160         1.5800\n3     C      1.3000         1.4100        1.5000      1.4860         1.5500\n4     D      1.3500         1.4700        1.5700      1.5424         1.6000\n  WtGain.Max.\n1      1.7000\n2      1.8100\n3      1.6900\n4      1.7600\n```\n\n\n:::\n\n```{.r .cell-code}\nboxplot(WtGain ~ Group, ylab = \"Weight gain (kg)\", data = broilers)\n```\n\n::: {.cell-output-display}\n![](Lab04-residuals-posthoc_files/figure-typst/unnamed-chunk-40-1.png)\n:::\n\n```{.r .cell-code}\naggregate(WtGain ~ Group, sd, data = broilers)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Group     WtGain\n1     A 0.09046546\n2     B 0.10984838\n3     C 0.09673848\n4     D 0.09925892\n```\n\n\n:::\n:::\n\n\n\nThe residual diagnostics indicate the data is normally distributed and variances are equal.\n\n::: {.cell}\n\n```{.r .cell-code}\nbroilers.aov <- aov(WtGain ~ Group, data = broilers)\nqqnorm(rstandard(broilers.aov))\nabline(0,1)\n```\n\n::: {.cell-output-display}\n![](Lab04-residuals-posthoc_files/figure-typst/unnamed-chunk-41-1.png)\n:::\n\n```{.r .cell-code}\nhist(rstandard(broilers.aov))\n```\n\n::: {.cell-output-display}\n![](Lab04-residuals-posthoc_files/figure-typst/unnamed-chunk-41-2.png)\n:::\n\n```{.r .cell-code}\nplot(broilers.aov, which = 1)\n```\n\n::: {.cell-output-display}\n![](Lab04-residuals-posthoc_files/figure-typst/unnamed-chunk-41-3.png)\n:::\n:::\n\n\nThe Bartlett's test indicates the variance are equal.\n\n::: {.cell}\n\n```{.r .cell-code}\nbartlett.test(rstandard(broilers.aov) ~ broilers$Group)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tBartlett test of homogeneity of variances\n\ndata:  rstandard(broilers.aov) by broilers$Group\nBartlett's K-squared = 0.93192, df = 3, p-value = 0.8177\n```\n\n\n:::\n:::\n\n\nor\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_homogeneity(broilers.aov, method = \"bartlett\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOK: There is not clear evidence for different variances across groups (Bartlett Test, p = 0.818).\n```\n\n\n:::\n:::\n\n\n:::\n:::\n\n##\n::: {.question}\n### Exercise 9\n\nNote that the results of the analysis can only be used when the assumptions of the analysis have been met. If you believe that the assumptions are met, then what would your conclusions of the analysis of variance be? You should use the `summary()` function applied to your `aov()` object to obtain the ANOVA table.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#\n```\n:::\n\n\nWithout any formal analysis, consider the result of the group means in relation to the group treatment - i.e. type of selection. Would this pattern be expected?  If appropriate perform a Tukey test.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#\n```\n:::\n\n:::\n\n::: {.content-visible when-profile=\"solution\"}\n::: {.ans}\n#### Solution\nThe ANOVA table indicates we reject the null hypothesis.\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(broilers.aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq  Mean Sq F value Pr(>F)  \nGroup        3 0.0859 0.028648   2.904 0.0387 *\nResiduals   96 0.9471 0.009865                 \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nLooking at the sample means, this pattern might be expected from the breeding experiment: weight gain appears to be related to the degree of weight selection in each generation.  For Group 1 (A), the heaviest 10% of birds were used, as this breed did result in the highest wait gain, with lesser increases for Groups 2 (B) and 3 (C).  Similarly, since Group 4 (D) was obtained by crossing Groups 1 and 3, then an intermediate result might be expected -- and this is what occurred here.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(emmeans(broilers.aov,  ~ Group), comparisons = TRUE)\n```\n\n::: {.cell-output-display}\n![](Lab04-residuals-posthoc_files/figure-typst/unnamed-chunk-47-1.png)\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nemmeans(broilers.aov, pairwise ~ Group)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$emmeans\n Group emmean     SE df lower.CL upper.CL\n A       1.56 0.0199 96     1.52     1.60\n B       1.52 0.0199 96     1.48     1.56\n C       1.49 0.0199 96     1.45     1.53\n D       1.54 0.0199 96     1.50     1.58\n\nConfidence level used: 0.95 \n\n$contrasts\n contrast estimate     SE df t.ratio p.value\n A - B      0.0484 0.0281 96   1.723  0.3176\n A - C      0.0784 0.0281 96   2.791  0.0317\n A - D      0.0220 0.0281 96   0.783  0.8619\n B - C      0.0300 0.0281 96   1.068  0.7098\n B - D     -0.0264 0.0281 96  -0.940  0.7836\n C - D     -0.0564 0.0281 96  -2.008  0.1924\n\nP value adjustment: tukey method for comparing a family of 4 estimates \n```\n\n\n:::\n:::\n\n\nor\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTukeyHSD(broilers.aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Tukey multiple comparisons of means\n    95% family-wise confidence level\n\nFit: aov(formula = WtGain ~ Group, data = broilers)\n\n$Group\n       diff         lwr          upr     p adj\nB-A -0.0484 -0.12185261  0.025052614 0.3175960\nC-A -0.0784 -0.15185261 -0.004947386 0.0316837\nD-A -0.0220 -0.09545261  0.051452614 0.8619484\nC-B -0.0300 -0.10345261  0.043452614 0.7098306\nD-B  0.0264 -0.04705261  0.099852614 0.7835523\nD-C  0.0564 -0.01705261  0.129852614 0.1923814\n```\n\n\n:::\n:::\n\n\n:::\n:::\n\n\n# Conclusion\n\n## Closing thoughts\n\nWe tested ANOVA assumptions using residual diagnostics, applied transformations when assumptions were violated, and used post-hoc tests to identify which groups differ. These tools will be used throughout the rest of the course as we fit more complex models.\n\n### Attribution\n\nThis lab was developed using resources that are available under a\n[Creative Commons Attribution 4.0 International license], made available\non the [SOLES Open Educational Resources repository].\n\n  [Creative Commons Attribution 4.0 International license]: http://creativecommons.org/licenses/by/4.0/\n  [SOLES Open Educational Resources repository]: https://github.com/usyd-soles-edu/\n",
    "supporting": [
      "Lab04-residuals-posthoc_files/figure-typst"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}