{
  "hash": "ef9b06d177f083444f7f749cca242797",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"ENVX2001 Lab 07 - Regression modelling\"\n# revised-by: aca\nsubtitle: ENVX2001 Applied Statistical Methods\ndescription: The University of Sydney\ntoc: true\ntoc-depth: 3\nresources:\n  - data/Loyn_SLR.csv\n  - data/california_streamflow.xlsx\n---\n\n\n\n# Welcome to week 7!\n\nThis week's lab will give you some practice fitting and interpreting Simple Linear Regression (SLR) and Multiple Linear Regression (MLR) models. \n\nThis will prepare you for next week's content where we will seek to improve our models, and then in week 9 we will use improved models for prediction.\n\n## Learning outcomes\n\nThis module links to the following unit learning outcomes: \n\n* LO3. demonstrate proficiency in the use or the statistical programming language R to apply an ANOVA and fit regression models to experimental data\n\n* LO5. interpret the output and understand conceptually how its derived of a regression, ANOVA and multivariate analysis that have been calculated by R\n\n* LO6. write statistical and modelling results as part of a scientific report\n\n## Specific goals\n\nBy the end of this lab, students should be able to:\n\n- [ ] Fit a simple linear regression model\n- [ ] Assess model assumptions and apply transformations when needed\n- [ ] Interpret model parameters and fit statistics\n- [ ] Fit a multiple linear regression model (**different structure**)\n- [ ] Assess model assumptions, recalling key differences between MLR and SLR (**collinearity**)\n- [ ] Determine the most suitable fit statistics for assessing the fit of a MLR model(**r-sq vs adj**)\n- [ ] Write a conclusion on your findings\n\n\n::: callout-tip\nPlease work on this exercise by creating your own R Markdown file.\n:::\n\n## Preparation\n\n- [ ] Install or update the `performance` package\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#install.packages(\"performance\")\nlibrary(performance)\n```\n:::\n\n\nThis package is really good for checking your models. \nFor this lab, we will focus on the `check_model()` function, which gives us nice pretty diagnostic plots for models:\n\n::: panel-tabset\n\n\n::: {.cell}\n\n```{.r .cell-code}\niris_lm<- lm(iris$Petal.Length~iris$Sepal.Length)\n```\n:::\n\n\n### `plot()`\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow=c(2,2))\nplot(iris_lm)\n```\n\n::: {.cell-output-display}\n![](Lab07-regression-modelling_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n\n```{.r .cell-code}\npar(mfrow=c(1,1))\n```\n:::\n\n\n### `check_model()` from `performance`\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(performance)\ncheck_model(iris_lm)\n```\n\n::: {.cell-output-display}\n![](Lab07-regression-modelling_files/figure-html/warning - false-1.png){width=672}\n:::\n:::\n\n\n:::\n\n### Downloads\n\n| File | Used in | Download |\n|---|---|---|\n| `Loyn_SLR.xlsx` | Exercise 1 | [Download](data/Loyn_SLR.xlsx) |\n| `california_streamflow.xlsx` | Exercise 2 | [Download](data/california_streamflow.xlsx) |\n\n\n# Simple linear regression model fitting and interpretation (~ 30 minutes)\n\nHabitat fragmentation resulting from agriculture and urbanisation has increased the rate of wildlife population decline in Australia. You are a consultant and have been asked to investigate the influence of forest fragment size upon bird abundance. You have been provided with some data containing data on bird abundance and patch area from 56 different forest patches in Southeastern Victoria, Australia, and you want to know if there is a relationship between these two variables.\n\nThe data is in the **Loyn_SLR.xlsx** file.\n\nVariables are as follows: \n\n- ABUND: Bird abundance within each forest patch (number of birds)\n- AREA: Area of each forest patch (ha)\n\nOriginal data source: Loyn, R. H. (1987). Effects of patch area and habitat on bird abundances, species numbers, and tree health in fragmented Victorian forests. In *Nature Conservation: the role of remnants of native vegetation* eds. D.S. Saunders, G.W. Arnold, A.A. Burbridge, &A.J.M. Hopkins, pp. 65-77. Surrey Beatty and Sons. \n\n![Kookaburra sitting on a branch. Photo by [pen_ash on Unsplash]( https://unsplash.com/photos/a-kookaburra-bird-perches-on-a-tree-branch-mph8XzVCVkw)](images/pen_ash-mph8XzVCVkw-unsplash.jpg)\n\n<br>\n\n## Analysis\n::: {.question}\n### Exercise 1\n\n*(i)* Write out the statistical model for a simple linear regression and define it in terms of influence of forest fragment size upon bird abundance. \nYou can write it out in words and/or in mathematical notation.\n\n*(ii)* State the hypotheses you will be testing for the relationship between bird abundance and patch area.\n\n*(iii)* Conduct some exploratory data analysis upon your two variables. Describe the spread and central tendency of each, supported by values (summary statistics) and plots. \n\n*(iv)* Investigate the relationship between bird abundance and patch area. Describe the relationship, supported by values (correlation coefficient) and plots.\n\n*(v)* Fit a simple linear regression model to the data, with bird abundance as the response variable and patch area as the predictor variable.\n\n*(vi)* Check the assumptions of your model. Do you need to transform any variables?\n\nHint 1: you can use the the `check_model()` function from the `performance` package to check the assumptions of your model.\n\nHint 2: If you do choose to transform a variable you will need to refit the model and check the assumptions again. \n\n*(vii)* Interpret the model parameters and fit statistics. Recall the key information we draw from the output; what do these statistics tell you about the relationship between bird abundance and patch area?\n\n*(viii)* Write a concluding statement on your findings. \nHint: Consider the initial aim and hypothesis of the study and write it in a way that is easily understood by your client.\n\n:::\n\n:::: {.content-visible when-profile=\"solution\"}\n::: {.ans}\n#### Solution\n\n##### *(i)* Write out the statistical model for a simple linear regression and define it in terms of influence of forest fragment size upon bird abundance. \n\nThe statistical model for a simple linear regression is: \n\n$$\ny_{i} = \\beta_0 + \\beta_1x_i + \\epsilon_{i}\n$$\n\nWhere:\n\n- $y_{i}$ is the response variable (abundance) for the $i$th observation when the predictor X = $x_i$ (area of the patch)\n- $\\beta_0$ is the intercept where the regression line crosses the y-axis (the expected abundance when patch area is 0)\n- $\\beta_1$ is the slope of the regression line, which represents the change in abundance for a one-unit increase in patch area\n- $\\epsilon_{i}$ is the random error term for the ith observation and is assumed to be normally distributed with mean 0 and constant variance \n\nOR if written in terms of the variables in our dataset, the model would be:\n\n$$\nAbundance_{i} = \\beta_0 + \\beta_1Area_i + \\epsilon_{i}\n$$\n\n##### *(ii)* State the hypotheses you will be testing for the relationship between bird abundance and patch area.\n\nThe hypotheses for the relationship between bird abundance and patch area are:\n\n$$H_0 : \\beta_1 = 0$$\n$$H_0 : \\beta_1 \\neq 0$$\nWhere $\\beta_1$ is the slope of the regression line and represents the change in abundance for a one-unit increase in patch area.\n\nRemember: Null hypothesis = no change, no slope, therefore no relationship. \n\n\n\n##### *(iii)* Read in the dataset and conduct some exploratory data analysis upon your two variables. Describe the spread and central tendency of each, supported by values (summary statistics) and plots. \n\n1. Read in the data\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load library if needed\nlibrary(readxl)\n\n# Import the data\nloyn <- read_xlsx(\"data/Loyn_SLR.xlsx\", \"Loyn_SLR\")\n\n# check\nglimpse(loyn) # could also use str() or head() to look at the data\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 56\nColumns: 2\n$ ABUND <dbl> 5.3, 2.0, 1.5, 17.1, 13.8, 14.1, 3.8, 2.2, 3.3, 3.0, 27.6, 1.8, …\n$ AREA  <dbl> 0.1, 0.5, 0.5, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 2.0, 2.0,…\n```\n\n\n:::\n:::\n\n\nWe can see there are two variables, with 56 observations each. and both are numeric (coded as 'dbl' here, which is a type of numeric/continuous  variable). \n\n2. Summary statistics\n\nI have calculated each summary statistic separately here to produce the output as a table. If you are exploring the data for yourself, you are welcome to use `summary()` function. \n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(moments) # gives us the skewness() function\n\nAbundance = c(\n  mean = mean(loyn$ABUND),\n  median = median(loyn$ABUND),\n  min = min(loyn$ABUND),\n  max = max(loyn$ABUND),\n  sd = sd(loyn$ABUND),\n  skewness = skewness(loyn$ABUND)\n)\n\nArea = c(\n  mean = mean(loyn$AREA),\n  median = median(loyn$AREA),\n  min = min(loyn$AREA),\n  max = max(loyn$AREA),\n  sd = sd(loyn$AREA),\n  skewness = skewness(loyn$AREA)\n)\n\nsummary_loyn = rbind(Abundance, Area) |> round(1)\n\nkable(summary_loyn, caption = \"Table 1. Summary statistics for bird abundance and area of forest patches\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Table 1. Summary statistics for bird abundance and area of forest patches\n\n|          | mean| median| min|    max|    sd| skewness|\n|:---------|----:|------:|---:|------:|-----:|--------:|\n|Abundance | 19.5|   21.0| 1.5|   39.6|  10.7|     -0.3|\n|Area      | 69.3|    7.5| 0.1| 1771.0| 266.1|      5.5|\n\n\n:::\n:::\n\n\n\n**Bird Abundance** (aka number of birds counted)\n\nThe mean bird abundance in forest patches is 19.5 and the median is 21.0 (Table 1). These are quite similar, suggesting a normal distribution. This is further supported by the skewness coefficient of -0.28, which is close to 0, and the relatively symmetrical boxplot (Fig. 1), indicating a fairly symmetric distribution. \n\nBird abundance ranges from a minimum of 1.5 to 39.6 birds and the standard deviation is 10.73, which indicates that there is quite a bit of variability in bird abundance across the patches. This is also evident in the wider interquartile range visible in the boxplot (fig. 1). \n\n\n::: {.cell caption='Figure 1. Boxplot of bird abundance'}\n\n```{.r .cell-code}\nggplot(loyn) + \n  geom_boxplot(aes(x = \"\", y = ABUND)) +\n  labs(title = \"Abundance\",\n       y = \"Bird abundance (number of birds)\")\n```\n\n::: {.cell-output-display}\n![](Lab07-regression-modelling_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n**Area of forest patches** (in hectares, ha)\n\nThe mean area is 69.3 ha (Table 1), which is very different to the median of 7.5 ha, suggesting a highly skewed distribution. This is further supported by the skewness coefficient of 5.5. \n\nWe can also see this high amount of variability in the standard deviation of 266.1, and the area ranging from 0.1 ha to 1771 ha. The skewness and high amount of variation is most likely a result of two outliers present, visible in the boxplot (Fig. 2). \n\n\n::: {.cell caption='Figure 2. Boxplot of area of forest patches (ha)'}\n\n```{.r .cell-code}\nggplot(loyn) +\n  geom_boxplot(aes(x = \"\", y = AREA)) +\n  labs(title = \"Area\",\n       y = \"Area of forest patch (ha)\")\n```\n\n::: {.cell-output-display}\n![](Lab07-regression-modelling_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n\n##### *(iv)* Investigate the relationship between bird abundance and patch area. Describe the relationship, supported by values (correlation coefficient) and plots.\n\nCalculate the correlation coefficient\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(loyn$AREA, loyn$ABUND) |> round(2) # calculate correlation |> round to 2 decimal places\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.26\n```\n\n\n:::\n:::\n\n\nGenerate a scatter plot\n\n::: {.cell caption='Figure 3. Scatterplot of Bird abundance vs area of forest patch (ha)'}\n\n```{.r .cell-code}\nggplot() +\n  geom_point(aes(x = loyn$AREA, y = loyn$ABUND)) + \n  labs(title = \"Bird abundance vs area of forest patch\",\n       x = \"Area of forest patch (ha)\",\n       y = \"Bird abundance (number of birds)\")\n```\n\n::: {.cell-output-display}\n![](Lab07-regression-modelling_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nThe correlation coefficient is 0.26, which indicates a weak positive relationship between patch area and bird abundance. \n\nThis is evident in the scatterplot (Fig. 3) where the relationship is not very clear, as most of the points clustered towards one side of the plot. This tells us that there is a high amount of variation in bird abundance for small patch areas, and mostly smaller areas of forest with two larger areas >500 ha.\n\n##### *(v)* Fit a simple linear regression model to the data, with bird abundance as the response variable and patch area as the predictor variable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit the model\nloyn_lm <- lm(ABUND ~ AREA, data = loyn)\n```\n:::\n\n\n##### *(vi)* Check the assumptions of your model. Do you need to transform any variables?\n\nHINT: If you do choose to transform a variable you will need to refit the model and check the assumptions again. \n\nUse the `check_model()` function to check the assumptions of the model. You can also use plot(loyn_lm) to check the assumptions, but `check_model()` gives you a prettier output.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_model(loyn_lm)\n```\n\n::: {.cell-output-display}\n![](Lab07-regression-modelling_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n* Linearity: Line doesn't follow the dashed line, indicating relationship may not be linear.   \n* I **COME BACK TO THIS**\n* Normality of residuals: Most points follow the line, but there are some deviations at the tails, suggesting that the residuals may not be perfectly normally distributed.\n* Equal variance: The reference line in the plot is not straight, and there is a funnel shape in the plot, suggesting that the variance of the residuals is not constant (heteroscedasticity).\n\n* Influential observations: Hard to see, but there is a point lying outside the dashed lines, which suggests that there may be an influential observation in the data.\n\nDecision: Usually we would transform the response variable first if the assumptions aren't met, but we know the Area variable is highly skewed, so it is worth transforming the Area variable to see if this improves the model fit.  \n\n**Transform Area and refit**\n\n::: {.cell}\n\n```{.r .cell-code}\n#I have used log10 transformation here\nloyn$log10_AREA <- log10(loyn$AREA)\n\n# refit model with the transformed variable\nloyn_lm2 <- lm(ABUND ~ log10_AREA, data = loyn)\n\n# recheck assumptions\ncheck_model(loyn_lm2)\n```\n\n::: {.cell-output-display}\n![](Lab07-regression-modelling_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\nThe assumptions of the model with the log10 transformed Area variable are much better. The relationship looks more linear, the residuals are more normally distributed, and there is less evidence of heteroscedasticity. \n\n##### *(vii)* Interpret the model parameters and fit statistics. Recall the key information we draw from the output; what do these statistics tell you about the relationship between bird abundance and patch area?\n\nGet the model summary of your final model (with the transformed variable) \n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(loyn_lm2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = ABUND ~ log10_AREA, data = loyn)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-13.380  -6.119   1.372   4.631  14.255 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   10.401      1.489   6.984 4.38e-09 ***\nlog10_AREA     9.778      1.209   8.086 7.18e-11 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 7.286 on 54 degrees of freedom\nMultiple R-squared:  0.5477,\tAdjusted R-squared:  0.5393 \nF-statistic: 65.38 on 1 and 54 DF,  p-value: 7.178e-11\n```\n\n\n:::\n:::\n\n\n1. State the model equation\nModel equation is $Abundance = 10.401 + 9.778 log10(Area)$\n\n2. Interpretation of regression coefficients\nFor every 1 unit change in log10(Area), we expect a 9.778 increase in bird abundance.\n\n3. P-value\nThe P-value for the slope coefficient is < 0.001, meaning we reject our null hypothesis that the slope is equal to zero ($H0: \\beta_1 \\neq 0$) and conclude that log10(Area) is a significant predictor of bird abundance. \n\n4. R-squared\nAs we only have one predictor in the model, we can use the r^2^ value rather than the adjusted r^2^. \n\nThe r^2^ value is 0.55, which means that 55% of the variation in bird abundance can be explained by log10(Area). This is not really a strong r^2^ value, so it suggests that there are other factors influencing bird abundance that are not included in the model.\n\n\n##### *(viii)* Write a concluding statement on your findings. \nHint: Consider the initial aim and hypothesis of the study and write it in a way that is easily understood by your client.\n\nRecall that our original aim was to investigate the influence of forest fragment size upon bird abundance. Therefore we would say something like: \n\nWe fitted a linear model (estimated using OLS) to investigate the relationship between bird abundance and forest fragment size (area) upon bird abundance (equation: abundance = $\\beta_0 + \\beta_1 \\cdot area$). \n\nThe model explains a statistically significant and moderate proportion of variance (R^2^ = 0.55, F(1, 54) = 65.38, p < .001). Within this model, the effect of forest patch area is statistically significant and positive ($\\beta_1$ = 9.778, t(54) = 8.086, p < .001).\n\n:::\n::::\n\n\n## Multiple linear regression (~ 30 minutes)\n\n**You are a water scientist tasked with analysing legacy stream runoff data to determineprecipitation sites influence the stream runoff volume. **\n\n\nThe california_streamflow dataset contains 43 years of annual precipitation measurements (in mm) taken at (originally) 6 sites in the Owens Valley in California. I have reduced this to three variables: \n\n* `lake_sabrina`: Precipitation recorded at Lake Sabrina (mm)\n* `pine_creek`: Precipitation recorded at Big Pine Creek (mm), \n* `rock_creek`: Precipitation recorded at Rock Creek (mm)\n* `runoff_volume`: Stream runoff volume measured at a site near Bishop, California (ML/year). This will be the response variable.\n\nNote the variables have already been log-transformed to increase normality of the residuals in the regressions.\n\nThis week we will focus on getting the model running and practice interpretation of the output. Next week we will focus on working out work out the most suitable model. \n\n**DATA SOURCE**\n\n\n\n\n## Analysis\n::: {.question}\n### Exercise 1\n\n*(i)* Write out the statistical model for a simple linear regression and define it in terms of influence of forest fragment size upon bird abundance. \nYou can write it out in words and/or in mathematical notation.\n\n*(ii)* State the hypotheses you will be testing for the relationship between bird abundance and patch area.\n\n*(iii)* Conduct some exploratory data analysis upon your two variables. Describe the spread and central tendency of each, supported by values (summary statistics) and plots. \n\n*(iv)* Investigate the relationship between bird abundance and patch area. Describe the relationship, supported by values (correlation coefficient) and plots.\n\n*(v)* Fit a simple linear regression model to the data, with bird abundance as the response variable and patch area as the predictor variable.\n\n*(vi)* Check the assumptions of your model. Do you need to transform any variables?\n\nHint 1: you can use the the `check_model()` function from the `performance` package to check the assumptions of your model.\n\nHint 2: If you do choose to transform a variable you will need to refit the model and check the assumptions again. \n\n*(vii)* Interpret the model parameters and fit statistics. Recall the key information we draw from the output; what do these statistics tell you about the relationship between bird abundance and patch area?\n\n*(viii)* Write a concluding statement on your findings. \nHint: Consider the initial aim and hypothesis of the study and write it in a way that is easily understood by your client.\n\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# read in the data\nstream_data <- read_xlsx(\"data/california_streamflow.xlsx\", \"streamflow\")\n\nnames(stream_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"lake_sabrina\"  \"pine_creek\"    \"rock_creek\"    \"runoff_volume\"\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ns.mod_full <-lm(runoff_volume~lake_sabrina + pine_creek + rock_creek, data=stream_data)\ns.mod_full <-lm(runoff_volume~., data=stream_data) ## you can also use the . to indicate use all variables\nsummary(s.mod_full)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = runoff_volume ~ ., data = stream_data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.09885 -0.03331  0.01025  0.03359  0.09495 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   3.25716    0.12360  26.352  < 2e-16 ***\nlake_sabrina  0.05631    0.03756   1.499  0.14185    \npine_creek    0.21085    0.06756   3.121  0.00339 ** \nrock_creek    0.43838    0.08798   4.983 1.32e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.04861 on 39 degrees of freedom\nMultiple R-squared:  0.8817,\tAdjusted R-squared:  0.8726 \nF-statistic: 96.88 on 3 and 39 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n### Partial F-Tests\n\nThe above analysis tells us that both `pine_creek` & `rock_creek` are significant, according to the t-test, in the model and `lake_sabrina` is not? This involves performing Partial F-Tests as discussed in the lecture.\n\nThis can be done in **R** by using `anova()` on two model objects. To be able to compare the models and run the anova, you need to make objects of all the possible model combinations you want to compare.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ns.mod_reduced <- lm(runoff_volume ~ rock_creek + pine_creek, data=stream_data)\nanova(s.mod_reduced, s.mod_full)\n```\n:::\n\n\nThe last row gives the results of the partial F-test.\n\n::: {.question}\n### Question 1\n\nShould we remove `lake_sabrina` from the model?\n:::\n\n::: {.content-visible when-profile=\"solution\"}\n::: {.ans}\n### Answer\n\nYes, we should remove lake_sabrina as the p-value is \\> 0.05 and opt for the simpler model.\n:::\n:::\n\n::: {.question}\n### Question 2\n\nIs the p-value for the f-test the same as for the t-test?\n:::\n\n::: {.content-visible when-profile=\"solution\"}\n::: {.ans}\n### Answer\n\nYes, P-values for the t-statistic and for the Partial F-statistic are related (Partial F = t^2^)\n:::\n:::\n\n::: {.question}\n### Question 3\n\nWrite out the hypotheses you are testing.\n:::\n\n::: {.content-visible when-profile=\"solution\"}\n::: {.ans}\n### Answer\n\nH~0~: $\\beta_{lake_sabrina} = 0$\\\nH~1~: $\\beta_{lake_sabrina} \\neq 0$\n:::\n:::\n\nPerform a Partial F-Test to work out if the removal of `lake_sabrina` and `pine_creek` improves upon the full model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ns.mod_reduced2  <- lm(runoff_volume ~ lake_sabrina + pine_creek,data=stream_data)\nanova(s.mod_reduced2, s.mod_full)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: runoff_volume ~ lake_sabrina + pine_creek\nModel 2: runoff_volume ~ lake_sabrina + pine_creek + rock_creek\n  Res.Df      RSS Df Sum of Sq     F    Pr(>F)    \n1     40 0.150845                                 \n2     39 0.092166  1   0.05868 24.83 1.321e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n::: {.question}\n### Question 4\n\nWhich variable should be added to the model containing rock_creek?\n:::\n\n::: {.content-visible when-profile=\"solution\"}\n::: {.ans}\n### Answer\n\nlake_sabrina does not improve the model with only rock_creek ($\\beta_{lake_sabrina} = 0$), so we can say that we should add pine_creek to the model containing rock_creek.\n\nRemember: H0: No difference between the models, so choose the simplest H1: Full model is better\n:::\n:::\n\n::: {.question}\n### Question 5\n\nCould things be even simpler? Perform a partial F-Test to see if a model containing rock_creek alone could be suitable.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\ns.mod_reduced3  <- lm(runoff_volume ~ rock_creek,data=stream_data)\nanova(s.mod_reduced3, s.mod_full)\n```\n:::\n\n\n::: {.content-visible when-profile=\"solution\"}\n::: {.ans}\n### Answer\n\nFitting with only rock_creek does not improve model fit (P\\<0.05) and so we can conclude that the better model is the one with pine_creek and rock_creek as predictors, with lake_sabrina removed.\n:::\n:::\n\n::: {.question}\n### Question 6\n\nWhat is your optimal model?\n:::\n\n::: {.content-visible when-profile=\"solution\"}\n::: {.ans}\n### Answer\n\nThe best model is: $runoff_volume = \\beta_0 + \\beta_1 rock_creek + \\beta_2pine_creek+ error$\n:::\n:::\n\n<hr>\n\n## Review\n\n-   Simple linear regressions model the relationship between two variables\n\n    -   We can also make linear models with more than one predictor\n\n-   We can use histograms and correlation matrices to do some preliminary exploration of the data\n\n-   If any variables are skewed, we can transform them\n\n-   Looking at a correlation matrix to identify the best predictors (for both simple and multiple linear regression)\n\n-   Fit model using `lm()` function\n\n-   Check assumptions:\n\n    -   Collinearity (multiple linear regression only)\n    -   Linearity\n    -   Independence\n    -   Normality\n    -   Equal variance\n- Use `summary()` to look at model output and interpret it\n  - F-test : overall model significance\n  - Coefficients table : individual predictors' significance\n  - R^2^ : How much variation in the data is explained by the model?\n\nThat's it for today! Great work fitting simple and multiple linear regression! Next week we jump into stepwise selection!\n\n### Attribution\n",
    "supporting": [
      "Lab07-regression-modelling_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}