{
  "hash": "0aaa3675b4462f1d1d3a2adf01889150",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"ENVX2001 Lab 07 - Regression modelling\"\n# revised-by: aca\nsubtitle: ENVX2001 Applied Statistical Methods\ndescription: The University of Sydney\ndate: today\ndate-format: \"[Semester 1,] YYYY\"\ntoc: true\ntoc-depth: 3\nresources:\n  - data/Loyn_SLR.csv\n  - data/california_streamflow.xlsx\n---\n\n\n\n# Welcome!\n\n**Idea: can use birds to demo difference between SLR and MLR. Then get DIY exercises for SLR and MLR**\n\ntutorial will need to walk through both eg first, could take an hour. Then Students DIY with other datasets\n\nThis week we will revisit simple linear regression and multiple linear regression. **DATASETS WE WILL USE...**\n\n**This week's lab will give you some practice fitting and interpreting SLR and MLR models. This will prepare you for next week's content where we will seek to improve our models, and then in week 9 we will use these improved models for prediction. **\n\n## Learning outcomes\n\nThis module links to the following unit learning outcomes: \n\n* LO3. demonstrate proficiency in the use or the statistical programming language R to apply an ANOVA and fit regression models to experimental data\n\n* LO5. interpret the output and understand conceptually how its derived of a regression, ANOVA and multivariate analysis that have been calculated by R\n\n* LO6. write statistical and modelling results as part of a scientific report\n\n## Specific goals\n\nBy the end of this lab, students should be able to use R to fit simple and multiple linear regression models. \n\nSpecifically, you should be able to:\n\n- [ ] Fit a simple linear regression model\n- [ ] Assess model assumptions and apply transformations when needed\n- [ ] Interpret model parameters and fit statistics\n- [ ] Fit a multiple linear regression model (**different structure**)\n- [ ] Assess model assumptions, recalling key differences between MLR and SLR (**collinearity**)\n- [ ] Determine the most suitable fit statistics for assessing the fit of a MLR model(**r-sq vs adj**)\n- [ ] Write a conclusion on your findings **FIX THIS UP - links to LO6**\n\n\n::: callout-tip\nPlease work on this exercise by creating your own R Markdown file.\n:::\n\n## Preparation\n\n- [ ] Install or update the `performance` package\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#install.packages(\"performance\")\nlibrary(performance)\n```\n:::\n\n\nThis package is really good for checking your models. \nFor this lab, we will focus on the `check_model()` function, which gives us nice pretty diagnostic plots for models:\n\n::: panel-tabset\n\n\n::: {.cell}\n\n```{.r .cell-code}\niris_lm<- lm(iris$Petal.Length~iris$Sepal.Length)\n```\n:::\n\n\n### `plot()`\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow=c(2,2))\nplot(iris_lm)\n```\n\n::: {.cell-output-display}\n![](Lab07-regression-modelling_files/figure-typst/unnamed-chunk-2-1.png)\n:::\n\n```{.r .cell-code}\npar(mfrow=c(1,1))\n```\n:::\n\n\n### `check_model()` from `performance`\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(performance)\ncheck_model(iris_lm)\n```\n\n::: {.cell-output-display}\n![](Lab07-regression-modelling_files/figure-typst/warning - false-1.png)\n:::\n:::\n\n\n:::\n\n### Downloads\n\n| File | Used in | Download |\n|---|---|---|\n| `Loyn_SLR.xlsx` | Exercise 1 | [Download](data/Loyn_SLR.xlsx) |\n| `california_streamflow.xlsx` | Exercise 2 | [Download](data/california_streamflow.xlsx) |\n\n\n# Simple linear regression model fitting and interpretation (~ 30 minutes)\n\nHabitat fragmentation resulting from agriculture and urbanisation has increased the rate of wildlife population decline in Australia. You are a consultant and have been asked to investigate the influence of forest fragment size upon bird abundance. You have been provided with some data containing data on bird abundance and patch area from 56 different forest patches in Southeastern Victoria, Australia, and you want to know if there is a relationship between these two variables.\n\nThe data is in the **Loyn_SLR.xlsx** file.\n\nVariables are as follows: \n\n- ABUND: Bird abundance within each forest patch (number of birds)\n- AREA: Area of each forest patch (ha)\n\nOriginal data source: Loyn, R. H. (1987). Effects of patch area and habitat on bird abundances, species numbers, and tree health in fragmented Victorian forests. In *Nature Conservation: the role of remnants of native vegetation* eds. D.S. Saunders, G.W. Arnold, A.A. Burbridge, &A.J.M. Hopkins, pp. 65-77. Surrey Beatty and Sons. \n\n## Analysis\n\n::: {.question}\n\n### Exercise 1\n\n*(i)* Write out the statistical model for a simple linear regression and define it in terms of influence of forest fragment size upon bird abundance. \nYou can write it out in words and/or in mathematical notation.\n\n\n::: {.cell}\n\n:::\n\n\n*(ii)* State the hypotheses you will be testing for the relationship between bird abundance and patch area.\n\n\n::: {.cell}\n\n:::\n\n\n*(iii)* Conduct some exploratory data analysis upon your two variables. Describe the spread and central tendency of each, supported by values (summary statistics) and plots. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Answer here\n```\n:::\n\n\n*(iv)* Look at the relationship between bird abundance and patch area. Describe the relationship, supported by values (correlation coefficient) and plots.\n\n\n::: {.cell}\n\n:::\n\n\n*(v)* Fit a simple linear regression model to the data, with bird abundance as the response variable and patch area as the predictor variable.\n\n\n::: {.cell}\n\n:::\n\n\n*(vi)* Check the assumptions of your model. Do you need to transform any variables?\n\nHint: you can use the the `check_model()` function from the `performance` package to check the assumptions of your model.\n\n\n::: {.cell}\n\n:::\n\n\n*(vii)* Interpret the model parameters and fit statistics. Recall the key information we draw from the output; what do these statistics tell you about the relationship between bird abundance and patch area?\n\n\n::: {.cell}\n\n:::\n\n\n*(viii)* Write a concluding statement on your findings. \nHint: Consider the initial aim and hypothesis of the study and write it in a way that is easily understood by your client.\n\n\n::: {.cell}\n\n:::\n\n:::\n\n::: {.content-visible when-profile=\"solution\"}\n::: {.ans}\n#### Solution\n\n##### *(i)* Write out the statistical model for a simple linear regression and define it in terms of influence of forest fragment size upon bird abundance. \n\nThe statistical model for a simple linear regression is: \n\n$$\ny_{i} = \\beta_0 + \\beta_1x_i + \\epsilon_{i}\n$$\n\nWhere:\n\n- $y_{i}$ is the response variable (abundance) for the $i$th observation when the predictor X = $x_i$ (area of the patch)\n- $\\beta_0$ is the intercept where the regression line crosses the y-axis (the expected abundance when patch area is 0)\n- $\\beta_1$ is the slope of the regression line, which represents the change in abundance for a one-unit increase in patch area\n- $\\epsilon_{i}$ is the random error term for the ith observation and is assumed to be normally distributed with mean 0 and constant variance \n\nOR if written in terms of the variables in our dataset, the model would be:\n\n$$\nAbundance_{i} = \\beta_0 + \\beta_1Area_i + \\epsilon_{i}\n$$\n\n##### *(ii)* State the hypotheses you will be testing for the relationship between bird abundance and patch area.\n\nThe hypotheses for the relationship between bird abundance and patch area are:\n\n$$H_0 : \\beta_1 = 0$$\n$$H_0 : \\beta_1 \\neq 0$$\nWhere $\\beta_1$ is the slope of the regression line and represents the change in abundance for a one-unit increase in patch area.\n\nRemember: Null hypothesis = no change, no slope, therefore no relationship. \n\n\n\n##### *(iii)* Read in the dataset and conduct some exploratory data analysis upon your two variables. Describe the spread and central tendency of each, supported by values (summary statistics) and plots. \n\n1. Read in the data\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load library if needed\nlibrary(readxl)\n\n# Import the data\nloyn <- read_xlsx(\"data/Loyn_SLR.xlsx\", \"Loyn_SLR\")\n\n# check\nglimpse(loyn)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 56\nColumns: 2\n$ ABUND <dbl> 5.3, 2.0, 1.5, 17.1, 13.8, 14.1, 3.8, 2.2, 3.3, 3.0, 27.6, 1.8, …\n$ AREA  <dbl> 0.1, 0.5, 0.5, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 2.0, 2.0,…\n```\n\n\n:::\n:::\n\n\nWe can see there are two variables, with 56 observations each. and both are numeric (coded as 'dbl' here, which is a type of numeric/continuous  variable). \n\n2. Summary statistics\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(moments) # gives us the skewness() function\n\nsummary_abund = c(\n  mean = mean(loyn$ABUND),\n  median = median(loyn$ABUND),\n  min = min(loyn$ABUND),\n  max = max(loyn$ABUND),\n  sd = sd(loyn$ABUND),\n  skewness = skewness(loyn$ABUND)\n)\n\nkable(summary_abund, caption = \"Table 1. Summary statistics for bird abundance and area of forest patches\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Table 1. Summary statistics for bird abundance and area of forest patches\n\n|         |          x|\n|:--------|----------:|\n|mean     | 19.5142857|\n|median   | 21.0500000|\n|min      |  1.5000000|\n|max      | 39.6000000|\n|sd       | 10.7347597|\n|skewness | -0.2800748|\n\n\n:::\n:::\n\n\nBird Abundance (aka number of birds counted)\n\nThe mean bird abundance in forest patches is 19.51 and the median is 21.05 (Table 1.). These are quite similar, suggesting a normal distribution. This is further supported by the skewness coefficient of -0.28, which is close to 0, and the relatively symmetrical boxplot (Fig. 1), indicating a fairly symmetric distribution. \n\nBird abundance ranges from a minimum of 1.5 to 39.6 birds and the standard deviation is 10.73, which indicates that there is quite a bit of variability in bird abundance across the patches. This is also evident in the wider interquartile range visible in the boxplot (fig. 1). \n\n\n::: {.cell caption='Figure 1. Boxplot of bird abundance'}\n\n```{.r .cell-code}\nggplot(loyn) + \n  geom_boxplot(aes(x = \"\", y = ABUND)) +\n  labs(title = \"Abundance\",\n       y = \"Bird abundance (number of birds)\")\n```\n\n::: {.cell-output-display}\n![](Lab07-regression-modelling_files/figure-typst/unnamed-chunk-13-1.png)\n:::\n:::\n\n\nArea of forest patches (in hectares, ha)\n\nThe mean area is 69.3 ha, which is very different to the median of 7.5 ha, suggesting a highly skewed distribution. This is further supported by the skewness coefficient of 5.5. \n\nWe can also see this high amount of variability in the standard deviation of 266.1, and the area ranging from 0.1 ha to 1771 ha. The skewness and high amount of variation is most likely a result of two outliers present, visible in the boxplot (Fig. 2). \n\n\n::: {.cell caption='Figure 2. Boxplot of area of forest patches (ha)'}\n\n```{.r .cell-code}\nggplot(loyn) +\n  geom_boxplot(aes(x = \"\", y = AREA)) +\n  labs(title = \"Area\",\n       y = \"Area of forest patch (ha)\")\n```\n\n::: {.cell-output-display}\n![](Lab07-regression-modelling_files/figure-typst/unnamed-chunk-14-1.png)\n:::\n:::\n\n\n\n:::\n:::\n\n### 1. Exploratory data analysis\n\nWe need to understand the data we are working with, so we need to perform exploratory data analysis. To do this, we can look at summary statistics, distributions, and visualise the data.\n\n\n\nFor linear regression, we also need to look at the relationship between the predictor and response. We first look at a scatter plot to determine if we have linear data, and then we choose a suitable correlation coefficient.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot() +\n  geom_point(aes(x = loyn$AREA, y = loyn$ABUND) +\n  labs(title = \"Bird abundance vs area of forest patch\",\n       x = \"Area of forest patch (ha)\",\n       y = \"Bird abundance (number of birds)\"))\n```\n\n::: {.cell-output-display}\n![](Lab07-regression-modelling_files/figure-typst/unnamed-chunk-15-1.png)\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(loyn$AREA, loyn$ABUND) |> round(2) # calculate correlation |> round to 2 decimal places\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.26\n```\n\n\n:::\n:::\n\n\nThe correlation coefficient is 0.26, which is quite low, indicating a weak or no positive relationship between bird abundance and patch area. \n\nHowever, we can see from the scatter plot that there is a lot of variation in bird abundance for small patch areas, and that there are some large patches with high bird abundance. This suggests that there may be other factors influencing bird abundance, and that patch area alone may not be a strong predictor. We will explore this further in next week's lecture. \n\nFor now, it is possible to fit a model of the relationship between these two variables. \n\n### 1.2 State hypotheses\n\nRemembering back to the lecture and tutorial, the general equations for our hypotheses are:\n\n$$\nH_0 : \\beta_1 = 0\n$$\n\n$$\nH_1 : \\beta_1 \\neq 0\n$$\n\nIn the context of our data, the hypotheses would be:\n\n$H_0$: Slope = 0; fertiliser is not a significant predictor of yield.\n\n$H_1$: Slope $\\neq$ 0; fertiliser is a significant predictor of yield.\n\nIf P \\> 0.05, we fail to reject the null hypothesis that the true slope ($\\beta_1$) is equal to 0. If this is the case, it means our model does not predict better than the mean of our observations, and so there is no advantage to using our model over the mean of y ($\\bar{y}$).\n\nIf we find there is a high probability of the slope not being equal to 0 (P \\< 0.05), we can reject the null hypothesis and conclude our model is better at predicting than the mean of our observations.\n\nNow we understand what we are testing for, we can fit the model.\n\n\n### 1.3 Fit a simple linear regression model\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit the model\nloyn_lm <- lm(ABUND ~ AREA, data = loyn)\nplot(loyn_lm)\n```\n\n::: {.cell-output-display}\n![](Lab07-regression-modelling_files/figure-typst/unnamed-chunk-17-1.png)\n:::\n\n::: {.cell-output-display}\n![](Lab07-regression-modelling_files/figure-typst/unnamed-chunk-17-2.png)\n:::\n\n::: {.cell-output-display}\n![](Lab07-regression-modelling_files/figure-typst/unnamed-chunk-17-3.png)\n:::\n\n::: {.cell-output-display}\n![](Lab07-regression-modelling_files/figure-typst/unnamed-chunk-17-4.png)\n:::\n\n```{.r .cell-code}\n# Look at the model sulog()# Look at the model summary\n#summary(loyn_lm) NOT YET\n```\n:::\n\n\nThe model summary gives us a lot of information about the model fit. We can see that the coefficient for log(AREA) is 0.26, which means that for every unit increase in log(AREA), we expect bird abundance to increase by 0.26 on average.\n\n### 1.4 Check model assumptions\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_model(loyn_lm)\n```\n\n::: {.cell-output-display}\n![](Lab07-regression-modelling_files/figure-typst/unnamed-chunk-18-1.png)\n:::\n:::\n\n\nThe diagnostic plots show us that the residuals are not normally distributed, and that there is some heteroscedasticity (the variance of the residuals is not constant). This suggests that the model may not be a good fit for the data, and that we may need to consider a different model or transformation of the data.\n\n### 1.5 Interpret model parameters and fit statistics\n\n### 1.6 Make conclusions\n\n\n## Exercise 2: California streamflow\n\n\nThe following dataset contains 43 years of annual precipitation measurements (in mm) taken at (originally) 6 sites in the Owens Valley in California. I have reduced this to three variables labelled `lake_sabrina` (Lake Sabrina), `pine_creek` (Big Pine Creek), `rock_creek` (Rock Creek), and the dependent variable stream runoff volume (measured in ML/year) at a site near Bishop, California (labelled `runoff_volume`).\n\nNote the variables have already been log-transformed to increase normality of the residuals in the regressions.\n\nStart with a full model and manually remove the variables one at a time, checking every time whether removal of a variable actually improves the model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# read in the data\nstream_data <- read_xlsx(\"data/california_streamflow.xlsx\", \"streamflow\")\nnames(stream_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"lake_sabrina\"  \"pine_creek\"    \"rock_creek\"    \"runoff_volume\"\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ns.mod_full <-lm(runoff_volume~lake_sabrina + pine_creek + rock_creek, data=stream_data)\ns.mod_full <-lm(runoff_volume~., data=stream_data) ## you can also use the . to indicate use all variables\nsummary(s.mod_full)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = runoff_volume ~ ., data = stream_data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.09885 -0.03331  0.01025  0.03359  0.09495 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   3.25716    0.12360  26.352  < 2e-16 ***\nlake_sabrina  0.05631    0.03756   1.499  0.14185    \npine_creek    0.21085    0.06756   3.121  0.00339 ** \nrock_creek    0.43838    0.08798   4.983 1.32e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.04861 on 39 degrees of freedom\nMultiple R-squared:  0.8817,\tAdjusted R-squared:  0.8726 \nF-statistic: 96.88 on 3 and 39 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n### Partial F-Tests\n\nThe above analysis tells us that both `pine_creek` & `rock_creek` are significant, according to the t-test, in the model and `lake_sabrina` is not? This involves performing Partial F-Tests as discussed in the lecture.\n\nThis can be done in **R** by using `anova()` on two model objects. To be able to compare the models and run the anova, you need to make objects of all the possible model combinations you want to compare.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ns.mod_reduced <- lm(runoff_volume ~ rock_creek + pine_creek, data=stream_data)\nanova(s.mod_reduced, s.mod_full)\n```\n:::\n\n\nThe last row gives the results of the partial F-test.\n\n::: {.question}\n### Question 1\n\nShould we remove `lake_sabrina` from the model?\n:::\n\n::: {.content-visible when-profile=\"solution\"}\n::: {.ans}\n### Answer\n\nYes, we should remove lake_sabrina as the p-value is \\> 0.05 and opt for the simpler model.\n:::\n:::\n\n::: {.question}\n### Question 2\n\nIs the p-value for the f-test the same as for the t-test?\n:::\n\n::: {.content-visible when-profile=\"solution\"}\n::: {.ans}\n### Answer\n\nYes, P-values for the t-statistic and for the Partial F-statistic are related (Partial F = t^2^)\n:::\n:::\n\n::: {.question}\n### Question 3\n\nWrite out the hypotheses you are testing.\n:::\n\n::: {.content-visible when-profile=\"solution\"}\n::: {.ans}\n### Answer\n\nH~0~: $\\beta_{lake_sabrina} = 0$\\\nH~1~: $\\beta_{lake_sabrina} \\neq 0$\n:::\n:::\n\nPerform a Partial F-Test to work out if the removal of `lake_sabrina` and `pine_creek` improves upon the full model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ns.mod_reduced2  <- lm(runoff_volume ~ lake_sabrina + pine_creek,data=stream_data)\nanova(s.mod_reduced2, s.mod_full)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: runoff_volume ~ lake_sabrina + pine_creek\nModel 2: runoff_volume ~ lake_sabrina + pine_creek + rock_creek\n  Res.Df      RSS Df Sum of Sq     F    Pr(>F)    \n1     40 0.150845                                 \n2     39 0.092166  1   0.05868 24.83 1.321e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n::: {.question}\n### Question 4\n\nWhich variable should be added to the model containing rock_creek?\n:::\n\n::: {.content-visible when-profile=\"solution\"}\n::: {.ans}\n### Answer\n\nlake_sabrina does not improve the model with only rock_creek ($\\beta_{lake_sabrina} = 0$), so we can say that we should add pine_creek to the model containing rock_creek.\n\nRemember: H0: No difference between the models, so choose the simplest H1: Full model is better\n:::\n:::\n\n::: {.question}\n### Question 5\n\nCould things be even simpler? Perform a partial F-Test to see if a model containing rock_creek alone could be suitable.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\ns.mod_reduced3  <- lm(runoff_volume ~ rock_creek,data=stream_data)\nanova(s.mod_reduced3, s.mod_full)\n```\n:::\n\n\n::: {.content-visible when-profile=\"solution\"}\n::: {.ans}\n### Answer\n\nFitting with only rock_creek does not improve model fit (P\\<0.05) and so we can conclude that the better model is the one with pine_creek and rock_creek as predictors, with lake_sabrina removed.\n:::\n:::\n\n::: {.question}\n### Question 6\n\nWhat is your optimal model?\n:::\n\n::: {.content-visible when-profile=\"solution\"}\n::: {.ans}\n### Answer\n\nThe best model is: $runoff_volume = \\beta_0 + \\beta_1 rock_creek + \\beta_2pine_creek+ error$\n:::\n:::\n\n<hr>\n\n## Review\n\n-   Simple linear regressions model the relationship between two variables\n\n    -   We can also make linear models with more than one predictor\n\n-   We can use histograms and correlation matrices to do some preliminary exploration of the data\n\n-   If any variables are skewed, we can transform them\n\n-   Looking at a correlation matrix to identify the best predictors (for both simple and multiple linear regression)\n\n-   Fit model using `lm()` function\n\n-   Check assumptions:\n\n    -   Collinearity (multiple linear regression only)\n    -   Linearity\n    -   Independence\n    -   Normality\n    -   Equal variance\n- Use `summary()` to look at model output and interpret it\n  - F-test : overall model significance\n  - Coefficients table : individual predictors' significance\n  - R^2^ : How much variation in the data is explained by the model?\n\nThat's it for today! Great work fitting simple and multiple linear regression! Next week we jump into stepwise selection!\n\n### Attribution\n",
    "supporting": [
      "Lab07-regression-modelling_files/figure-typst"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}