{
  "hash": "70392ab352bbeb2814f243d4c0bb93f5",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Tutorial 02\"\n# reviewed-by:\nformat:\n  sandstone-html:\n    code-tools: true\n---\n\n## Welcome {.unnumbered}\n\nIn this tutorial you will use a real dataset to compute confidence intervals and see why group structure matters when estimating a population parameter.\n\nYou will learn how to:\n\n1. Load a real dataset and compute a confidence interval using `t.test()`.\n2. Understand what a confidence interval tells you (and what it does not).\n3. See why accounting for group structure matters when estimating a population parameter.\n\nThe dataset for today comes from the `DAAG` package. The `possum` dataset contains measurements on 104 mountain brushtail possums (*Trichosurus caninus*) captured at seven sites across south-eastern Australia, from a study by Lindenmayer et al. (1995). Researchers captured possums at field sites in Victoria and in parts of Queensland and New South Wales, recording morphological measurements such as head length, skull width, tail length, and ear conch length.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(DAAG)\ndata(possum)\n```\n:::\n\n\n::: {.column-margin}\nIf you have not installed DAAG before, run `install.packages(\"DAAG\")` in the console first. You only need to do this once.\n:::\n\n\n# Confidence intervals\n\nA confidence interval is a range of plausible values for a population parameter, such as a mean, based on sample data. Instead of a single number, it tells you how much uncertainty there is in the estimate.\n\n## Exercise 1: What confidence intervals tell us {.unnumbered}\n\n### Part A --- Compute and interpret\n\nStart by inspecting the dataset:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(possum)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t104 obs. of  14 variables:\n $ case    : num  1 2 3 4 5 6 7 8 9 10 ...\n $ site    : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Pop     : Factor w/ 2 levels \"Vic\",\"other\": 1 1 1 1 1 1 1 1 1 1 ...\n $ sex     : Factor w/ 2 levels \"f\",\"m\": 2 1 1 1 1 1 2 1 1 1 ...\n $ age     : num  8 6 6 6 2 1 2 6 9 6 ...\n $ hdlngth : num  94.1 92.5 94 93.2 91.5 93.1 95.3 94.8 93.4 91.8 ...\n $ skullw  : num  60.4 57.6 60 57.1 56.3 54.8 58.2 57.6 56.3 58 ...\n $ totlngth: num  89 91.5 95.5 92 85.5 90.5 89.5 91 91.5 89.5 ...\n $ taill   : num  36 36.5 39 38 36 35.5 36 37 37 37.5 ...\n $ footlgth: num  74.5 72.5 75.4 76.1 71 73.2 71.5 72.7 72.4 70.9 ...\n $ earconch: num  54.5 51.2 51.9 52.2 53.2 53.6 52 53.9 52.9 53.4 ...\n $ eye     : num  15.2 16 15.5 15.2 15.1 14.2 14.2 14.5 15.5 14.4 ...\n $ chest   : num  28 28.5 30 28 28.5 30 30 29 28 27.5 ...\n $ belly   : num  36 33 34 34 33 32 34.5 34 33 32 ...\n```\n\n\n:::\n:::\n\n\nThere are 104 observations and 14 variables, including morphological measurements like head length, skull width, and tail length. We will focus on head length first.\n\nCompute a 95% confidence interval for the mean head length:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(possum$hdlngth)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  possum$hdlngth\nt = 264.28, df = 103, p-value < 2.2e-16\nalternative hypothesis: true mean is not equal to 0\n95 percent confidence interval:\n 91.90796 93.29781\nsample estimates:\nmean of x \n 92.60288 \n```\n\n\n:::\n:::\n\n\nThe sample mean head length is 92.6 mm. The 95% confidence interval is approximately [91.9, 93.3].\n\nWhat does this interval actually mean? If we repeated this study many times --- catching a fresh group of 104 possums each time --- about 95% of the intervals we compute would contain the true population mean.\n\nA common misconception is that there is a 95% probability the true mean lies inside this particular interval. That is not correct. The true mean is a fixed value --- it is either inside the interval or it is not. We just do not know which.\n\nPut simply: we are reasonably confident that the average head length of mountain brushtail possums in this region is somewhere between 91.9 and 93.3 mm.\n\n::: {.column-margin}\nThe 95% refers to the long-run success rate of the method, not the probability for any single interval.\n:::\n\n### Part B --- What affects the width?\n\nWhat if we had measured fewer possums? Would our confidence interval change?\n\nDraw a random sample of 10 possums and compute the confidence interval:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\nsamp10 <- sample(possum$hdlngth, 10)\nt.test(samp10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  samp10\nt = 74.625, df = 9, p-value = 7.048e-14\nalternative hypothesis: true mean is not equal to 0\n95 percent confidence interval:\n 89.44386 95.03614\nsample estimates:\nmean of x \n    92.24 \n```\n\n\n:::\n:::\n\n\nNow draw a sample of 50:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\nsamp50 <- sample(possum$hdlngth, 50)\nt.test(samp50)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  samp50\nt = 181.77, df = 49, p-value < 2.2e-16\nalternative hypothesis: true mean is not equal to 0\n95 percent confidence interval:\n 91.13518 93.17282\nsample estimates:\nmean of x \n   92.154 \n```\n\n\n:::\n:::\n\n\nCompare the widths. With 10 possums the interval is roughly 5.6 mm wide, with 50 it narrows to about 2.0 mm, and with all 104 it is only 1.4 mm. More data gives a more precise estimate.\n\nThis happens because the standard error is SD / $\\sqrt{n}$. As $n$ increases, the standard error shrinks, and so does the confidence interval. This is what `t.test()` computes internally.\n\n::: {.column-margin}\nTry changing the seed or the sample size and re-running to see how your interval changes.\n:::\n\n::: {.callout-note}\n## Checkpoint\nYou should be able to explain what a 95% confidence interval means in plain language and why a larger sample gives a narrower interval.\n:::\n\n\n# Sampling and group structure\n\nSo far we have treated all 104 possums as one group. But what happens when a population contains distinct subgroups?\n\n## Exercise 2: When groups matter {.unnumbered}\n\n### Part A --- The pooled estimate\n\nCompute a confidence interval for ear conch length across all possums:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(possum$earconch)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  possum$earconch\nt = 119.44, df = 103, p-value < 2.2e-16\nalternative hypothesis: true mean is not equal to 0\n95 percent confidence interval:\n 47.33160 48.92994\nsample estimates:\nmean of x \n 48.13077 \n```\n\n\n:::\n:::\n\n\nThis interval estimates the average ear conch length --- the length of the outer ear opening --- across all 104 possums. The mean is about 48.1 mm, with a 95% CI of roughly [47.3, 48.9].\n\nBut these possums come from two distinct populations: Victorian possums from sites in central and eastern Victoria, and possums from sites further north in New South Wales and Queensland.\n\n### Part B --- Split by population\n\nCompute separate confidence intervals for each population:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(possum$earconch[possum$Pop == \"Vic\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  possum$earconch[possum$Pop == \"Vic\"]\nt = 153.2, df = 45, p-value < 2.2e-16\nalternative hypothesis: true mean is not equal to 0\n95 percent confidence interval:\n 51.50087 52.87304\nsample estimates:\nmean of x \n 52.18696 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(possum$earconch[possum$Pop == \"other\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  possum$earconch[possum$Pop == \"other\"]\nt = 216.63, df = 57, p-value < 2.2e-16\nalternative hypothesis: true mean is not equal to 0\n95 percent confidence interval:\n 44.49862 45.32896\nsample estimates:\nmean of x \n 44.91379 \n```\n\n\n:::\n:::\n\n\nThe Victorian possums have a mean ear conch length of about 52.2 mm, while the other population averages about 44.9 mm --- a difference of over 7 mm. The pooled confidence interval of [47.3, 48.9] sits between the two groups and does not accurately describe either population.\n\nA boxplot makes the separation clear:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nggplot(possum, aes(x = Pop, y = earconch, fill = Pop)) +\n  geom_boxplot(show.legend = FALSE) +\n  labs(x = \"Population\", y = \"Ear conch length (mm)\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![Ear conch length by population](tutorial02_files/figure-typst/fig-earconch-1.png){#fig-earconch}\n:::\n:::\n\n\n### Part C --- Connection to the lab\n\nWhen a population has distinct subgroups, a single estimate can hide real differences. In the lab, you will learn **stratified random sampling** --- a method that estimates each subgroup separately and then combines them into a single, more accurate overall estimate.\n\n::: {.callout-note}\n## Checkpoint\nYou should be able to explain why computing a single confidence interval for a population with distinct subgroups can be misleading.\n:::\n\n\n## Wrap-up {.unnumbered}\n\nIn this tutorial you computed confidence intervals, saw how sample size affects precision, and discovered why group structure matters. You will use all of these ideas in the lab.\n",
    "supporting": [
      "tutorial02_files/figure-typst"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}