{
  "hash": "dfb41153084bd13fe20701559009173c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Lab 05\n# revised-by:\nsubtitle: ENVX2001 Applied Statistical Methods\ndescription: The University of Sydney\ntoc: true\ntoc-depth: 3\nresources:\n  - data/crd_dingo_fox_exclusion.csv\n  - data/rcbd_mammals.csv\n---\n\n# Welcome!\n\nThis week we will analyse two experiments using one-way ANOVA: a completely randomised design investigating dingo and fox activity from camera trap data, and a randomised complete block design examining fire severity effects on small mammal abundance.\n\nYou will come across **Exercises** in this lab. Solutions will be posted on Friday evening.\n\n## Learning outcomes\n\nIn this lab, we will learn how to:\n\n1. Use R to analyse CRDs and RCBDs.\n2. Assess the usefulness of blocking.\n\n## Specific goals\n\nBy the end of this lab, you should be able to:\n\n- [ ] Fit and interpret a one-way ANOVA for a CRD\n- [ ] Check ANOVA assumptions using diagnostic plots\n- [ ] Perform post-hoc tests using `emmeans`\n- [ ] Fit a one-way ANOVA with a blocking term for an RCBD\n- [ ] Calculate the percentage of variation explained by blocking\n\n## Preparation\n\nThis lab uses `emmeans`. Install it if you are missing it by running the following **in the console**:\n\n```r\ninstall.packages(\"emmeans\")\n```\n\n### Downloads\n\n| File | Used in | Download |\n|---|---|---|\n| `crd_dingo_fox_exclusion.csv` | Section 1 | [Download](data/crd_dingo_fox_exclusion.csv) |\n| `rcbd_mammals.csv` | Section 2 | [Download](data/rcbd_mammals.csv) |\n\nSave the files into a folder called `data` inside your project folder.\n\n\n# 1. Completely randomised design (~25 min)\n\nYou are tasked with analysing data from an experiment that investigated the effect of dingo activity on fox activity. You set out camera traps at 36 sites for 36 days at sites with high, medium and no dingoes (exclusion). You recorded the number of foxes that were captured on camera. Our measure of activity is the number of images per 100 trap nights. This was calculated by:\n\n$$FoxRatePer100 = \\frac{FoxDetections}{TrapNights} \\times 100$$\n\n\n\n![Introduced red fox (*Vulpes vulpes*) caught on camera trap in the Greater Blue Mountains World Heritage Area. Image credit: Ecosystems Dynamics Lab, The University of Sydney.](images/Juv_Fox.jpeg){fig-align=\"center\" width=\"767\"}\n\n\n\nWe predict Higher fox activity → lower dingo activity based on mesopredator release hypothesis.\n\n\nData is in the **crd_dingo_fox_exclusion.csv** file.\n\n- Experimental units: Sites (randomly assigned to treatments; no blocking)\n- Factor: DingoActivity (3 levels: High, Medium, Exclusion)\n- Response: FoxRatePer100 (images per 100 trap-nights)\n- Replicates: n = 12 sites per treatment (36 total)\n\nOther variables:\n\n- SiteID: unique identifier for each site\n- TrapNights: number of nights the camera trap was active at each site (max of 36, but some cameras surveyed for less)\n- FoxDetections: number of images of foxes captured by the camera trap at each site\n\nStatistical model for CRD:\n$$Y_{ij} = \\mu + \\alpha_i + \\epsilon_{ij}$$\nWhere:\n\n- $Y_{ij}$ is the observed fox activity (FoxRatePer100) at the $j$-th site in the $i$-th dingo activity level.\n- $\\mu$ is the overall mean fox activity across all dingo activity levels.\n\nOR:\n\n$$fox\\ activity = overall\\ mean + dingo\\ activity + random\\ error.$$\n\n## Analysis\n\n::: {.question}\n### Exercise 1\n\n*(i)* Test the assumptions of the ANOVA and transform the data (if needed). Hint first run the model using the `aov()` function and then use the `plot()` function to check the assumptions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#\n```\n:::\n\n\n*(ii)* Use an ANOVA to analyse the CRD and report on the results.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#\n```\n:::\n\n\n*(iii)* Explore any significant results using post-hoc tests from `emmeans` package and its `emmeans()` function. Include any plots that you think are useful to visualise the results.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#\n```\n:::\n\n:::\n\n::: {.content-visible when-profile=\"solution\"}\n::: {.ans}\n#### Solution\n\n##### (i) Check assumptions\n\n::: {.cell}\n\n```{.r .cell-code}\nfoxes<-read.csv(\"data/crd_dingo_fox_exclusion.csv\", header=TRUE)\nhead(foxes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  SiteID DingoActivity TrapNights FoxDetections FoxRatePer100\n1    S01     Exclusion         27             4     14.814815\n2    S02     Exclusion         30             7     23.333333\n3    S03        Medium         31             2      6.451613\n4    S04     Exclusion         30             7     23.333333\n5    S05        Medium         32             4     12.500000\n6    S06        Medium         36             2      5.555556\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfox.anova<-aov(FoxRatePer100~DingoActivity,data=foxes)\n\npar(mfrow=c(2,2))\nplot(fox.anova)\n```\n\n::: {.cell-output-display}\n![](Lab05-exp-designs_files/figure-typst/unnamed-chunk-5-1.png)\n:::\n\n```{.r .cell-code}\npar(mfrow=c(1,1))\n```\n:::\n\n\nAssumptions of normality and homogeneity of variance appear to be met, so we can proceed with the ANOVA results.\n\n##### (ii) ANOVA results\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(fox.anova)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              Df Sum Sq Mean Sq F value   Pr(>F)    \nDingoActivity  2   1156   578.1   17.49 6.63e-06 ***\nResiduals     33   1091    33.1                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\nThere is a significant effect of dingo activity on fox activity (F~1,18~ = 17.49; P < 0.01).\n\n\n##### (iii) Perform post-hoc tests.\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(emmeans)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWelcome to emmeans.\nCaution: You lose important information if you filter this package's results.\nSee '? untidy'\n```\n\n\n:::\n\n```{.r .cell-code}\nemmeans(fox.anova, pairwise ~ DingoActivity )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$emmeans\n DingoActivity emmean   SE df lower.CL upper.CL\n Exclusion      17.91 1.66 33   14.534     21.3\n High            4.22 1.66 33    0.846      7.6\n Medium          9.07 1.66 33    5.692     12.4\n\nConfidence level used: 0.95 \n\n$contrasts\n contrast           estimate   SE df t.ratio p.value\n Exclusion - High      13.69 2.35 33   5.832  <.0001\n Exclusion - Medium     8.84 2.35 33   3.767  0.0018\n High - Medium         -4.85 2.35 33  -2.065  0.1129\n\nP value adjustment: tukey method for comparing a family of 3 estimates \n```\n\n\n:::\n:::\n\n\nThere are significantly more foxes at sites with no dingo activity (mean = 17.91; t = 5.83, df = 22, P < 0.01) than at sites with high dingo activity (mean = 4.22) or medium dingo activity (mean = 9.07; t = 3.77; df = 33; P = 0.002).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(emmeans(fox.anova, \"DingoActivity\"), comparisons = TRUE)\n```\n\n::: {.cell-output-display}\n![](Lab05-exp-designs_files/figure-typst/unnamed-chunk-8-1.png)\n:::\n:::\n\n\nConclusion: The results support the mesopredator release hypothesis, with higher fox activity at sites with no dingo activity. Interestingly, there is no significant difference in fox activity between sites with medium and high dingo activity, suggesting that even moderate dingo activity may suppress fox activity.\n\n:::\n:::\n\nBefore we move on, now is a good time to take a 5-minute break.\n\n\n# 2. Randomised complete block design (~25 min)\n\nA researcher designs a study to investigate the effect of fire treatment (unburnt, low severity and high severity) on small mammal abundance. They set up four blocks (Block_1, Block_2, etc) and select sites that were unburnt, low severity and high severity fire within each block. At each site to survey small mammal abundance.  The data is in the **rcbd_mammals.csv** file.\n\n![Fire severity classes. Image credit: CoPilot.](images/fire_severity.png){fig-align=\"center\" width=\"767\"}\n\n## Analysis\n\n\n::: {.question}\n### Exercise 2\n\n*(i)* Write out the statistical model for the ANOVA model for this experiment.  Define all the terms in the model. You can write out in words or in mathematical notation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Answer here\n```\n:::\n\n\n\n\n*(ii)* Test the assumptions of the ANOVA and transform the data (if needed). Hint first run the model using the `aov()` function and then use the `plot()` function to check the assumptions.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#\n```\n:::\n\n\n\n*(iii)* Use an ANOVA to analyse the RCBD and report on the results.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#\n```\n:::\n\n\n\n*(iv)* Explore any significant results using post-hoc tests from `emmeans` package and its `emmeans()` function. Include any plots that you think are useful to visualise the results.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#\n```\n:::\n\n\n\n*(v)* Calculate the variation explained by the blocking term.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#\n```\n:::\n\n:::\n\n::: {.content-visible when-profile=\"solution\"}\n::: {.ans}\n#### Solution\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire<-read.csv(\"data/rcbd_mammals.csv\", header=TRUE)\nhead(fire)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Block Treatment Abundance\n1 Block_1   Unburnt        23\n2 Block_1       Low        23\n3 Block_1      High         8\n4 Block_2   Unburnt        26\n5 Block_2       Low        25\n6 Block_2      High         8\n```\n\n\n:::\n\n```{.r .cell-code}\nblock.anova<-aov(Abundance~Block+Treatment,data=fire)\n```\n:::\n\n\n##### (i) Statistical model\nThe statistical model for the RCBD can be written in mathematical notation as:\n$$Y_{ijk} = \\mu + \\alpha_i + \\beta_j + \\epsilon_{ijk}$$\n\nWhere:\n\n- $Y_{ijk}$ is the observed abundance of small mammals at the $k$-th site in the $i$-th block and $j$-th treatment.\n- $\\mu$ is the overall mean abundance of small mammals across all treatments and blocks.\n- $\\alpha_i$ is the effect of the $i$-th block (i = 1, 2, 3, 4).\n- $\\beta_j$ is the effect of the $j$-th treatment (j = unburnt, low severity, high severity).\n- $\\epsilon_{ijk}$ is the random error term associated with the $k$-th site in the $i$-th block and $j$-th treatment, assumed to be independently and identically distributed with mean 0 and variance $\\sigma^2$.\n\nOR:\n\n$$Abundance\\ of\\ small\\ mammals = overall\\ mean + block + fire\\ treatment + random\\ error$$\n\n\n\n##### (ii) Check assumptions\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow=c(2,2))\nplot(block.anova)\n```\n\n::: {.cell-output-display}\n![](Lab05-exp-designs_files/figure-typst/unnamed-chunk-15-1.png)\n:::\n\n```{.r .cell-code}\npar(mfrow=c(1,1))\n```\n:::\n\nAssumptions of normality and homogeneity of variance appear to be met, so we can proceed with the ANOVA results.\n\n##### (iii) ANOVA results\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(block.anova)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value  Pr(>F)    \nBlock        3   16.7    5.56   0.837 0.52104    \nTreatment    2  465.5  232.75  35.059 0.00049 ***\nResiduals    6   39.8    6.64                    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\nThere is a significant effect of fire treatment on small mammal abundance (F~2,6~ = 35.06; P = 0.0005).\n\n\n##### (iv) Perform post-hoc tests.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(emmeans)\nemmeans(block.anova, pairwise ~ Treatment)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$emmeans\n Treatment emmean   SE df lower.CL upper.CL\n High        9.25 1.29  6      6.1     12.4\n Low        21.50 1.29  6     18.3     24.7\n Unburnt    23.25 1.29  6     20.1     26.4\n\nResults are averaged over the levels of: Block \nConfidence level used: 0.95 \n\n$contrasts\n contrast       estimate   SE df t.ratio p.value\n High - Low       -12.25 1.82  6  -6.724  0.0013\n High - Unburnt   -14.00 1.82  6  -7.684  0.0006\n Low - Unburnt     -1.75 1.82  6  -0.961  0.6257\n\nResults are averaged over the levels of: Block \nP value adjustment: tukey method for comparing a family of 3 estimates \n```\n\n\n:::\n:::\n\n\nThere are significant differences in mean abundance of small mammals between High and low fire severity (t = -6.72; df = 6; P = 0.001) and high fire severity and unburnt sites (t = -7.68 df = 6; P = 0.0006), but no difference in abundance between low severity and unburnt sites (t = -0.96; df = 6; P = 0.63). Sites that burnt at high severity had significantly lower mean abundance (9.25) of small mammals than both low severity (21.5) and unburnt sites (23.25).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(emmeans(block.anova, \"Treatment\"), comparisons = TRUE)\n```\n\n::: {.cell-output-display}\n![](Lab05-exp-designs_files/figure-typst/unnamed-chunk-18-1.png)\n:::\n:::\n\n\nConclusion: The results suggest that high severity fire has a significant negative effect on small mammal abundance, while low severity fire does not differ significantly from unburnt sites.\n\n\n##### (v) Calculate the variation explained by the blocking term\n\nThe proportion of variation explained by the Blocking is:\n\n$\\frac{Block\\ SS}{Total\\ SS}\\times 100$\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Note you can just use a calculator and ANOVA table to do this, but here is how you would do it in R for repeatability.\n\nsummary(block.anova)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value  Pr(>F)    \nBlock        3   16.7    5.56   0.837 0.52104    \nTreatment    2  465.5  232.75  35.059 0.00049 ***\nResiduals    6   39.8    6.64                    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nanova_table <- summary(block.anova)[[1]]\n\nss_total <- sum(anova_table$`Sum Sq`)\nss_treatment <- anova_table$`Sum Sq`[2]\nss_block <- anova_table$`Sum Sq`[1]\n\npercent_treatment <- (ss_treatment / ss_total) * 100\npercent_block <- (ss_block / ss_total) * 100\n\ncat(\"\\n\")\n```\n\n```{.r .cell-code}\ncat(\"Percentage of variation explained by treatments:\", round(percent_treatment, 1), \"%\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPercentage of variation explained by treatments: 89.2 %\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Percentage of variation explained by blocks:\", round(percent_block, 1), \"%\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPercentage of variation explained by blocks: 3.2 %\n```\n\n\n:::\n:::\n\n\n:::\n:::\n\n\n# Conclusion\n\n## Closing thoughts\n\nWe analysed two experimental designs this week: a CRD using camera trap data to test the mesopredator release hypothesis, and an RCBD examining fire severity effects on small mammal abundance. These designs and analysis techniques will continue to be used as we work with more complex models throughout the course.\n\n### Attribution\n\nThis lab was developed using resources that are available under a\n[Creative Commons Attribution 4.0 International license], made available\non the [SOLES Open Educational Resources repository].\n\n  [Creative Commons Attribution 4.0 International license]: http://creativecommons.org/licenses/by/4.0/\n  [SOLES Open Educational Resources repository]: https://github.com/usyd-soles-edu/\n",
    "supporting": [
      "Lab05-exp-designs_files/figure-typst"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}